IF
  Global("ForgeStuff","GLOBAL",0)
  Global("CDTime","AR0334",1)
THEN
  RESPONSE #100
    SetGlobal("CDTime","AR0334",0)
END

IF
  Time(0)
  Global("ForgeStuff","GLOBAL",1)
  Global("CDTime","AR0334",0)
THEN
  RESPONSE #100
    DayNight(23)
    SetGlobal("CDTime","AR0334",1)
    Continue()
END

IF
  Time(1)
  Global("ForgeStuff","GLOBAL",1)
  Global("CDTime","AR0334",0)
THEN
  RESPONSE #100
    DayNight(0)
    SetGlobal("CDTime","AR0334",1)
    Continue()
END

IF
  Time(2)
  Global("ForgeStuff","GLOBAL",1)
  Global("CDTime","AR0334",0)
THEN
  RESPONSE #100
    DayNight(1)
    SetGlobal("CDTime","AR0334",1)
    Continue()
END

IF
  Time(3)
  Global("ForgeStuff","GLOBAL",1)
  Global("CDTime","AR0334",0)
THEN
  RESPONSE #100
    DayNight(2)
    SetGlobal("CDTime","AR0334",1)
    Continue()
END

IF
  Time(4)
  Global("ForgeStuff","GLOBAL",1)
  Global("CDTime","AR0334",0)
THEN
  RESPONSE #100
    DayNight(3)
    SetGlobal("CDTime","AR0334",1)
    Continue()
END

IF
  Time(5)
  Global("ForgeStuff","GLOBAL",1)
  Global("CDTime","AR0334",0)
THEN
  RESPONSE #100
    DayNight(4)
    SetGlobal("CDTime","AR0334",1)
    Continue()
END

IF
  Time(6)
  Global("ForgeStuff","GLOBAL",1)
  Global("CDTime","AR0334",0)
THEN
  RESPONSE #100
    DayNight(5)
    SetGlobal("CDTime","AR0334",1)
    Continue()
END

IF
  Time(7)
  Global("ForgeStuff","GLOBAL",1)
  Global("CDTime","AR0334",0)
THEN
  RESPONSE #100
    DayNight(6)
    SetGlobal("CDTime","AR0334",1)
    Continue()
END

IF
  Time(8)
  Global("ForgeStuff","GLOBAL",1)
  Global("CDTime","AR0334",0)
THEN
  RESPONSE #100
    DayNight(7)
    SetGlobal("CDTime","AR0334",1)
    Continue()
END

IF
  Time(9)
  Global("ForgeStuff","GLOBAL",1)
  Global("CDTime","AR0334",0)
THEN
  RESPONSE #100
    DayNight(8)
    SetGlobal("CDTime","AR0334",1)
    Continue()
END

IF
  Time(10)
  Global("ForgeStuff","GLOBAL",1)
  Global("CDTime","AR0334",0)
THEN
  RESPONSE #100
    DayNight(9)
    SetGlobal("CDTime","AR0334",1)
    Continue()
END

IF
  Time(11)
  Global("ForgeStuff","GLOBAL",1)
  Global("CDTime","AR0334",0)
THEN
  RESPONSE #100
    DayNight(10)
    SetGlobal("CDTime","AR0334",1)
    Continue()
END

IF
  Time(12)
  Global("ForgeStuff","GLOBAL",1)
  Global("CDTime","AR0334",0)
THEN
  RESPONSE #100
    DayNight(11)
    SetGlobal("CDTime","AR0334",1)
    Continue()
END

IF
  Time(13)
  Global("ForgeStuff","GLOBAL",1)
  Global("CDTime","AR0334",0)
THEN
  RESPONSE #100
    DayNight(12)
    SetGlobal("CDTime","AR0334",1)
    Continue()
END

IF
  Time(14)
  Global("ForgeStuff","GLOBAL",1)
  Global("CDTime","AR0334",0)
THEN
  RESPONSE #100
    DayNight(13)
    SetGlobal("CDTime","AR0334",1)
    Continue()
END

IF
  Time(15)
  Global("ForgeStuff","GLOBAL",1)
  Global("CDTime","AR0334",0)
THEN
  RESPONSE #100
    DayNight(14)
    SetGlobal("CDTime","AR0334",1)
    Continue()
END

IF
  Time(16)
  Global("ForgeStuff","GLOBAL",1)
  Global("CDTime","AR0334",0)
THEN
  RESPONSE #100
    DayNight(15)
    SetGlobal("CDTime","AR0334",1)
    Continue()
END

IF
  Time(17)
  Global("ForgeStuff","GLOBAL",1)
  Global("CDTime","AR0334",0)
THEN
  RESPONSE #100
    DayNight(16)
    SetGlobal("CDTime","AR0334",1)
    Continue()
END

IF
  Time(18)
  Global("ForgeStuff","GLOBAL",1)
  Global("CDTime","AR0334",0)
THEN
  RESPONSE #100
    DayNight(17)
    SetGlobal("CDTime","AR0334",1)
    Continue()
END

IF
  Time(19)
  Global("ForgeStuff","GLOBAL",1)
  Global("CDTime","AR0334",0)
THEN
  RESPONSE #100
    DayNight(18)
    SetGlobal("CDTime","AR0334",1)
    Continue()
END

IF
  Time(20)
  Global("ForgeStuff","GLOBAL",1)
  Global("CDTime","AR0334",0)
THEN
  RESPONSE #100
    DayNight(19)
    SetGlobal("CDTime","AR0334",1)
    Continue()
END

IF
  Time(21)
  Global("ForgeStuff","GLOBAL",1)
  Global("CDTime","AR0334",0)
THEN
  RESPONSE #100
    DayNight(20)
    SetGlobal("CDTime","AR0334",1)
    Continue()
END

IF
  Time(22)
  Global("ForgeStuff","GLOBAL",1)
  Global("CDTime","AR0334",0)
THEN
  RESPONSE #100
    DayNight(21)
    SetGlobal("CDTime","AR0334",1)
    Continue()
END

IF
  Time(23)
  Global("ForgeStuff","GLOBAL",1)
  Global("CDTime","AR0334",0)
THEN
  RESPONSE #100
    DayNight(22)
    SetGlobal("CDTime","AR0334",1)
    Continue()
END