IF
  GlobalTimerExpired("FindShagbag","GLOBAL")
  Global("CDShagbagHogsScript","AR0400",0)
THEN
  RESPONSE #100
    SetGlobal("CDShagbagHogsScript","AR0400",1)
    ActionOverride("korshag",DestroySelf())
    ActionOverride("korcrazy",DestroySelf())
    ActionOverride("korscroo",DestroySelf())
    ActionOverride("korgoo01",DestroySelf())
    ActionOverride("korgoo02",DestroySelf())
END
