/////                                                  \\\\\
///// bulk item file fixes                             \\\\\
/////                                                  \\\\\

ACTION_DEFINE_ASSOCIATIVE_ARRAY cd_bulk_changes_itm BEGIN

  //file, timing, magical, power, speed, weight, thac0, lore, type, prof, enchantment, dispellable => file // notes
  aegis, 1, null, null, 1, null, null, null, null, 97, 3, null => aegis // Aegis Fang
  aegis2, 1, null, null, 1, null, null, null, null, 97, 3, null => aegis2 // Aegis Fang
  aeriebab, null, 1, null, null, null, null, null, null, null, null, null => aeriebab // Aerie's Baby
  arow01, null, null, null, null, null, null, null, null, 2, null, null => arow01 // Arrows
  arow02, null, null, null, null, null, null, null, null, 2, null, null => arow02 // Arrows +1
  arow03, null, null, null, null, null, null, null, null, 2, null, null => arow03 // Arrow of Slaying
  arow04, null, null, null, null, null, null, null, null, 2, 1, null => arow04 // Acid Arrows
  arow05, null, null, null, null, null, null, null, null, 2, null, null => arow05 // Arrow of Biting
  arow06, null, null, 0, null, null, null, null, null, 2, null, null => arow06 // Arrows of Detonation 
  arow07, null, null, null, null, null, null, null, null, 2, null, null => arow07 // Arrows of Dispelling
  arow08, null, null, 0, null, null, 0, null, null, 2, null, null => arow08 // Arrow of Fire
  arow09, null, null, 0, null, null, null, null, null, 2, null, null => arow09 // Arrows of Ice
  arow10, null, null, null, null, null, null, null, null, 2, null, null => arow10 // Arrows of Piercing
  arow11, null, null, null, null, null, null, null, null, 2, null, null => arow11 // Arrow +2
  arow14, null, null, null, null, null, null, null, null, 2, null, null => arow14 // Poisoned Arrow
  arow15, null, null, null, null, null, null, null, null, 2, null, null => arow15 // Arrow +3
  arow1a, null, null, null, null, null, null, null, null, 2, null, null => arow1a // Arrow +2
  aurstaf, null, null, 0, null, null, null, null, null, null, null, null => aurstaf // Staff of the Ram +4
  ax1h04, 1, null, null, null, null, null, null, null, null, null, null => ax1h04 // Throwing Axe
  ax1h05, 1, null, null, null, null, null, null, null, null, null, null => ax1h05 // Throwing Axe +2
  ax1h06, 1, null, null, null, null, null, null, null, null, null, null => ax1h06 // Throwing Axe +2
  ax1h07, null, null, 0, 7, null, null, 65, null, null, null, null => ax1h07 // Bala's Axe
  ax1h08, 1, null, null, null, null, null, null, null, null, null, null => ax1h08 // Hangard's Axe +2
  bag06, null, null, null, null, 2, null, null, null, null, null, null => bag06 // Potion Case
  bazpatrg, 1, null, null, null, null, null, null, null, null, null, null => bazpatrg // Ring
  bearspir, null, 1, null, null, null, null, null, null, null, 3, null => bearspir // Attack
  blun01, 1, null, null, null, null, null, null, null, null, null, null => blun01 // Club
  blun03, null, null, null, null, 13, null, null, null, null, null, null => blun03 // Flail +1
  blun04, 1, null, null, null, 10, null, null, null, null, null, null => blun04 // Mace
  blun06, 1, null, null, null, null, null, null, null, null, null, null => blun06 // Morning Star
  blun10, 1, null, null, null, null, null, null, null, null, null, null => blun10 // The Root of the Problem
  blun14d, null, null, null, 5, null, null, null, null, null, null, null => blun14d // Flail of Ages
  blun14e, null, null, null, 5, null, null, null, null, null, null, null => blun14e // Flail of Ages
  blun14f, null, null, null, 5, null, null, null, null, null, null, null => blun14f // Flail of Ages
  blun20, null, null, 0, null, null, null, null, null, null, null, null => blun20 // Ardulia's Fall +1
  blun22, null, null, null, 1, null, null, null, null, null, null, null => blun22 // Club +3, Blackblood
  blun23, 1, null, null, null, null, null, null, null, null, null, null => blun23 // Bone Club +2, +3 vs. Undead
  blun24, 1, null, null, null, null, null, null, null, null, null, null => blun24 // Club +2, Gnasher
  blun25, null, null, null, 5, null, null, null, null, null, null, null => blun25 // Mace of Disruption +2
  blun26, null, null, null, 1, null, null, null, null, null, null, null => blun26 // Club of Detonation +3
  blun27, null, null, null, 0, null, null, null, null, null, null, null => blun27 // Club of Detonation +5
  blun31, 1, null, null, null, null, null, null, null, null, null, null => blun31 // Club +3
  blun35, null, null, null, 3, null, null, null, null, null, null, null => blun35 // Ice Star +4
  bodhi, 1, null, null, null, null, null, null, null, null, null, null => bodhi // <Invalid Strref -1>
  bolt01, null, null, null, null, null, null, null, null, 2, null, null => bolt01 // Bolt
  bolt02, null, null, null, null, null, null, null, null, 2, null, null => bolt02 // Bolt +1
  bolt03, null, null, 0, null, null, null, null, null, 2, null, null => bolt03 // Bolt of Lightning
  bolt04, null, null, null, null, null, null, null, null, 2, null, null => bolt04 // Bolt of Biting 
  bolt05, null, null, 0, null, null, null, null, null, 2, null, null => bolt05 // Bolt of Polymorphing
  bolt06, null, null, null, null, null, null, null, null, 2, null, null => bolt06 // Bolt +2
  bolt07, null, null, null, null, 0, null, null, null, 2, 1, null => bolt07 // Flasher Master Bruiser Mate
  bolt08, null, null, null, null, null, null, null, null, 2, null, null => bolt08 // Blessed Bolt
  bolt09, null, null, null, null, null, null, null, null, 2, null, null => bolt09 // Bolt +3
  bonedag, null, null, 0, null, null, null, null, null, null, null, null => bonedag // Mordenkainen's Sword
  bonefd, null, 1, null, null, null, null, null, null, null, null, null => bonefd // Skull
  book05, null, null, null, null, null, null, null, 0, null, null, null => book05 // Manual of Quickness of Action 
  book07, null, null, null, null, null, null, null, 0, null, null, null => book07 // Tome of Leadership and Influence
  book08, null, null, null, null, null, null, null, 0, null, null, null => book08 // Tome of Understanding
  book32, null, null, null, null, null, null, null, 37, null, null, null => book32 // History of Tethyr
  book94, null, null, null, null, null, null, null, 37, null, null, null => book94 // The Vapiricus Omnibus: Unabridged
  book95, null, null, null, null, null, null, null, 37, null, null, null => book95 // Dea Vampir Becomos
  book96, null, null, null, null, null, null, null, 37, null, null, null => book96 // Conjur Ota Servanta
  boot10, 1, null, null, null, null, null, null, null, null, null, null => boot10 // Boots of Lightning Speed
  boot12, null, null, null, null, null, null, 55, null, null, null, null => boot12 // Gargoyle Boots
  bootdriz, null, 1, null, null, null, null, null, null, null, null, null => bootdriz // Boots of Speed
  bow02, 1, null, null, null, null, null, null, null, null, null, null => bow02 // Composite Long Bow +1
  bow05, 1, null, null, null, null, null, null, null, null, null, null => bow05 // Short Bow
  bow06, null, null, null, null, 2, null, null, null, null, null, null => bow06 // Short Bow +1
  bow07, null, null, null, null, null, null, null, null, 104, null, null => bow07 // Long Bow of Marksmanship
  bow08, 1, null, null, null, null, null, null, null, null, null, null => bow08 // Eagle Bow
  bow09, 1, null, null, null, null, null, null, null, null, null, null => bow09 // Ripper +2
  bow10, 1, null, null, null, null, null, null, null, null, null, null => bow10 // Heartseeker +3
  bow11, 1, null, null, null, null, null, null, null, null, null, null => bow11 // Strong Arm +2
  bow13, null, null, null, null, null, 5, null, null, null, null, null => bow13 // Mana Bow +4
  bow14, 1, null, null, null, null, null, null, null, null, null, null => bow14 // Tuigan Bow +1
  bow15, 1, null, null, null, null, null, null, null, null, null, null => bow15 // Tansheron's Bow +3
  bow16, 1, null, null, null, null, null, null, null, null, null, null => bow16 // Composite Long Bow +2
  bow17, null, null, null, 5, null, null, null, null, null, null, null => bow17 // Long Bow +2
  bow18, 1, null, null, null, null, null, null, null, null, null, null => bow18 // Short Bow +2
  bow19, 1, null, null, null, null, null, null, null, null, null, null => bow19 // Short Bow of Gesen
  bow20, 1, null, null, null, null, null, null, null, null, null, null => bow20 // Darkfire Bow +4
  bow21, 1, null, null, null, null, null, null, null, null, null, null => bow21 // Darkfire Bow +5
  bow22, null, null, null, null, null, 5, null, null, null, null, null => bow22 // Taralash +4
  bow23, null, null, null, null, null, 6, null, null, null, null, null => bow23 // Taralash +5
  bow24, 1, null, null, null, null, null, null, null, null, null, null => bow24 // Composite Long Bow +3
  bow25, null, null, null, 4, null, null, null, null, null, null, null => bow25 // Long Bow +3
  bow26, 1, null, null, null, null, null, null, null, null, null, null => bow26 // Short Bow +3
  bow99, 1, null, null, null, null, null, null, null, null, null, null => bow99 // Eagle Bow
  bownon, 1, null, null, null, null, null, null, null, null, null, null => bownon // Long Bow
  brac15, null, null, null, null, 2, null, null, null, null, null, null => brac15 // Bracers of Defense AC 3
  brdflute, null, null, null, null, 0, null, null, null, null, null, null => brdflute // Magic Flute
  bruenaxe, null, null, null, null, null, null, null, null, 92, null, null => bruenaxe // Battle Axe +3
  bull01, null, null, null, null, null, null, null, null, 2, null, null => bull01 // Bullet
  bull02, null, null, null, null, null, null, null, null, 2, null, null => bull02 // Bullet +1
  bull03, null, null, null, null, null, null, null, null, 2, null, null => bull03 // Bullet +2
  bull04, null, null, null, null, null, null, null, null, 2, null, null => bull04 // Sunstone Bullet +1
  bull05, null, null, null, null, null, null, null, null, 2, null, null => bull05 // Bullet +3
  bull06, null, null, null, null, null, null, 35, null, null, null, null => bull06 // Bullet +4
  cattac1, 1, null, null, null, null, null, null, null, null, null, null => cattac1 // Two Handed Sword
  cattibow, 1, null, null, null, null, null, null, null, null, null, null => cattibow // Tansheron's Bow +3
  chalcy2, null, null, 0, null, null, null, null, null, null, null, null => chalcy2 // Short Sword of Backstabbing 
  chalslay, 1, null, null, null, null, null, null, null, null, null, null => chalslay // Ring
  chan03, null, null, null, null, null, null, 65, null, null, null, null => chan03 // Mail of the Dead +2
  chan21, null, null, null, null, null, null, 75, null, null, null, null => chan21 // Chain Mail +3
  chwraith, 1, null, null, null, null, null, null, null, null, null, null => chwraith // <Invalid Strref -1>
  clck13, null, null, null, null, 4, null, null, null, null, null, null => clck13 // Traveller's Robe
  clck18, null, 1, null, null, null, null, null, null, null, null, null => clck18 // Knave's Robe
  clown, 1, null, null, null, null, null, null, null, null, null, null => clown // <Invalid Strref -1>
  dagg04, 1, null, null, null, null, null, null, null, null, null, null => dagg04 // Dagger +2, Longtooth
  dagg05, 1, null, null, null, 0, null, null, null, null, null, null => dagg05 // Throwing Dagger
  dagg10, null, null, null, null, null, null, null, 16, null, null, null => dagg10 // Soultaker Dagger
  dagg11, null, null, null, 0, null, null, null, null, null, null, null => dagg11 // Boomerang Dagger +2
  dagg12, null, null, null, 0, null, null, null, null, null, null, null => dagg12 // Fire Tooth +3
  dagg16, 1, null, null, null, null, null, null, null, null, null, null => dagg16 // Poisoned Throwing Dagger
  dagg18, 1, null, null, null, null, null, null, null, null, null, null => dagg18 // Shadow Thief Dagger
  dagg19, null, 1, null, null, null, null, null, null, null, 1, null => dagg19 // Dagger of <CHARNAME>
  daggshit, 1, null, null, null, null, null, null, null, null, null, null => daggshit // Dagger
  dart01, null, null, null, 2, null, null, null, null, null, null, null => dart01 // Dart
  dart03, null, null, 0, null, null, null, null, null, null, null, null => dart03 // Dart of Stunning
  dart04, null, null, 0, null, null, null, null, null, null, null, null => dart04 // Dart of Wounding
  dart05, null, null, 0, null, null, null, null, null, null, 1, null => dart05 // Asp's Nest
  dartmel, null, null, 0, null, null, null, null, null, null, null, null => dartmel // Bone Dagger
  dax1h01, null, 1, null, null, null, null, null, null, null, null, null => dax1h01 // Battle Axe
  demogorg, 1, null, null, null, null, null, null, null, null, null, null => demogorg // <Invalid Strref -1>
  demsuc01, 1, null, null, null, null, null, null, null, null, null, null => demsuc01 // <Invalid Strref -1>
  dragring, null, null, null, null, null, null, null, null, null, null, 1 => dragring // Ring
  dwbolt01, null, null, null, null, null, null, null, null, 2, null, null => dwbolt01 // Drow Bolt of Sleep
  dwbolt02, null, null, null, null, null, null, null, null, 2, null, null => dwbolt02 // Drow Bolt of Stunning
  dwbolt03, null, null, null, null, null, null, null, null, 2, null, null => dwbolt03 // Drow Bolt +1
  dwchan01, null, null, null, null, null, null, 75, null, null, null, null => dwchan01 // Drow Elven Chain +3
  dwchan02, null, null, null, null, 12, null, null, null, null, null, null => dwchan02 // Drow Adamantine Chain +5
  dwhalb01, 1, null, null, null, null, null, null, null, null, null, null => dwhalb01 // Drow Halberd +3
  dwplat01, null, null, null, null, null, null, 75, null, null, null, null => dwplat01 // Drow Full Plate +5
  dwshld01, null, null, null, null, 7, null, null, null, null, null, null => dwshld01 // Drow Shield +3
  dwxbow01, null, null, null, 2, null, null, null, null, null, null, null => dwxbow01 // Drow Crossbow of Speed
  elemchan, null, null, null, null, null, null, null, null, null, null, 1 => elemchan // Skull
  elemyanc, null, null, null, null, null, null, null, null, null, null, 1 => elemyanc // Skull
  enmace, 1, null, null, null, 0, null, null, null, null, null, null => enmace // Mace
  enmorn, 1, null, null, null, 0, null, null, null, null, null, null => enmorn // Morning Star
  enstaff, null, null, null, null, 0, null, null, null, null, null, null => enstaff // Quarter Staff +3
  ensw1h01, null, null, null, null, 0, null, null, null, null, null, null => ensw1h01 // Long Sword 
  ensw1h02, null, null, null, null, 0, null, null, null, null, null, null => ensw1h02 // Short Sword 
  ensw2h, 1, null, null, null, 0, null, null, null, null, null, null => ensw2h // Battle Axe
  famcat, null, 1, null, null, null, null, null, null, null, null, null => famcat // Familiar
  famcat25, null, 1, null, null, null, null, null, null, null, null, null => famcat25 // Familiar
  famdus25, null, 1, null, null, null, null, null, null, null, null, null => famdus25 // Familiar
  famdust, null, 1, null, null, null, null, null, null, null, null, null => famdust // Familiar
  famfai25, null, 1, null, null, null, null, null, null, null, null, null => famfai25 // Familiar
  famfair, null, 1, null, null, null, null, null, null, null, null, null => famfair // Familiar
  famfer, null, 1, null, null, null, null, null, null, null, null, null => famfer // Familiar
  famfer25, null, 1, null, null, null, null, null, null, null, null, null => famfer25 // Familiar
  famimp, null, 1, null, null, null, null, null, null, null, null, null => famimp // Familiar
  famimp25, null, 1, null, null, null, null, null, null, null, null, null => famimp25 // Familiar
  fampsd, null, 1, null, null, null, null, null, null, null, null, null => fampsd // Familiar
  fampsd25, null, 1, null, null, null, null, null, null, null, null, null => fampsd25 // Familiar
  famqua25, null, 1, null, null, null, null, null, null, null, null, null => famqua25 // Familiar
  famquas, null, 1, null, null, null, null, null, null, null, null, null => famquas // Familiar
  famrab, null, 1, null, null, null, null, null, null, null, null, null => famrab // Familiar
  famrab25, null, 1, null, null, null, null, null, null, null, null, null => famrab25 // Familiar
  flam01, null, null, null, null, null, null, null, null, 2, null, null => flam01 // Flamethrower
  frag01, null, null, null, null, null, null, null, null, 2, null, null => frag01 // Frag Grenade
  frosty, 1, null, null, null, null, null, null, null, 2, null, null => frosty // Dr. Freeze Death Ray
  fsspir, 1, null, null, null, null, null, null, null, null, null, null => fsspir // Ring
  ghost, 1, null, null, null, null, null, null, null, null, null, null => ghost // <Invalid Strref -1>
  ghost2, 1, null, null, null, null, null, null, null, null, null, null => ghost2 // <Invalid Strref -1>
  giafir, 1, null, null, null, null, null, null, null, null, null, null => giafir // War Hammer +2
  giafir2, 1, null, null, null, null, null, null, null, null, null, null => giafir2 // Battle Axe +2
  giafir3, 1, null, null, null, null, null, null, null, null, null, null => giafir3 // <Invalid Strref -1>
  giants01, 1, null, null, null, null, null, null, null, null, null, null => giants01 // Two Handed Sword
  globblu1, null, null, 0, null, null, null, null, null, null, null, null => globblu1 // Blue Globe
  globred1, null, null, 0, null, null, null, null, null, null, null, null => globred1 // Red Globe
  gorcamb, null, null, 0, null, null, null, null, null, null, null, null => gorcamb // Two Handed Sword +2
  gorchr, 1, null, null, null, null, null, null, null, null, null, null => gorchr // Ring
  gorfirg, 1, null, null, null, null, null, null, null, null, null, null => gorfirg // Ring
  gorjelfu, 1, null, null, null, null, null, null, null, null, null, null => gorjelfu // Ring
  gorjelgr, 1, null, null, null, null, null, null, null, null, null, null => gorjelgr // Ring
  gormisti, 1, null, null, null, null, null, null, null, null, null, null => gormisti // Ring
  gorwom1, 1, null, null, null, null, null, null, null, null, null, null => gorwom1 // <Invalid Strref -1>
  halb01, 1, null, null, null, null, null, null, null, null, null, null => halb01 // Halberd
  halb03, null, null, null, null, null, null, 60, null, null, null, null => halb03 // Halberd +2
  halb04, null, null, null, 6, null, null, null, null, null, null, null => halb04 // Dragon's Bane +3
  halbrd01, 1, null, null, null, null, null, null, null, null, null, null => halbrd01 // Halberd
  hamm01, 1, null, null, null, null, null, null, null, null, null, null => hamm01 // War Hammer
  hamm03, null, null, 0, null, null, null, null, null, null, null, null => hamm03 // War Hammer +2
  hamm04, null, null, null, 3, null, null, null, null, null, null, null => hamm04 // War Hammer +1,+4 vs. Giantkin
  hamm05, null, null, 0, null, null, null, null, null, null, null, null => hamm05 // War Hammer +2
  hamm09, null, null, null, 0, null, null, null, null, null, null, null => hamm09 // Crom Faeyr
  helmskwa, null, 1, null, null, null, null, null, null, null, null, null => helmskwa // Helmet
  hgber01, 1, null, null, null, null, null, null, null, null, null, null => hgber01 // Two Handed Sword +1
  hgnya01, null, null, 0, null, null, null, null, null, null, null, null => hgnya01 // Quarterstaff
  hgnymph, 1, null, null, null, null, null, null, null, null, null, null => hgnymph // <Invalid Strref -1>
  hgwra01, 1, null, null, null, null, null, null, null, null, null, null => hgwra01 // Quarterstaff
  hlolth, null, null, null, null, 7, null, null, null, null, null, null => hlolth // Handmaiden's Mace
  holdring, 1, null, null, null, null, null, null, null, null, null, null => holdring // Ring
  hslaywpn, 1, null, null, null, null, null, null, null, null, null, null => hslaywpn // <Invalid Strref -1>
  hspectre, 1, null, null, null, null, null, null, null, null, null, null => hspectre // Spectral Harpist hand weapon
  iarow01, null, null, null, null, null, null, null, null, 2, null, null => iarow01 // Arrows
  iax1h01, 1, null, null, null, null, null, null, null, null, null, null => iax1h01 // Battle Axe
  iblun04, 1, null, null, null, 10, null, null, null, null, null, null => iblun04 // Mace
  ibow03, 1, null, null, null, null, null, null, null, null, null, null => ibow03 // Long Bow
  icetrl, null, null, 0, null, null, null, null, null, null, null, null => icetrl // Attack
  ihamm01, 1, null, null, null, null, null, null, null, null, null, null => ihamm01 // War Hammer
  impinvis, null, null, null, null, null, null, null, null, null, null, 1 => impinvis // Ring of Invisibility 
  innoc2, 1, null, null, null, null, null, null, null, null, null, null => innoc2 // <Invalid Strref -1>
  invulner, 1, null, null, null, null, null, null, null, null, null, null => invulner // Ring
  irongol, 1, null, null, null, null, null, null, null, null, null, null => irongol // <Invalid Strref -1>
  jonhp1, null, null, null, null, null, null, null, null, null, null, 1 => jonhp1 // <Invalid Strref -1>
  killsw01, null, null, 0, null, null, null, null, null, null, null, null => killsw01 // Long Sword +2
  kuobolt, null, null, null, null, 0, null, null, null, 2, null, null => kuobolt // Kuo-Toa Bolts
  kuobolt2, null, null, null, null, null, null, null, null, 2, 2, null => kuobolt2 // Kuo-Toa Bolts
  kuobolt3, null, null, 0, null, null, null, null, null, 2, null, null => kuobolt3 // Kuo-Toa Bolts
  kuobow, 1, 1, null, null, null, null, null, null, null, null, null => kuobow // Heavy Crossbow
  kuoring, null, null, null, null, null, null, null, null, null, null, 1 => kuoring // <Invalid Strref -1>
  kuosper, null, 1, null, null, null, null, null, null, null, null, null => kuosper // Spear
  laser, null, null, null, null, null, null, null, null, 2, null, null => laser // Laser
  leat03, null, null, null, null, null, null, 60, null, null, null, null => leat03 // Protector of the Second +2
  leat06, null, null, null, null, null, null, 100, null, null, null, null => leat06 // Missile Attraction +2 
  lich, 1, null, null, null, null, null, null, null, null, null, 1 => lich // Ring
  light, null, null, null, null, null, null, null, null, 2, null, null => light // Wand of Magic Missiles
  lionspir, null, 1, null, null, null, null, null, null, null, 3, null => lionspir // Attack
  mage05, null, null, null, null, null, null, null, null, null, null, 1 => mage05 // Ring of Free Action
  mage06, null, null, null, null, null, null, null, null, null, null, 1 => mage06 // Ring
  mdog1, 1, null, null, null, null, null, null, null, null, null, null => mdog1 // <Invalid Strref -1>
  melfmet, null, null, null, null, 0, null, null, null, null, null, null => melfmet // Melf's Minute Meteor
  misc3a, null, null, null, null, null, null, 80, null, null, null, null => misc3a // Book of Infinite Spells
  misc3e, null, null, null, null, null, null, 75, null, null, null, null => misc3e // Black Spider Figurine
  misc3f, null, null, null, null, null, null, 75, null, null, null, null => misc3f // Jade Hound
  misc3j, null, null, null, null, null, null, 0, null, null, null, null => misc3j // Bronze Horn of Valhalla
  misc3k, null, null, null, null, null, null, 0, null, null, null, null => misc3k // Iron Horn of Valhalla
  misc4g, null, 1, null, null, null, null, null, null, null, null, null => misc4g // Portal Key
  misc4q, null, null, null, null, null, null, null, null, 89, null, null => misc4q // The Ogre's Sword
  misc4u, null, null, null, 2, null, null, null, null, 96, null, null => misc4u // Embarl's Dagger
  misc5c, null, null, 0, null, null, null, null, null, null, null, null => misc5c // Rift Device
  misc5t, null, null, null, 4, null, null, null, null, 102, null, null => misc5t // Shaman's Staff
  misc73, null, 1, null, null, null, null, null, 0, null, null, null => misc73 // The Horn of Kazgaroth
  misc75, null, null, null, null, null, null, null, null, 96, 2, null => misc75 // Dagger of Venom
  misc84, null, 1, null, null, null, null, null, null, null, null, null => misc84 // Boo
  misc9q, null, null, null, 5, null, null, null, null, null, null, null => misc9q // Scimitar
  miscan, null, null, null, null, null, null, null, 1, null, null, null => miscan // Galvena's Medallion
  miscb1, null, null, null, null, null, null, null, 1, null, null, null => miscb1 // Talisman of Rillifane
  mistcd, null, null, 0, null, null, null, null, null, null, null, null => mistcd // <Invalid Strref -1>
  mistho, null, null, 0, null, null, null, null, null, null, null, null => mistho // Skull
  mistice, null, null, 0, null, null, null, null, null, null, null, null => mistice // Skull
  mistva, null, null, 0, null, null, null, null, null, null, null, null => mistva // Skull
  mistva2, null, null, 0, null, null, null, null, null, null, null, null => mistva2 // Skull
  mistwa, null, null, 0, null, null, null, null, null, null, null, null => mistwa // Skull
  mound, null, null, 0, null, null, null, null, null, null, null, null => mound // <Invalid Strref -1>
  nebdag, null, null, 0, null, null, null, null, null, null, null, null => nebdag // Neb's Nasty Cutter
  npbow, 1, null, null, 4, null, null, null, null, null, null, null => npbow // Bow of Arvoreen
  npstaf, null, null, null, null, 3, null, null, null, null, null, null => npstaf // Staff of the High Forest
  npsw03, null, null, null, null, null, null, null, null, null, null, 1 => npsw03 // Hallowed Redeemer
  npsw05, null, null, null, 1, null, null, null, null, null, null, null => npsw05 // Entropy
  npsw06, null, null, null, 1, null, null, null, null, null, null, null => npsw06 // Chaos Blade
  objring, 1, null, null, null, null, null, null, null, null, null, null => objring // Ring
  p3-12m4, null, null, null, null, null, null, null, null, null, 4, null => p3-12m4 // <Invalid Strref -1>
  plat02, null, null, null, null, null, null, 40, null, null, null, null => plat02 // Plate Mail +1
  plat09, null, null, null, null, null, null, 50, null, null, null, null => plat09 // Mithral Field Plate Armor +2
  plat19, null, null, null, null, 40, null, null, null, null, null, null => plat19 // Full Plate + 2
  plat23, null, null, null, null, null, null, 75, null, null, null, null => plat23 // Full Plate Mail +2
  plat98, null, 1, null, null, null, null, null, null, null, null, null => plat98 // Plate Mail Armor
  plybass, null, 1, null, null, null, null, null, null, null, null, null => plybass // Attack
  plyfist, null, 1, null, null, null, null, null, null, null, null, null => plyfist // Attack
  plymstar, 1, 1, null, null, null, null, null, null, null, null, null => plymstar // Morning Star
  plysala, null, 1, null, null, 0, null, null, null, null, null, null => plysala // Spear
  plyspid, null, 1, null, null, null, null, null, null, null, null, null => plyspid // Attack
  plywyvrn, null, 1, null, null, null, null, null, null, null, null, null => plywyvrn // Attack
  potn26, null, null, 0, null, null, null, null, null, null, null, null => potn26 // Potion of Explosions
  potn27, null, null, 0, null, null, null, null, null, null, null, null => potn27 // Potion of Firebreath
  potn40, null, null, null, null, null, null, 0, null, null, null, null => potn40 // Potion of Invulnerability
  puls01, null, null, null, null, null, null, null, null, 2, null, null => puls01 // Wand of Magic Missiles
  puls02, null, null, null, null, null, null, null, null, 2, null, null => puls02 // Wand of Magic Missiles
  quasclaw, null, null, 0, null, null, null, null, null, null, null, null => quasclaw // Attack
  quiv01, null, null, null, null, null, null, null, null, 2, null, null => quiv01 // Arrows
  quiver01, null, null, null, null, null, null, null, null, 2, null, null => quiver01 // Quiver of Plenty +1
  quiver02, null, null, null, null, null, null, 20, null, null, null, null => quiver02 // Case of Plenty +1
  quiver03, null, null, null, null, null, null, null, null, 2, null, null => quiver03 // Quiver of Plenty +2
  quiver04, null, null, null, null, null, null, null, null, 2, null, null => quiver04 // Case of Plenty +2
  quiver05, null, null, null, null, null, null, null, null, 2, null, null => quiver05 // Bag of Plenty +1
  quiver06, null, null, null, null, null, null, null, null, 2, null, null => quiver06 // Bag of Plenty +2
  ravag01, null, null, 0, null, null, null, null, null, null, null, null => ravag01 // Skull
  ravag02, null, null, 0, null, null, null, null, null, null, null, null => ravag02 // Boneblade +4
  reaver, 1, null, null, null, null, null, null, null, null, null, null => reaver // Unholy Reaver
  regisamu, null, 1, null, null, null, null, 65, null, null, null, null => regisamu // Ruby Pendant
  revent1, null, null, 0, null, null, null, null, null, null, null, null => revent1 // <Invalid Strref -1>
  ring20, null, null, 0, null, null, null, null, null, null, null, null => ring20 // Ring of Energy
  ring43, null, null, null, null, null, null, 0, null, null, null, null => ring43 // Oaken Ring
  ring94, 1, null, null, null, null, null, null, null, null, null, null => ring94 // Ring
  ring95, 1, null, null, null, null, null, null, null, null, null, null => ring95 // Ring
  ring99, 1, null, null, null, null, null, null, null, null, null, null => ring99 // Ring
  ringwolf, 1, null, null, null, null, null, null, null, null, null, null => ringwolf // <Invalid Strref -1>
  rods02, null, null, null, null, null, null, 70, null, null, null, null => rods02 // Rod of Lordly Might
  rods03, null, null, 0, null, null, null, null, null, null, null, null => rods03 // Rod of Resurrection
  rods06, null, null, null, null, null, null, 85, null, null, null, null => rods06 // Rod of Reversal
  sahbolt, null, null, null, null, 0, null, null, null, 2, null, null => sahbolt // Paralytic Bolt
  scrl03, null, null, 0, null, null, null, null, null, null, null, null => scrl03 // Protection from Acid
  scrl04, null, null, 0, null, null, null, null, null, null, null, null => scrl04 // Protection from Cold
  scrl05, null, null, 0, null, null, null, null, null, null, null, null => scrl05 // Protection from Electricity
  scrl06, null, null, 0, null, null, null, null, null, null, null, null => scrl06 // Protection from Fire
  scrl08, null, null, 0, null, null, null, null, null, null, null, null => scrl08 // Protection from Poison
  scrl09, null, null, 0, null, null, null, null, null, null, null, null => scrl09 // Protection from Undead
  scrl15, null, null, 0, null, null, null, null, null, null, null, null => scrl15 // Protection from Petrification
  scrla9, null, null, null, null, null, null, null, 37, null, null, null => scrla9 // Scroll
  scrlaa, null, null, null, null, null, null, null, 37, null, null, null => scrlaa // Scroll
  scrlab, null, null, null, null, null, null, null, 37, null, null, null => scrlab // Dradeel's Recipe Page
  scrlac, null, null, null, null, null, null, null, 37, null, null, null => scrlac // Dradeel's Recipe Page
  scrlad, null, null, null, null, null, null, null, 37, null, null, null => scrlad // Dradeel's Recipe Page
  scrlaf, null, null, null, null, null, null, null, 37, null, null, null => scrlaf // Dradeel's Recipe Page
  scrlag, null, 1, null, null, null, null, null, 37, null, null, null => scrlag // Crom Faeyr Scroll
  scrlhp, null, null, null, null, null, null, null, 37, null, null, null => scrlhp // Note
  scrlick, null, null, null, null, null, null, null, 37, null, null, null => scrlick // Illithid Correspondence
  scrlmz, null, null, null, null, null, null, null, 37, null, null, null => scrlmz // A note from Mazzy Fentan
  secret02, null, null, 0, null, null, null, null, null, 2, null, null => secret02 // Pulse Ammunition
  secret03, null, null, null, null, null, null, null, null, 2, null, null => secret03 // Frag Grenade
  secret04, null, null, null, null, null, null, null, null, 2, null, null => secret04 // Scorcher Ammunition
  seltest, 1, null, null, null, null, null, null, null, null, null, null => seltest // <Invalid Strref -1>
  sendai, null, null, 0, null, null, null, null, null, null, null, null => sendai // Drow Flail +3
  shalt01, 1, null, null, null, null, null, null, null, null, null, null => shalt01 // Ring
  shille, null, null, 0, null, 0, null, null, null, null, null, null => shille // Shillelagh
  shld17, null, null, null, null, null, null, 10, null, null, null, null => shld17 // Buckler +1
  shld23, null, null, null, null, 10, null, null, null, null, null, null => shld23 // Fortress Shield +3
  shld27, null, null, null, null, 4, null, null, null, null, null, null => shld27 // Saving Grace +3
  skelclub, 1, null, null, null, null, null, null, null, null, null, null => skelclub // Club
  skelwasu, 1, null, null, null, null, null, null, null, null, null, null => skelwasu // Two Handed Sword +1
  slayerwp, 1, null, null, null, null, null, null, null, null, null, 1 => slayerwp // <Invalid Strref -1>
  slaysh01, 1, null, null, null, null, null, null, null, null, null, null => slaysh01 // <Invalid Strref -1>
  slng03, null, null, null, null, null, null, 45, null, null, null, null => slng03 // Sling +3
  slng08, null, null, null, 2, null, null, null, null, null, null, null => slng08 // Erinne Sling +4
  slng09, null, null, null, 1, null, null, null, null, null, null, null => slng09 // Erinne Sling +5
  snakspir, null, 1, null, null, null, null, null, null, null, 3, null => snakspir // Attack
  sorb, null, null, null, null, 0, null, null, null, null, null, null => sorb // Searing Orb
  spectr, 1, null, null, null, null, null, null, null, null, null, null => spectr // <Invalid Strref -1>
  sper03, null, null, null, 6, null, null, null, null, null, null, null => sper03 // Spear +3, Backbiter
  sper06, null, null, null, null, 3, null, null, null, null, null, null => sper06 // Spear +3
  sper10, null, null, null, 2, null, null, null, null, null, null, null => sper10 // Spear of Withering +4
  sper11, null, null, null, 2, null, null, null, null, null, null, null => sper11 // Ixil's Nail +4
  sper12, null, null, null, 1, null, null, null, null, null, null, null => sper12 // Ixil's Spike +6
  spermel, null, null, 0, null, null, null, null, null, null, null, null => spermel // Spear
  staf04, null, null, null, 4, 4, null, null, null, null, null, null => staf04 // Quarterstaff
  staf05, null, null, null, 1, null, null, null, null, null, null, null => staf05 // Staff of Striking
  staf06, null, null, null, null, null, null, 25, null, null, null, null => staf06 // Staff Mace
  staf07, null, null, null, null, null, null, 65, null, null, null, null => staf07 // Staff Spear +2
  staf08, null, null, null, null, 4, null, null, null, null, null, null => staf08 // Martial Staff +3
  staf09, null, null, null, 2, null, null, null, null, null, null, null => staf09 // Staff of Command
  staf10, null, null, null, 3, 4, null, null, null, null, 1, null => staf10 // Staff of Curing
  staf11, null, null, null, 1, 4, null, null, null, null, null, null => staf11 // Staff of the Magi
  staf12, null, null, null, 2, null, null, null, null, null, null, null => staf12 // Staff of Power
  staf13, null, null, null, 2, 4, null, null, null, null, null, null => staf13 // Staff of Thunder and Lightning
  staf14, null, null, 0, null, null, null, null, null, null, null, null => staf14 // Staff of the Woodlands +4
  staf15, null, null, null, 2, null, null, null, null, null, null, null => staf15 // Staff of Air +2
  staf16, null, null, null, 2, null, null, null, null, null, null, null => staf16 // Staff of Earth +2
  staf17, null, null, null, 2, null, null, null, null, null, null, null => staf17 // Staff of Fire +2
  staf18, null, null, null, 2, null, null, null, null, null, null, null => staf18 // Quarter Staff +2
  staf20, null, null, null, null, 3, null, null, null, null, null, null => staf20 // Staff of Rynn +4
  staf23, null, null, null, 2, null, null, null, null, null, null, null => staf23 // Serpent Shaft
  stalker, 1, null, null, null, null, null, null, null, null, null, null => stalker // Ring
  stardart, null, null, null, 0, null, null, null, null, null, null, null => stardart // Dart +5
  stonring, 1, null, null, null, null, null, null, null, null, null, null => stonring // Ring
  stonskin, 1, null, null, null, null, null, null, null, null, null, null => stonskin // <Invalid Strref -1>
  surehp1, 1, null, null, null, null, null, null, null, null, null, null => surehp1 // Ring
  sw1h03, null, null, null, null, null, null, null, null, null, 3, null => sw1h03 // Bastard Sword +1,+3 vs. Shapeshifters 
  sw1h06, null, null, 0, null, null, null, null, null, null, null, null => sw1h06 // Long Sword +2
  sw1h08, 1, null, null, null, null, null, null, null, null, null, null => sw1h08 // Short Sword +1
  sw1h14, 1, null, null, null, null, null, null, null, null, null, null => sw1h14 // Short Sword +1
  sw1h15, null, null, null, null, 4, null, null, null, null, null, null => sw1h15 // Scimitar +3, Frostbrand
  sw1h16, null, null, null, null, 4, null, null, null, null, null, null => sw1h16 // Scimitar +5, Defender
  sw1h23, null, null, null, null, 4, null, null, null, null, null, null => sw1h23 // Scimitar +2, Rashad's Talon
  sw1h24, null, null, null, 4, null, null, 70, null, null, null, null => sw1h24 // Flame Tongue
  sw1h26, null, null, null, 2, null, null, null, null, null, null, null => sw1h26 // Ilbratha +1
  sw1h28, null, null, null, 0, null, null, null, null, null, null, null => sw1h28 // Cutthroat +4
  sw1h31, null, null, null, null, null, null, null, null, null, 4, null => sw1h31 // Daystar
  sw1h32, null, null, null, null, 3, null, null, null, null, null, null => sw1h32 // Dragonslayer
  sw1h47, null, 1, null, null, null, null, null, null, null, null, null => sw1h47 // Wakizashi +1
  sw1h52, null, null, null, 2, null, null, null, null, null, null, null => sw1h52 // Scimitar +3
  sw1h53, null, null, null, 4, null, null, null, null, null, null, null => sw1h53 // Sword of Flame +1
  sw1h54, null, null, null, 2, null, null, null, null, null, null, null => sw1h54 // The Equalizer
  sw1h54c, null, null, null, null, null, null, null, 34, null, null, null => sw1h54c // Pommel Jewel of the Equalizer
  sw1h57, 1, null, null, null, null, null, null, null, null, null, null => sw1h57 // Throwing Dagger
  sw1h58, null, null, 0, null, null, null, null, null, null, null, null => sw1h58 // Short Sword of Mask +4
  sw1h59, null, null, 0, null, null, null, null, null, null, null, null => sw1h59 // Short Sword of Mask +5
  sw1h60, null, null, null, 1, null, null, null, null, null, null, null => sw1h60 // Angurvadal +4
  sw1h69, null, null, null, 0, null, null, null, null, null, null, null => sw1h69 // Spectral Brand +5
  sw1h73, null, null, null, 2, null, null, null, null, null, null, null => sw1h73 // Long Sword +3
  sw1h99, 1, null, null, null, null, null, null, null, null, null, null => sw1h99 // Sword of Chaos
  sw1hseek, null, null, null, null, null, null, null, null, null, null, 1 => sw1hseek // Seeking Sword
  sw2h01, 1, null, null, null, null, null, null, null, null, null, null => sw2h01 // Two Handed Sword
  sw2h01b, 1, null, null, null, null, null, null, null, null, null, null => sw2h01b // Two Handed Sword
  sw2h02, 1, null, null, null, null, null, null, null, null, null, null => sw2h02 // Two Handed Sword +1
  sw2h03, null, null, null, 10, null, null, null, null, null, null, null => sw2h03 // Cursed Berserking Sword +3
  sw2h05, 1, null, null, null, null, null, null, null, null, null, null => sw2h05 // Two Handed Sword
  sw2h12, null, null, null, null, 10, null, null, null, null, null, null => sw2h12 // Flame Of The North
  sw2h14, 1, null, null, 7, null, null, null, null, null, null, null => sw2h14 // Lilarcor
  sw2h15, null, null, null, 7, 15, null, null, null, null, null, null => sw2h15 // Silver Sword
  telslav, 1, null, 1, null, null, null, null, null, null, null, null => telslav // <Invalid Strref -1>
  telslav2, 1, null, null, null, null, null, null, null, null, null, null => telslav2 // <Invalid Strref -1>
  trolltor, null, null, 0, null, null, null, null, null, null, null, null => trolltor // Attack
  ttsword2, 1, null, null, null, null, null, null, null, null, null, null => ttsword2 // Two Handed Sword
  vamp, 1, null, null, null, null, null, null, null, null, null, null => vamp // <Invalid Strref -1>
  vamp1, 1, null, null, null, null, null, null, null, null, null, null => vamp1 // <Invalid Strref -1>
  vamp2, 1, null, null, null, null, null, null, null, null, null, null => vamp2 // <Invalid Strref -1>
  vamp3, 1, null, null, null, null, null, null, null, null, null, null => vamp3 // <Invalid Strref -1>
  wa2halb, null, null, null, 6, null, null, null, null, null, null, null => wa2halb // Harmonium Halberd
  wa2shiel, null, null, null, null, 4, null, null, null, null, null, null => wa2shiel // Shield of Balduran
  waflail, null, null, null, 4, null, null, null, null, null, null, null => waflail // Defender of Easthaven +2
  wamace, null, null, null, null, null, null, null, null, null, 5, null => wamace // Jerrod's Mace
  wand11, null, null, null, null, null, null, 50, null, null, null, null => wand11 // Wand of the Heavens
  wand12, null, null, 0, null, null, null, null, null, null, null, null => wand12 // Wand of Wonder
  wasling, null, null, null, 1, null, null, null, null, null, null, null => wasling // Sling of Everard +5
  wastaff, null, null, null, 1, null, null, null, null, null, null, null => wastaff // Staff of Arundel
  wight, 1, null, null, null, null, null, null, null, null, null, null => wight // <Invalid Strref -1>
  wolfspir, null, 1, null, null, null, null, null, null, null, 3, null => wolfspir // Attack
  wolfwi1, null, null, 0, null, null, null, null, null, null, null, null => wolfwi1 // <Invalid Strref -1>
  wolfwi2, null, null, 0, null, null, null, null, null, null, null, null => wolfwi2 // <Invalid Strref -1>
  wraith1, 1, null, null, null, null, null, null, null, null, null, null => wraith1 // <Invalid Strref -1>
  xbow01, 1, null, null, null, null, null, null, null, null, null, null => xbow01 // Heavy Crossbow
  xbow02, 1, null, null, null, null, null, null, null, null, null, null => xbow02 // Heavy Crossbow +1
  xbow03, 1, null, null, 5, null, null, null, null, null, null, null => xbow03 // Heavy Crossbow of Accuracy 
  xbow06, null, null, null, 4, null, null, null, null, null, null, null => xbow06 // Light Crossbow of Speed 
  xbow07, 1, null, null, null, null, null, null, null, null, null, null => xbow07 // Heavy Crossbow +2
  xbow08, 1, null, null, null, null, null, null, null, null, null, null => xbow08 // Giant Hair Crossbow +3
  xbow13, null, null, null, 1, null, null, null, null, null, null, null => xbow13 // Crossbow of Affliction +4
  xbow15, null, null, 0, null, null, null, null, null, null, null, null => xbow15 // Firetooth +4
  xbow16, null, null, 0, null, null, null, null, null, null, null, null => xbow16 // Firetooth +5
  xbow17, 1, null, null, null, null, null, null, null, null, null, null => xbow17 // Heavy Crossbow +3

END

OUTER_SPRINT itm_speed_text @30
OUTER_SPRINT itm_weight_text @31
OUTER_SPRINT itm_thac0_text @32

ACTION_PHP_EACH cd_bulk_changes_itm AS params => file BEGIN

  //file, timing, magical, power, speed, weight, thac0, lore, type, prof, enchantment, dispellable => file // notes
  //file, timing, magical, power, speed, weight, thac0, lore, type, enchantment, dispellable => file // notes
  COPY_EXISTING ~%file%.itm~ ~override~
    PATCH_IF (IS_AN_INT params_1) BEGIN // has equipped effects with bad timing
      LPF ALTER_EFFECT INT_VAR silent = 1 check_headers = 0 timing = 2 duration = 0 END // instant/while equipped for all global effects
    END 
    PATCH_IF (IS_AN_INT params_2) BEGIN // add/remove magical flag
      PATCH_IF (params_2 = 0)   BEGIN WRITE_BYTE 0x18 THIS & `BIT6 END // remove magical flag
      PATCH_IF (params_2 = 1)   BEGIN WRITE_BYTE 0x18 THIS | BIT6  END // add magical flag
    END  
    PATCH_IF (IS_AN_INT params_3) BEGIN // has equipping effects with wrong power
      LPF ALTER_EFFECT INT_VAR silent = 1 check_globals = 0 power = params_3 END
    END 
    PATCH_IF (IS_AN_INT params_4) BEGIN // wrong weapon speed
      LPF ALTER_HEADER INT_VAR silent = 1 match_location = 1 speed = params_4 END // anything that turns up in weapon slots (e.g. not magical abilities)
    END 
    PATCH_IF (IS_AN_INT params_5) BEGIN // wrong weight
      WRITE_LONG 0x4c params_5
    END 
    PATCH_IF (IS_AN_INT params_6) BEGIN // wrong to-hit
      LPF ALTER_HEADER INT_VAR silent = 1 match_location = 1 to_hit = params_6 END 
    END 
    PATCH_IF ((IS_AN_INT params_4) OR (IS_AN_INT params_5) OR (IS_AN_INT params_6)) BEGIN // update description for speed/weight/thac0 changes
      LPM cd_bulk_fix_item_strings_bulk
    END  
    PATCH_IF (IS_AN_INT params_7)  BEGIN WRITE_SHORT 0x42 params_7  END // lore
    PATCH_IF (IS_AN_INT params_8)  BEGIN WRITE_SHORT 0x1c params_8  END // type
    PATCH_IF (IS_AN_INT params_9)  BEGIN WRITE_BYTE  0x31 params_9  END // prof    
    PATCH_IF (IS_AN_INT params_10) BEGIN WRITE_LONG  0x60 params_10 END // enchantment
    PATCH_IF (IS_AN_INT params_11) BEGIN // has equipped effects which should bypass MR
      LPF ALTER_EFFECT INT_VAR silent = 1 check_headers = 0 match_resist_dispel = 1 resist_dispel = 2 END
      LPF ALTER_EFFECT INT_VAR silent = 1 check_headers = 0 match_resist_dispel = 3 resist_dispel = 2 END
    END 
    BUT_ONLY IF_EXISTS

END
  
// dispel magic via items can not be blocked; route through spell to allow for op 206 to block if needed - see also cditmdm0.spl, cditmdm1.spl, cd_item_dispel_magic item array
ACTION_CLEAR_ARRAY cd_item_dispel_magic
ACTION_DEFINE_ASSOCIATIVE_ARRAY cd_item_dispel_magic BEGIN

  arow07   => 99 // always dispel
  carsomyr => 99 // always dispel (melee), cast always dispel (magical)
  deva     =>  0 // caster level, power 15
  devaevil =>  0 // caster level, power 15
  elemchan =>  0 // caster level, power 15
  elemcryo =>  0 // caster level, power 15
  elemhydr =>  0 // caster level, power 15
  elemimix =>  0 // caster level, power 15
  elemogre =>  0 // caster level, power 15
  elemsunn =>  0 // caster level, power 15
  elemyanc =>  0 // caster level, power 15
  elemzaam =>  0 // caster level, power 15
  finsol01 => 22 // specific level 22
  misc5c   => 99 // always (magical header)
  planetar =>  0 // caster level, power 15
  plot04i  => 99 // always
  potn33   => 99 // always
  ravag01  => 25 // specific level 25
  reaver   => 99 // always
  scrl07   => 99 // always (cast)
  staf11   => 30 // specific level 30
  sw2h10   => 30 // specific level 30
  sw2h19   => 30 // specific level 30

END

ACTION_PHP_EACH cd_item_dispel_magic AS item => level BEGIN

  COPY_EXISTING ~%item%.itm~ ~override~
    PATCH_IF level = 99 BEGIN SET slevel = 0 SET level = 0 END ELSE BEGIN SET slevel = 1 END // cditmdm0 always dispels, cditmdm1 uses level (up to 50)
    LPF ALTER_EFFECT INT_VAR match_opcode = 58 opcode = 146 parameter1 = level parameter2 = 1 STR_VAR resource = EVAL ~cditmdm%slevel%~ END // change dispel to cast spell
    // delete associated dispel magic effects
    LPF DELETE_EFFECT INT_VAR match_opcode =  77 END // cure feeblemind
    LPF DELETE_EFFECT INT_VAR match_opcode =  81 END // cure deafness
    LPF DELETE_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 14056 END // 'dispel effects' string
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 7 match_parameter2 = 7 STR_VAR match_resource = destself END // destroy illusionary creatures
    LPF DELETE_EFFECT INT_VAR match_opcode = 215 STR_VAR match_resource = spdispma END // DM visuals
    LPF DELETE_EFFECT INT_VAR match_opcode = 240 match_parameter2 =  48 END // remove icon: feeblemind
    LPF DELETE_EFFECT INT_VAR match_opcode = 240 match_parameter2 = 112 END // remove icon: deaf
    IF_EXISTS

END

// targeted charm spells w/ portrait icons; see also series of cdc[abcde]XXX.eff files created
COPY_EXISTING ~regisamu.itm~ ~override~ // 60s dire charm icon
              ~ring03.itm~   ~override~ // 120s eff_m22a expiry sound
              ~staf14.itm~   ~override~ // spnwchrm, 300s charm icon
              ~spcl311.spl~  ~override~ // 120s charm icon, spnwchrm
              ~spcl641.spl~  ~override~ // spnwchrm, 7200s eff_m22a expiry sound
              ~spin108.spl~  ~override~ // 120s charm icon
              ~spin119.spl~  ~override~ // 100s charm icon
              ~spin980.spl~  ~override~ // 100s charm icon, 100s eff_e07 expiry sound, spnwchrm
              ~sppr204.spl~  ~override~ // spnwchrm, 60s charm icon, 60s eff_m22a expiry shound - also fixes wrong save on sound (174)
              ~sppr982.spl~  ~override~ // 48s dire charm icon
              ~spwi104.spl~  ~override~ // 30s charm icon, spnwchrm, 30s eff_e07 expiry sound
              ~spwi316.spl~  ~override~ // 30s dire charm icon, spnwchrm, 30s eff_e07 expiry sound - also fixes one charm effect save wrong
              ~spwi943.spl~  ~override~ // 120s dire charm icon
  READ_ASCII 0x00 sig (3)
  SET abil_length = 0x28
  PATCH_IF ("%sig%" STRING_COMPARE_CASE "ITM" = 0) BEGIN
    SET abil_length += 0x10
  END
  SET fx_delta = 0
  READ_LONG  0x64 abil_off
  READ_SHORT 0x68 abil_num
  READ_LONG  0x6a fx_off
  FOR (index = 0 ; index < abil_num ; ++index) BEGIN
    READ_SHORT  (abil_off + 0x1e + (abil_length * index)) abil_fx_num
    WRITE_SHORT (abil_off + 0x20 + (abil_length * index)) (THIS + fx_delta)
    READ_SHORT  (abil_off + 0x20 + (abil_length * index)) abil_fx_idx
    SET charm = 0
    SET icon0 = 0
    SET icon1 = 0
    SET sound0 = 0
    SET sound1 = 0
    SET sparklies = 0
    FOR (index2 = 0 ; index2 < abil_fx_num ; ++index2) BEGIN
      READ_SHORT (fx_off +        (0x30 * (abil_fx_idx + index2))) opcode
      READ_LONG  (fx_off + 0x08 + (0x30 * (abil_fx_idx + index2))) param2
      READ_ASCII (fx_off + 0x14 + (0x30 * (abil_fx_idx + index2))) resource
      PATCH_IF (opcode = 5) BEGIN
        SET charm = 1 // sanity check
        READ_LONG (fx_off + 0x0e + (0x30 * (abil_fx_idx + index2))) duration
      END ELSE
      PATCH_IF ((opcode = 142) AND (param2 = 0)) BEGIN
        SET icon0 = 1
        DELETE_BYTES (fx_off +        (0x30 * (abil_fx_idx + index2))) 0x30
        SET index2 -= 1
        SET fx_delta -= 1
        SET abil_fx_num -= 1
      END ELSE
      PATCH_IF ((opcode = 142) AND (param2 = 1)) BEGIN
        SET icon1 = 1
        DELETE_BYTES (fx_off +        (0x30 * (abil_fx_idx + index2))) 0x30
        SET index2 -= 1
        SET fx_delta -= 1
        SET abil_fx_num -= 1
      END ELSE
      PATCH_IF ((opcode = 174) AND ("%resource%" STRING_COMPARE_CASE ~eff_m22a~ = 0)) BEGIN
        SET sound0 = 1
        DELETE_BYTES (fx_off +        (0x30 * (abil_fx_idx + index2))) 0x30
        SET index2 -= 1
        SET fx_delta -= 1
        SET abil_fx_num -= 1
      END ELSE
      PATCH_IF ((opcode = 174) AND ("%resource%" STRING_COMPARE_CASE ~eff_e07~ = 0)) BEGIN
        SET sound1 = 1
        DELETE_BYTES (fx_off +        (0x30 * (abil_fx_idx + index2))) 0x30
        SET index2 -= 1
        SET fx_delta -= 1
        SET abil_fx_num -= 1
      END ELSE
      PATCH_IF ((opcode = 215) AND ("%resource%" STRING_COMPARE_CASE ~spnwchrm~ = 0)) BEGIN
        SET sparklies = 1
        DELETE_BYTES (fx_off +        (0x30 * (abil_fx_idx + index2))) 0x30
        SET index2 -= 1
        SET fx_delta -= 1
        SET abil_fx_num -= 1
      END
    END
    PATCH_IF ((charm = 1) AND (icon0 +icon1 + sound0 + sound1 + sparklies != 0)) BEGIN // don't bother if no charm found, or if no ancillaries found
      FOR (index2 = 0 ; index2 < abil_fx_num ; ++index2) BEGIN
        READ_SHORT (fx_off +        (0x30 * (abil_fx_idx + index2))) opcode
        PATCH_IF (opcode = 5) BEGIN
          READ_ASCII   (fx_off +        (0x30 * (abil_fx_idx + index2))) clone (48)
          PATCH_IF (icon0 = 1) BEGIN
            INSERT_BYTES (fx_off +        (0x30 * (abil_fx_idx + index2))) 0x30
              WRITE_ASCIIE (fx_off +        (0x30 * (abil_fx_idx + index2))) ~%clone%~ #48
              WRITE_SHORT  (fx_off +        (0x30 * (abil_fx_idx + index2))) 177
              WRITE_LONG   (fx_off + 0x08 + (0x30 * (abil_fx_idx + index2))) 3 // from general.ids
              WRITE_ASCIIE (fx_off + 0x14 + (0x30 * (abil_fx_idx + index2))) ~cdca%duration%~ #8
            SET index2 += 1
            SET fx_delta += 1
            SET abil_fx_num += 1
          END
          PATCH_IF (icon1 = 1) BEGIN
            INSERT_BYTES (fx_off +        (0x30 * (abil_fx_idx + index2))) 0x30
              WRITE_ASCIIE (fx_off +        (0x30 * (abil_fx_idx + index2))) ~%clone%~ #48
              WRITE_SHORT  (fx_off +        (0x30 * (abil_fx_idx + index2))) 177
              WRITE_LONG   (fx_off + 0x08 + (0x30 * (abil_fx_idx + index2))) 3 // from general.ids
              WRITE_ASCIIE (fx_off + 0x14 + (0x30 * (abil_fx_idx + index2))) ~cdcb%duration%~ #8
            SET index2 += 1
            SET fx_delta += 1
            SET abil_fx_num += 1
          END
          PATCH_IF (sound0 = 1) BEGIN
            INSERT_BYTES (fx_off +        (0x30 * (abil_fx_idx + index2))) 0x30
              WRITE_ASCIIE (fx_off +        (0x30 * (abil_fx_idx + index2))) ~%clone%~ #48
              WRITE_SHORT  (fx_off +        (0x30 * (abil_fx_idx + index2))) 177
              WRITE_LONG   (fx_off + 0x08 + (0x30 * (abil_fx_idx + index2))) 3 // from general.ids
              WRITE_BYTE   (fx_off + 0x0c + (0x30 * (abil_fx_idx + index2))) 4 // timing: delay/permanent
              WRITE_ASCIIE (fx_off + 0x14 + (0x30 * (abil_fx_idx + index2))) ~cdcc%duration%~ #8
            SET index2 += 1
            SET fx_delta += 1
            SET abil_fx_num += 1
          END
          PATCH_IF (sound1 = 1) BEGIN
            INSERT_BYTES (fx_off +        (0x30 * (abil_fx_idx + index2))) 0x30
              WRITE_ASCIIE (fx_off +        (0x30 * (abil_fx_idx + index2))) ~%clone%~ #48
              WRITE_SHORT  (fx_off +        (0x30 * (abil_fx_idx + index2))) 177
              WRITE_LONG   (fx_off + 0x08 + (0x30 * (abil_fx_idx + index2))) 3 // from general.ids
              WRITE_BYTE   (fx_off + 0x0c + (0x30 * (abil_fx_idx + index2))) 4 // timing: delay/permanent
              WRITE_ASCIIE (fx_off + 0x14 + (0x30 * (abil_fx_idx + index2))) ~cdcd%duration%~ #8
            SET index2 += 1
            SET fx_delta += 1
            SET abil_fx_num += 1
          END
          PATCH_IF (sparklies = 1) BEGIN
            INSERT_BYTES (fx_off +        (0x30 * (abil_fx_idx + index2))) 0x30
              WRITE_ASCIIE (fx_off +        (0x30 * (abil_fx_idx + index2))) ~%clone%~ #48
              WRITE_SHORT  (fx_off +        (0x30 * (abil_fx_idx + index2))) 177
              WRITE_LONG   (fx_off + 0x08 + (0x30 * (abil_fx_idx + index2))) 3 // from general.ids
              WRITE_LONG   (fx_off + 0x0e + (0x30 * (abil_fx_idx + index2))) 4 // duration
              WRITE_ASCII  (fx_off + 0x14 + (0x30 * (abil_fx_idx + index2))) ~cdcvis~ #8
            SET index2 += 1
            SET fx_delta += 1
            SET abil_fx_num += 1
          END
        END // opcode = 5
      END // index2 for loop
    END // charm = 1
    WRITE_SHORT  (abil_off + 0x1e + (abil_length * index)) abil_fx_num
  END // index for loop
  BUT_ONLY