/////                                                  \\\\\
///// bulk item file fixes                             \\\\\
/////                                                  \\\\\

// many items have effects not being applied due to bad timing modes
COPY_EXISTING ~aegis.itm~    ~override~ // color
              ~aegis2.itm~   ~override~ // color
              ~ax1h04.itm~   ~override~ // color
              ~ax1h05.itm~   ~override~ // color
              ~ax1h06.itm~   ~override~ // color
              ~ax1h08.itm~   ~override~ // color
              ~bazpatrg.itm~ ~override~ // immunity to teleport field
              ~blun01.itm~   ~override~ // color
              ~blun04.itm~   ~override~ // color
              ~blun06.itm~   ~override~ // color
              ~blun10.itm~   ~override~ // color
              ~blun23.itm~   ~override~ // color
              ~blun24.itm~   ~override~ // color
              ~blun31.itm~   ~override~ // color
              ~bodhi.itm~    ~override~ // protection from spell: nature's beauty
              ~bow02.itm~    ~override~ // color
              ~bow05.itm~    ~override~ // color
              ~bow08.itm~    ~override~ // color
              ~bow09.itm~    ~override~ // color
              ~bow10.itm~    ~override~ // color
              ~bow11.itm~    ~override~ // color
              ~bow14.itm~    ~override~ // color
              ~bow15.itm~    ~override~ // color
              ~bow16.itm~    ~override~ // color
              ~bow18.itm~    ~override~ // color
              ~bow19.itm~    ~override~ // color
              ~bow20.itm~    ~override~ // color
              ~bow21.itm~    ~override~ // color
              ~bow24.itm~    ~override~ // color
              ~bow26.itm~    ~override~ // color
              ~bow99.itm~    ~override~ // color
              ~bownon.itm~   ~override~ // color
              ~cattac1.itm~  ~override~ // color
              ~cattibow.itm~ ~override~ // color
              ~chalslay.itm~ ~override~ // protection from spell: lower resist
              ~chwraith.itm~ ~override~ // immunities to charm, sleep, hold creature, hold creature type
              ~clown.itm~    ~override~ // colorglow pulse
              ~dagg04.itm~   ~override~ // color
              ~dagg05.itm~   ~override~ // color
              ~dagg16.itm~   ~override~ // color
              ~dagg18.itm~   ~override~ // color
              ~daggshit.itm~ ~override~ // color
              ~demogorg.itm~ ~override~ // protection from spell: lower resist
              ~demsuc01.itm~ ~override~ // protection from spell: nature's beauty
              ~dwhalb01.itm~ ~override~ // color
              ~enmace.itm~   ~override~ // color
              ~enmorn.itm~   ~override~ // color
              ~ensw2h.itm~   ~override~ // color
              ~frosty.itm~   ~override~ // cold resist bonus
              ~fsspir.itm~   ~override~ // character color, immunity to teleport field
              ~ghost.itm~    ~override~ // slow
              ~ghost2.itm~   ~override~ // slow
              ~giafir.itm~   ~override~ // color
              ~giafir2.itm~  ~override~ // color
              ~giafir3.itm~  ~override~ // color
              ~giants01.itm~ ~override~ // color
              ~gorchr.itm~   ~override~ // immunity to teleport field, slay, kill target
              ~gorfirg.itm~  ~override~ // protection from nature's beauty, immunity to animations spmindat & spflayer
              ~gorjelfu.itm~ ~override~ // protection from nature's beauty, immunity to animations spmindat & spflayer
              ~gorjelgr.itm~ ~override~ // protection from nature's beauty, immunity to animations spmindat & spflayer
              ~gormisti.itm~ ~override~ // protection from nature's beauty, immunity to animations spmindat & spflayer
              ~gorwom1.itm~  ~override~ // protection from nature's beauty
              ~halb01.itm~   ~override~ // color
              ~halbrd01.itm~ ~override~ // color
              ~hamm01.itm~   ~override~ // color
//              ~helm14.itm~   ~override~ // remove fear, remove fear 2 effects - remove fear/reset morale should be instant/perm timing
              ~hgber01.itm~  ~override~ // color
              ~hgnymph.itm~  ~override~ // protection from nature's beauty
              ~hgwra01.itm~  ~override~ // protection from nature's beauty
              ~holdring.itm~ ~override~ // immunity to teleport field
              ~hslaywpn.itm~ ~override~ // regen
              ~hspectre.itm~ ~override~ // protection from deathsong, invis detection by script
              ~iax1h01.itm~  ~override~ // color
              ~iblun04.itm~  ~override~ // color
              ~ibow03.itm~   ~override~ // color
              ~ihamm01.itm~  ~override~ // color
              ~innoc2.itm~   ~override~ // protection from nature's beauty
              ~invulner.itm~ ~override~ // immunity to teleport field
              ~irongol.itm~  ~override~ // immunity to sleep, poison
              ~kuobow.itm~   ~override~ // color
              ~lich.itm~     ~override~ // resistance to cold & electricity, immunity to non-magic weapons and spell lev < 6
              ~mdog1.itm~    ~override~ // immunity to charm
              ~npbow.itm~    ~override~ // color
              ~objring.itm~  ~override~ // protection from nature's beauty, immunity to break morale
              ~plymstar.itm~ ~override~ // color
              ~reaver.itm~   ~override~ // color
              ~ring94.itm~   ~override~ // protection from nature's beauty
              ~ring95.itm~   ~override~ // protection from nature's beauty, immunity to animations spmindat & spflayer
              ~ring99.itm~   ~override~ // immunity to animations spmindat & spflayer
              ~ringwolf.itm~ ~override~ // regen
              ~seltest.itm~  ~override~ // use eff
              ~shalt01.itm~  ~override~ // protection from nature's beauty, immunity to break morale
              ~skelclub.itm~ ~override~ // color
              ~skelwasu.itm~ ~override~ // color
              ~slayerwp.itm~ ~override~ // current hp bonus
              ~slaysh01.itm~ ~override~ // protection from nature's beauty
              ~spectr.itm~   ~override~ // protection from nature's beauty
              ~stalker.itm~  ~override~ // protection from nature's beauty
              ~stonring.itm~ ~override~ // set item color
              ~stonskin.itm~ ~override~ // stoneskin effect
              ~surehp1.itm~  ~override~ // immunity to teleport field
              ~sw1h08.itm~   ~override~ // color
              ~sw1h14.itm~   ~override~ // color
              ~sw1h57.itm~   ~override~ // color
              ~sw1h99.itm~   ~override~ // color
              ~sw2h01.itm~   ~override~ // color
              ~sw2h01b.itm~  ~override~ // color
              ~sw2h02.itm~   ~override~ // color
              ~sw2h05.itm~   ~override~ // color
              ~sw2h14.itm~   ~override~ // imunity to spconfus animation
              ~telslav.itm~  ~override~ // protection from nature's beauty
              ~telslav2.itm~ ~override~ // immunity to charm, sleep
              ~ttsword2.itm~ ~override~ // color
              ~vamp.itm~     ~override~ // protection from nature's beauty
              ~vamp1.itm~    ~override~ // protection from nature's beauty
              ~vamp2.itm~    ~override~ // protection from nature's beauty
              ~vamp3.itm~    ~override~ // protection from nature's beauty
              ~wight.itm~    ~override~ // protection from nature's beauty
              ~wraith1.itm~  ~override~ // protection from nature's beauty
              ~xbow01.itm~   ~override~ // color
              ~xbow02.itm~   ~override~ // modify attacks per round
              ~xbow03.itm~   ~override~ // color
              ~xbow07.itm~   ~override~ // modify attacks per round
              ~xbow08.itm~   ~override~ // modify attacks per round
              ~xbow17.itm~   ~override~ // modify attacks per round
  LPF ALTER_EFFECT INT_VAR silent = 1 check_headers = 0 timing = 2 duration = 0 END // instant/while equipped for all global effects
  BUT_ONLY IF_EXISTS

// adds magical flag to a mess of undroppable items to prevent black dragon from taking them; other items lacking magical flag
COPY_EXISTING ~aeriebab.itm~ ~override~
              ~bearspir.itm~ ~override~
              ~bootdriz.itm~ ~override~
              ~bonefd.itm~   ~override~ // bone fiend attack
              ~clck18.itm~   ~override~
              ~dagg19.itm~   ~override~
              ~dax1h01.itm~  ~override~
              ~famcat.itm~   ~override~
              ~famcat25.itm~ ~override~
              ~famdus25.itm~ ~override~
              ~famdust.itm~  ~override~
              ~famfai25.itm~ ~override~
              ~famfair.itm~  ~override~
              ~famfer.itm~   ~override~
              ~famfer25.itm~ ~override~
              ~famimp.itm~   ~override~
              ~famimp25.itm~ ~override~
              ~fampsd.itm~   ~override~
              ~fampsd25.itm~ ~override~
              ~famqua25.itm~ ~override~
              ~famquas.itm~  ~override~
              ~famrab.itm~   ~override~
              ~famrab25.itm~ ~override~
              ~helmskwa.itm~ ~override~
              ~kuobow.itm~   ~override~
              ~kuosper.itm~  ~override~
              ~lionspir.itm~ ~override~
              ~misc4g.itm~   ~override~
              ~misc73.itm~   ~override~ // horn of kazgaroth
              ~misc84.itm~   ~override~
              ~plat98.itm~   ~override~
              ~plybass.itm~  ~override~
              ~plyfist.itm~  ~override~
              ~plymstar.itm~ ~override~
              ~plysala.itm~  ~override~
              ~plyspid.itm~  ~override~
              ~plywyvrn.itm~ ~override~
              ~regisamu.itm~ ~override~  // ruby pendant
              ~scrlag.itm~   ~override~
              ~snakspir.itm~  ~override~
              ~sw1h47.itm~   ~override~
              ~wolfspir.itm~ ~override~
  WRITE_BYTE 0x18 (THIS BOR BIT6)
  BUT_ONLY IF_EXISTS

// fix power levels
COPY_EXISTING ~arow06.itm~   ~override~ // arrows of detonation - explosion has power 3
              ~arow08.itm~   ~override~ // arrows of fire - fire damage has power 6
              ~arow09.itm~   ~override~ // arrows of ice - cold damage has power 6
              ~aurstaf.itm~  ~override~ // aurumach rilmani's undroppable staff - slow effects have power 6
              ~ax1h07.itm~   ~override~ // bala's axe - miscast magic effects have power 3
              ~blun20.itm~   ~override~ // ardulia's flail - slow effects have power 3
              ~bolt03.itm~   ~override~ // bolt of lightning - electrical damage has power 6
              ~bolt05.itm~   ~override~ // bolt of polymorphing - polymorph effects are power 6
              ~bonedag.itm~  ~override~ // bone dagger attack item - slow effects have power 2, all other effects 0
              ~chalcy2.itm~  ~override~ // undroppable weapon of cyric's chosen - blindness effect has power 1
              ~dart03.itm~   ~override~ // dart of stunning - stun effects have power 8
              ~dart04.itm~   ~override~ // dart of wounding - poison damage has power 0, poison portrait icon has power 8
              ~dart05.itm~   ~override~ // asp's nest - poison damage has power 0, poison portrait icon has power 8
              ~dartmel.itm~  ~override~ // melissan's bone daggers - slow and disease effects have power 8
              ~globblu1.itm~ ~override~ // blue globe - cold damage at power 5
              ~globred1.itm~ ~override~ // red globe - fire damage at power 4
              ~gorcamb.itm~  ~override~ // aesgearth's undroppable weapon - stun at power 6, str/con drain at power 8
              ~hamm03.itm~   ~override~ // ashideena - electrical damage has power 8
              ~hamm05.itm~   ~override~ // borok's fist - electrical damage has power 8
              ~hgber01.itm~  ~override~ // berren's undroppable weapon - slow and dex penalties at power 4
              ~hgnya01.itm~  ~override~ // nyalee's undroppable weapon - slow, entangle effects at power 4
              ~icetrl.itm~   ~override~ // blizzard trolls' undroppable weapon - stun, dex penalty at power 6
              ~killsw01.itm~ ~override~ // arkanis gath's insta-kill sword for crossing shadow thieves - all elemental damages at power 8
              ~kuobolt3.itm~ ~override~ // high level kuo-toa bolts - web/entangle effects at power 2
              ~misc5c.itm~   ~override~ // rift device - fire damage has power 100, all other effects are at 0
              ~mistcd.itm~   ~override~ // attack of crimson deaths - visual effect has power 1
              ~mistho.itm~   ~override~ // attack of mist horrors, swamp horrors - horror effects are at power 4
              ~mistice.itm~  ~override~ // attack of ice mists - horror effects are at power 4
              ~mistva.itm~   ~override~ // attack of vampiric mists - level drain at power 1
              ~mistva2.itm~  ~override~ // attack of vampiric wraiths - level drain at power 1
              ~mistwa.itm~   ~override~ // attack of wandering horrors - stun at power 4
              ~mound.itm~    ~override~ // attack of shambling mounds - slow, ac penalty, extra damage, entangle at power 1, play sound at power 2
              ~nebdag.itm~   ~override~ // neb's dagger - slow effect at power 2, poison at 0
              ~potn26.itm~   ~override~ // potion of explosions
              ~potn27.itm~   ~override~ // potion of firebreath
              ~quasclaw.itm~ ~override~ // attack of quasit familiars - dex drain has power 4
              ~ravag01.itm~  ~override~ // attack of ravager - one effect (visual) has power 3, all others 0
              ~ravag02.itm~  ~override~ // attack of ravager - stun has power 6, all others 0
              ~revent1.itm~  ~override~ // attack of revenants - paralyzation effects at power 1
              ~ring20.itm~   ~override~ // ring of energy
              ~rods03.itm~   ~override~ // rod of resurrection
              ~scrl03.itm~   ~override~ // protection from acid
              ~scrl04.itm~   ~override~ // protection from cold
              ~scrl05.itm~   ~override~ // protection from electricity
              ~scrl06.itm~   ~override~ // protection from fire
              ~scrl08.itm~   ~override~ // protection from poison
              ~scrl09.itm~   ~override~ // protection from undead
              ~scrl15.itm~   ~override~ // protection from petrification
              ~secret02.itm~ ~override~ // pulse ammo - magical damage for easter egg item at power 8
              ~sendai.itm~   ~override~ // sendai's flail - slow has power 6, other effects such as str drain and poison use 0
              ~shille.itm~   ~override~ // shillelagh - visual effect has power 1
              ~spermel.itm~  ~override~ // mellisan's spear - slow and stun at power 8, save penalties at power 6
              ~staf14.itm~   ~override~ // staff of the woodlands
              ~sw1h06.itm~   ~override~ // varscona - cold damage at power 8
              ~sw1h58.itm~   ~override~ // short sword of mask - some entangle effects at power 1, 2
              ~sw1h59.itm~   ~override~ // short sword of mask - some entangle effects at power 1, 2
              ~telslav.itm~  ~override~ // attack of slave wraiths - slay and finger of death animation at power 7
              ~trolltor.itm~ ~override~ // attack of tor'gal - slow and str drain at power 3
              ~wand12.itm~   ~override~ // wand of wonder - all effects at power 0 except visuals at 8
              ~wolfwi1.itm~  ~override~ // attack of winter wolves - cold damage at power 1
              ~wolfwi2.itm~  ~override~ // attack of winter wolves - cold damage at power 1
              ~xbow15.itm~   ~override~ // firetooth - fire damage at power 6
              ~xbow16.itm~   ~override~ // firetooth - fire damage at power 6
  LPF ALTER_EFFECT INT_VAR silent = 1 check_globals = 0 power = 0 END // should bypass spell protections
  BUT_ONLY IF_EXISTS

// weapon-speed fixes (fixes descripts and items)
ACTION_CLEAR_ARRAY cd_bulk_item_fixes
ACTION_DEFINE_ASSOCIATIVE_ARRAY cd_bulk_item_fixes BEGIN

  // descript is right, item is wrong
  aegis    => 1 // aegis fang (descript is correct)
  aegis2   => 1 // aegis fang (descript is correct)
  ax1h07   => 7 // bala's axe (descript is correct)
  dart01   => 2 // dart (descript is correct)
  misc9q   => 5 // scimitar (descript is correct)
  sper03   => 6 // spear +3, backbiter (descript is correct)
  staf04   => 4 // quarterstaff (descript is correct)
  staf05   => 1 // staff of striking (descript is correct)
  stardart => 0 // dart +5 (descript doesn't have speed listed w/o GTU/L)
  sw1h26   => 2 // ilbratha +1 (descript is correct)
  sw2h03   => 10// cursed berserking sword +3 (descript is correct)

  // both item and descript are wrong
  blun22   => 1 // blackblood +3 (string #39490 and item need updates)
  blun23   => 2 // bone club +2, +3 vs. undead (string #39493 and item need updates)
  blun24   => 2 // gnasher +2 (string #39495 and item need updates)
  blun25   => 5 // imod (string #60877 and item need updates)
  blun26   => 1 // club of detonation +3 (string #66375 and item need updates)
  blun27   => 0 // club of detonation +5 (string #66376 and item need updates)
  bow25    => 4 // long bow +3 (string #71058 and item need updates) (string #71958 already fixed in strings for separate thac0 issue)
  dagg11   => 0 // boomerang dagger (string #39527 and item need updates)
  dagg12   => 0 // fire tooth +3 (string #39528 and item need updates)
  dwxbow01 => 2 // drow crossbow of speed (string #46706 and item need updates)
  hamm04   => 3 // hammer +1, +4 vs. giantkin (string #22263 and item need updates)
  hamm09   => 0 // crom faeyr (string #60863 and item need updates)
  misc4u   => 2 // embarl's dagger (string #34732 and item need updates)
  npbow    => 4 // bow of arvoreen (string #50827 and item need updates)
  slng08   => 2 // erinne sling +4 (string #66393 and item need updates)
  slng09   => 1 // erinne sling +5 (string #66394 and item need updates)
  sper12   => 1 // ixil's nail +6 (string #66474 and item need updates) 
  staf09   => 2 // staff of command (string #39625 and item need updates)
  staf12   => 2 // staff of power (string #39628 and item need updates)
  staf13   => 2  //staff of thunder and lightning (string #39629 and item need updates)
  sw1h24   => 4 // flame tongue (string #6526 and item need updates)
  sw1h28   => 0 // cutthroat +4 (string #39451 and item need updates)
  sw1h54   => 2 // equalizer (string #60866 and item need updates)
  sw2h14   => 7 // lilarcor (string #34090 and item need updates)
  waflail  => 4 // defender of easthaven (string #32187 and item need updates) (string #32187 already fixed in strings for separate thac0 issue)
  wasling  => 1 // sling of everard (string #32143 and item need updates)
  wastaff  => 1 // staff of arundel (string #32128 and item need updates)
  xbow03   => 5 // heavy crossbow of accuracy (string #7352 and item need updates)
  xbow06   => 4 // light crossbow of speed (string #7353 and item need updates)
  xbow13   => 1 // crossbow of afflication (string #39506 and item need updates)

  // item is right, descript is wrong
  blun14d  => 5 // flail of ages +2 (cold, fire) (strref #41389)
  blun14e  => 5 // flail of ages +2 (cold, acid) (strref #41620)
  blun14f  => 5 // flail of ages +2 (acid, fire) (strref #41621)
  blun35   => 3 // ice star +4 (strref #73912)
  bow11    => 5 // strong arm (strref #39511)
  bow17    => 5 // long bow +2 (strref #176)
  bow18    => 4 // short bow +2 (strref #199)
  halb04   => 6 // dragon's bane (strref #39531)
  misc5t   => 4 // shaman's staff of goodberries (strref #47131)
  npsw05   => 1 // entropy (strref #51947)
  npsw06   => 1 // chaos blade (strref #51949)
  sper10   => 2 // spear of withering (strref #2494)
  sper11   => 2 // ixil's nail +4 (strref #66372)
  staf10   => 3 // staff of curing (strref #39626)
  staf11   => 1 // staff of the magi (strref #39627)
  staf15   => 2 // staff of air (strref #39631)
  staf16   => 2 // staff of earth (strref #39632)
  staf17   => 2 // staff of fire (strref #39633)
  staf18   => 2 // staff +2 (strref #39634)
  staf23   => 2 // serpent shaft (strref #66369)
  sw1h52   => 2 // scimitar +3 water's edge (strref #51884)
  sw1h53   => 4 // sword of flame +1 (strref #4421)
  sw1h60   => 1 // angurvadal +4 (strref #66203)
  sw1h69   => 0 // spectral brand +5 (strref #66275)
  sw1h73   => 2 // long sword +3 (strref #70785)
  sw2h15   => 7 // silver sword (strref #48658)
  wa2halb  => 6 // harmonium halberd (strref #61593)

END

OUTER_SPRINT text_match @30

ACTION_PHP_EACH cd_bulk_item_fixes AS item => fix BEGIN

  COPY_EXISTING ~%item%.itm~ ~override~
    LPF ALTER_HEADER INT_VAR silent = 1 match_location = 1 speed = fix END // anything that turns up in weapon slots (e.g. not magical abilities)
    LAUNCH_PATCH_MACRO cd_bulk_fix_item_strings
    BUT_ONLY IF_EXISTS

END

// Comprehensive batch of item-weight fixes (Wisp)
ACTION_CLEAR_ARRAY cd_bulk_item_fixes
ACTION_DEFINE_ASSOCIATIVE_ARRAY cd_bulk_item_fixes BEGIN

//  chan02   => 20 // chainmail +1 (identified strref is wrong so this would patch wrong string; fixed in individual fixes)
//  plymstar =>  0 // (zero-weight magical items) ogre's morningstar from polymorph self; uses generic morningstar description so fixed individually

  // weight in item is wrong
  bolt07   =>  0 // (zero-weight magical items) jan's flashers
  bow06    =>  2 // short bow +1
  brac15   =>  2 // bracers of defense ac 3
  brdflute =>  0 // (zero-weight magical items) bard flute
  clck13   =>  4 // traveller's robe
  dagg05   =>  0 // throwing dagger
  dwchan02 => 12 // drow adamantine chain +5
  dwshld01 =>  7 // drow shield +3
  enmace   =>  0 // (zero-weight magical items) enchanted weapon: mace
  enmorn   =>  0 // (zero-weight magical items) enchanted weapon: morningstar
  enstaff  =>  0 // (zero-weight magical items) enchanted weapon: staff
  ensw1h01 =>  0 // (zero-weight magical items) enchanted weapon: long sword
  ensw1h02 =>  0 // (zero-weight magical items) enchanted weapon: short sword
  ensw2h   =>  0 // (zero-weight magical items) enchanted weapon: battle axe
  melfmet  =>  0 // (zero-weight magical items) melf's minute meteors
  plysala  =>  0 // (zero-weight magical items) salamander's spear from polymorph self
  shille   =>  0 // (zero-weight magical items) shillegagh
  shld23   => 10 // fortress shield +3
  sorb     =>  0 // (zero-weight magical items) sol's searing orb
  sper06   =>  3 // spear +3
  staf04   =>  4 // quarterstaff
  staf08   =>  4 // martial staff +3
  staf10   =>  4 // staff of curing
  staf11   =>  4 // staff of the magi
  staf13   =>  4 // staff of thunder and lightning
  staf20   =>  3 // staff of rynn +4
  sw1h15   =>  4 // scimitar +3, frostbrand
  sw1h16   =>  4 // scimitar +5, defender
  sw1h23   =>  4 // scimitar +2, rashad's talon
  sw1h32   =>  3 // dragonslayer
  sw2h03   => 15 // cursed berserking sword +3
  sw2h12   => 10 // flame of the north
  sw2h15   => 15 // silver sword

  // weight in description is wrong
  bag06    =>  2 // potion case (strref #71131) (also used by other potion cases)
  blun03   => 13 // flail +1 (strref #19359)
  blun04   => 10 // generic mace (strref #6709)
  hlolth   =>  7 // handmaiden's mace (strref #54340)
  kuobolt  =>  0 // kuo-toa bolt (strref #57897) (also used by kuobolt2, kuobolt3)
  npstaf   =>  3 // staff of the high forest (strref #8505)
  plat19   => 40 // full plate mail +2 (strref #1768)
  shld27   =>  4 // saving grace (strref #39579)
  wa2shiel =>  4 // shield of balduran (strref #61580)
  
  // string and item are wrong
  sahbolt  => 0 // Paralytic Bolt (strref #57919)

END

OUTER_SPRINT text_match @31

ACTION_PHP_EACH cd_bulk_item_fixes AS item => fix BEGIN

  COPY_EXISTING ~%item%.itm~ ~override~
    WRITE_LONG 0x4c fix // fixes item weight
    LAUNCH_PATCH_MACRO cd_bulk_fix_item_strings
    BUT_ONLY IF_EXISTS

END

// thac0 fixes
ACTION_CLEAR_ARRAY cd_bulk_item_fixes
ACTION_DEFINE_ASSOCIATIVE_ARRAY cd_bulk_item_fixes BEGIN
  arow08 => 0 // arrows of fire, only needs an item fix
  bow09  => 3 // ripper +2, also fixes string #39508
  bow13  => 5 // mana bow +4, also fixes string #39513
  bow17  => 3 // long bow +2, also fixes string #176
  bow22  => 5 // taralash +4, also fixes string #66388
  bow23  => 6 // taralash +5, also fixes string #66389
  bow25  => 4 // long bow +2, also fixes string #71058
END

OUTER_SPRINT text_match @32

ACTION_PHP_EACH cd_bulk_item_fixes AS item => fix BEGIN

  COPY_EXISTING ~%item%.itm~ ~override~
    LPF ALTER_HEADER INT_VAR silent = 1 match_location = 1 to_hit = fix END // anything that turns up in weapon slots (e.g. not magical abilities)
    LAUNCH_PATCH_MACRO cd_bulk_fix_item_strings
    BUT_ONLY IF_EXISTS

END

// lore fixes
ACTION_CLEAR_ARRAY cd_bulk_item_fixes
ACTION_DEFINE_ASSOCIATIVE_ARRAY cd_bulk_item_fixes BEGIN

  ax1h06   =>  65 // throwing axe +2, unused
  ax1h07   =>  65 // bala's axe (bg lore value), unused but restored by UB
  boot12   =>  55 // available via killing carras; already ID'd in store
  bull06   =>  35 // bullet +4
  chan03   =>  65 // mail of the dead
  chan21   =>  75 // chain mail +3
  dagg04   =>  60 // dagger +2 longtooth (bg lore value), unused
  dwchan01 =>  75 // drow elven chain +3
  dwchan02 =>  75 // drow adamantine chain +5
  dwplat01 =>  75 // drow full plate +5
  halb03   =>  60 // suryris' blade
  leat03   =>  60 // protector of the second +2
  leat06   => 100 // missile attraction +2
  misc3a   =>  80 // book of infinite spells
  misc3e   =>  75 // black spider figurine
  misc3f   =>  75 // jade hound, unused
  misc3j   =>   0 // bronze horn of valhalla (upgrades come identified)
  misc3k   =>   0 // iron horn of valhalla (upgrades come identified)
  plat02   =>  40 // plate mail +1
  plat09   =>  50 // mithral field plate armor +2, unused
  plat23   =>  75 // full plate mail +2
  potn40   =>   0 // cursed potion of invulnerability shouldn't require ID
  quiver02 =>  20 // case of plenty +1
  regisamu =>  65 // ruby pendant
  ring43   =>   0 // oaken ring
  rods02   =>  70 // rod of lordly might
  rods06   =>  85 // rod of reversal
  shld17   =>  10 // buckler +1
  slng03   =>  45 // sling +3
  staf06   =>  25 // staff mace
  staf07   =>  65 // staff spear +2
  sw1h06   =>  60 // long sword +2
  sw1h24   =>  70 // flame tongue (bg lore value)
  wand11   =>  50 // wand of the heavens

END

ACTION_PHP_EACH cd_bulk_item_fixes AS item => fix BEGIN

    COPY_EXISTING ~%item%.itm~ ~override~
      WRITE_SHORT 0x42 fix
      BUT_ONLY IF_EXISTS

END

// item type fixes
ACTION_CLEAR_ARRAY cd_bulk_item_fixes
ACTION_DEFINE_ASSOCIATIVE_ARRAY cd_bulk_item_fixes BEGIN

  blun27   => 17 // Club of Detonation +5
  book05   =>  0 // Manual of Quickness of Action (type 0 allows quickslotting)
  book07   =>  0 // Tome of Leadership and Influence (type 0 allows quickslotting)
  book08   =>  0 // Tome of Understanding (type 0 allows quickslotting)
  book32   => 37 // History of Tethyr
  book94   => 37 // The Vampiricus Omnibus: Unabridged
  book95   => 37 // Dea Vampir Becomos
  book96   => 37 // Conjur Ota Servanta
  dagg10   => 16 // soultaker dagger
  misc73   =>  0 // horn of kazgaroth (type 0 allows quickslotting)
  miscan   =>  1 // galvena's medallion
  miscb1   =>  1 // Talisman of Rillifane
  scrla9   => 37 // waneev's note
  scrlaa   => 37 // waneev's note
  scrlab   => 37 // monkey balls
  scrlac   => 37 // amnish dragoon soup
  scrlad   => 37 // baldur's delight
  scrlaf   => 37 // ruby racks
  scrlag   => 37 // crom faeyr scroll
  scrlhp   => 37 // harper note
  scrlick  => 37 // illithid correspndence
  scrlmz   => 37 // note from Mazzy Fentan
  sw1h54c  => 34 // pommel jewel of the equalizer

END

ACTION_PHP_EACH cd_bulk_item_fixes AS item => fix BEGIN

    COPY_EXISTING ~%item%.itm~ ~override~
      WRITE_SHORT 0x1c fix
      BUT_ONLY IF_EXISTS

END

// prof fixes
ACTION_CLEAR_ARRAY cd_bulk_item_fixes
ACTION_DEFINE_ASSOCIATIVE_ARRAY cd_bulk_item_fixes BEGIN

  // all of these prof 2 items are ammo; prof 0 lets you use them w/o non-prof penalty. The non-zero value keeps the prof type from the bow/sling/whatever
  aegis    =>  97 // aegis fang
  aegis2   =>  97 // aegis fang
  arow01   =>   2 // (ammo with 0 prof removes non-prof penalty)  arrows - arrows w/o shortbow prof
  arow02   =>   2 // (ammo with 0 prof removes non-prof penalty)  arrows +1 - arrows w/o shortbow prof
  arow03   =>   2 // (ammo with 0 prof removes non-prof penalty)  arrow of slaying - arrows w/o shortbow prof
  arow04   =>   2 // (ammo with 0 prof removes non-prof penalty)  acid arrows - arrows w/o shortbow prof
  arow05   =>   2 // (ammo with 0 prof removes non-prof penalty)  arrow of biting - arrows w/o shortbow prof
  arow06   =>   2 // (ammo with 0 prof removes non-prof penalty)  arrows of detonation  - arrows w/o shortbow prof
  arow07   =>   2 // (ammo with 0 prof removes non-prof penalty)  arrows of dispelling - arrows w/o shortbow prof
  arow08   =>   2 // (ammo with 0 prof removes non-prof penalty)  arrow of fire - arrows w/o shortbow prof
  arow09   =>   2 // (ammo with 0 prof removes non-prof penalty)  arrows of ice - arrows w/o shortbow prof
  arow10   =>   2 // (ammo with 0 prof removes non-prof penalty)  arrows of piercing - arrows w/o shortbow prof
  arow11   =>   2 // (ammo with 0 prof removes non-prof penalty)  arrow +2 - arrows w/o shortbow prof
  arow14   =>   2 // (ammo with 0 prof removes non-prof penalty)  poisoned arrow - arrows w/o shortbow prof
  arow15   =>   2 // (ammo with 0 prof removes non-prof penalty)  arrow +3 - arrows w/o shortbow prof
  arow1a   =>   2 // (ammo with 0 prof removes non-prof penalty)  arrow +2 - arrows w/o shortbow prof
  bolt01   =>   2 // (ammo with 0 prof removes non-prof penalty)  bolt - bolts w/o xbow prof
  bolt02   =>   2 // (ammo with 0 prof removes non-prof penalty)  bolt +1 - bolts w/o xbow prof
  bolt03   =>   2 // (ammo with 0 prof removes non-prof penalty)  bolt of lightning - bolts w/o xbow prof
  bolt04   =>   2 // (ammo with 0 prof removes non-prof penalty)  bolt of biting  - bolts w/o xbow prof
  bolt05   =>   2 // (ammo with 0 prof removes non-prof penalty)  bolt of polymorphing - bolts w/o xbow prof
  bolt06   =>   2 // (ammo with 0 prof removes non-prof penalty)  bolt +2 - bolts w/o xbow prof
  bolt07   =>   2 // (ammo with 0 prof removes non-prof penalty)  flasher master bruiser mate - bolts w/o xbow prof
  bolt08   =>   2 // (ammo with 0 prof removes non-prof penalty)  blessed bolt - bolts w/o xbow prof
  bolt09   =>   2 // (ammo with 0 prof removes non-prof penalty)  bolt +3 - bolts w/o xbow prof
  bow06    => 105 // short bow +1
  bow07    => 104 // long bow of marksmanship
  bruenaxe =>  92 // battle axe +3
  bull01   =>   2 // (ammo with 0 prof removes non-prof penalty)  bullet - bullet w/o sling prof
  bull02   =>   2 // (ammo with 0 prof removes non-prof penalty)  bullet +1 - bullet w/o sling prof
  bull03   =>   2 // (ammo with 0 prof removes non-prof penalty)  bullet +2 - bullet w/o sling prof
  bull04   =>   2 // (ammo with 0 prof removes non-prof penalty)  sunstone bullet +1 - bullet w/o sling prof
  bull05   =>   2 // (ammo with 0 prof removes non-prof penalty)  bullet +3 - bullet w/o sling prof
  bull06   =>   2 // (ammo with 0 prof removes non-prof penalty)  bullet +4 - bullet w/o sling prof
  dwbolt01 =>   2 // (ammo with 0 prof removes non-prof penalty)  drow bolt of sleep - bolts w/o xbow prof
  dwbolt02 =>   2 // (ammo with 0 prof removes non-prof penalty)  drow bolt of stunning - bolts w/o xbow prof
  dwbolt03 =>   2 // (ammo with 0 prof removes non-prof penalty)  drow bolt +1 - bolts w/o xbow prof
  flam01   =>   2 // (ammo with 0 prof removes non-prof penalty)  flamethrower - bolts w/o xbow prof
  frag01   =>   2 // (ammo with 0 prof removes non-prof penalty)  frag grenade - bolts w/o xbow prof
  frosty   =>   2 // (ammo with 0 prof removes non-prof penalty)  dr. freeze death ray - bolts w/o xbow prof
  iarow01  =>   2 // (ammo with 0 prof removes non-prof penalty)  arrows - arrows w/o shortbow prof
  kuobolt  =>   2 // (ammo with 0 prof removes non-prof penalty)  kuo-toa bolts - bolts w/o xbow prof
  kuobolt2 =>   2 // (ammo with 0 prof removes non-prof penalty)  kuo-toa bolts - bolts w/o xbow prof
  kuobolt3 =>   2 // (ammo with 0 prof removes non-prof penalty)  kuo-toa bolts - bolts w/o xbow prof
  laser    =>   2 // (ammo with 0 prof removes non-prof penalty)  laser - bolts w/o xbow prof
  light    =>   2 // (ammo with 0 prof removes non-prof penalty)  wand of magic missiles - bolts w/o xbow prof
  misc4q   =>  89 // ogre's sword
  misc4u   =>  96 // embarl's dagger
  misc5t   => 102 // shaman's staff
  misc75   =>  96 // dagger of venom
  puls01   =>   2 // (ammo with 0 prof removes non-prof penalty)  wand of magic missiles - bolts w/o xbow prof
  puls02   =>   2 // (ammo with 0 prof removes non-prof penalty)  wand of magic missiles - bolts w/o xbow prof
  quiv01   =>   2 // (ammo with 0 prof removes non-prof penalty)  arrows - arrows w/o shortbow prof
  quiver01 =>   2 // (ammo with 0 prof removes non-prof penalty)  quiver of plenty +1 - arrows w/o shortbow prof
  quiver02 =>   2 // (ammo with 0 prof removes non-prof penalty)  case of plenty +1 - bolts w/o xbow prof
  quiver03 =>   2 // (ammo with 0 prof removes non-prof penalty)  quiver of plenty +2 - arrows w/o shortbow prof
  quiver04 =>   2 // (ammo with 0 prof removes non-prof penalty)  case of plenty +2 - bolts w/o xbow prof
  quiver05 =>   2 // (ammo with 0 prof removes non-prof penalty)  bag of plenty +1 - bullet w/o sling prof
  quiver06 =>   2 // (ammo with 0 prof removes non-prof penalty)  bag of plenty +2 - bullet w/o sling prof
  sahbolt  =>   2 // (ammo with 0 prof removes non-prof penalty)  paralytic bolt - bolts w/o xbow prof
  secret02 =>   2 // (ammo with 0 prof removes non-prof penalty)  pulse ammunition - bolts w/o xbow prof
  secret03 =>   2 // (ammo with 0 prof removes non-prof penalty)  frag grenade - bolts w/o xbow prof
  secret04 =>   2 // (ammo with 0 prof removes non-prof penalty)  scorcher ammunition - bolts w/o xbow prof

END

ACTION_PHP_EACH cd_bulk_item_fixes AS item => fix BEGIN

    COPY_EXISTING ~%item%.itm~ ~override~
      WRITE_BYTE 0x31 fix
      BUT_ONLY IF_EXISTS

END

// enchantment fixes
ACTION_CLEAR_ARRAY cd_bulk_item_fixes
ACTION_DEFINE_ASSOCIATIVE_ARRAY cd_bulk_item_fixes BEGIN

  aegis    => 3 // aegis fang, real
  aegis2   => 3 // aegis fang, droppable version
  arow04   => 1 // acid arrows
  bearspir => 3 // weapon of totemic druid summon
  bolt07   => 1 // Flasher Master Bruiser Mate
  bow06    => 1 // short bow +1
  bruenaxe => 3 // battle axe +3
  bull04   => 1 // sunstone bullet
  dagg19   => 1 // dagger of <CHARNAME>
  dart05   => 1 // asp's nest
  kuobolt2 => 2 // kuo-toa bolt
  lionspir => 3 // weapon of totemic druid summon
  misc75   => 2 // dagger of venom
  p3-12m4  => 4 // by Bioware naming convention, this item should be 4 enchantment
  skelwasu => 1 // two-handed sword +1 used by summoned skeleton warriors
  snakspir => 3 // weapon of totemic druid summon
  staf10   => 1 // staff of curing
  sw1h03   => 3 // kondar
  sw1h31   => 4 // daystar
  wamace   => 5 // jerrod's mace (+5 vs. demons)
  wolfspir => 3 // weapon of totemic druid summon

END

ACTION_PHP_EACH cd_bulk_item_fixes AS item => fix BEGIN

    COPY_EXISTING ~%item%.itm~ ~override~
      WRITE_LONG  0x60 fix
      BUT_ONLY IF_EXISTS

END

//items with dispellable on-equip effects (Wisp)
COPY_EXISTING ~aurstaf.itm~  ~override~ // dispellable protection from projectile: bullet
              ~dragring.itm~ ~override~ // dispellable protection from projectile: arrowhvy, axe, bolt, bullet, dagger, dart
              ~elemchan.itm~ ~override~ // dispellable opcode 232, renewing globe of blades ability
              ~elemyanc.itm~ ~override~ // ditto
              ~impinvis.itm~ ~override~ // dispellable invisibility (creatures should not be visible, ever)
              ~jonhp1.itm~   ~override~ // dispellable protection from fiends
              ~kuoring.itm~  ~override~ // dispellable immunity to slow
              ~lich.itm~     ~override~ // dispellable protection from fiends
              ~mage05.itm~   ~override~ // free action. dispellable everything
              ~mage06.itm~   ~override~ // dispellable haste
              ~npsw03.itm~   ~override~ // dispellable opcode 232, for the 'retribution' type effect on the sword
              ~slayerwp.itm~ ~override~ // dispellable protection from projectile: arrowhvy, axe, bolt, bullet, dagger, dart
              ~sw1hseek.itm~ ~override~ // dispellable apr bonus
  LPF ALTER_EFFECT INT_VAR silent = 1 check_headers = 0 match_resist_dispel = 1 resist_dispel = 2 END
  LPF ALTER_EFFECT INT_VAR silent = 1 check_headers = 0 match_resist_dispel = 3 resist_dispel = 2 END
  BUT_ONLY IF_EXISTS
  
// dispel magic via items can not be blocked; route through spell to allow for op 206 to block if needed - see also cditmdm0.spl, cditmdm1.spl, cd_item_dispel_magic item array
ACTION_CLEAR_ARRAY cd_item_dispel_magic
ACTION_DEFINE_ASSOCIATIVE_ARRAY cd_item_dispel_magic BEGIN

  arow07   => 99 // always dispel
  carsomyr => 99 // always dispel (melee), cast always dispel (magical)
  deva     =>  0 // caster level, power 15
  devaevil =>  0 // caster level, power 15
  elemchan =>  0 // caster level, power 15
  elemcryo =>  0 // caster level, power 15
  elemhydr =>  0 // caster level, power 15
  elemimix =>  0 // caster level, power 15
  elemogre =>  0 // caster level, power 15
  elemsunn =>  0 // caster level, power 15
  elemyanc =>  0 // caster level, power 15
  elemzaam =>  0 // caster level, power 15
  finsol01 => 22 // specific level 22
  misc5c   => 99 // always (magical header)
  planetar =>  0 // caster level, power 15
  plot04i  => 99 // always
  potn33   => 99 // always
  ravag01  => 25 // specific level 25
  reaver   => 99 // always
  scrl07   => 99 // always (cast)
  staf11   => 30 // specific level 30
  sw2h10   => 30 // specific level 30
  sw2h19   => 30 // specific level 30

END

ACTION_PHP_EACH cd_item_dispel_magic AS item => level BEGIN

  COPY_EXISTING ~%item%.itm~ ~override~
    PATCH_IF level = 99 BEGIN SET slevel = 0 SET level = 0 END ELSE BEGIN SET slevel = 1 END // cditmdm0 always dispels, cditmdm1 uses level (up to 50)
    LPF ALTER_EFFECT INT_VAR match_opcode = 58 opcode = 146 parameter1 = level parameter2 = 1 STR_VAR resource = EVAL ~cditmdm%slevel%~ END // change dispel to cast spell
    // delete associated dispel magic effects
    LPF DELETE_EFFECT INT_VAR match_opcode =  77 END // cure feeblemind
    LPF DELETE_EFFECT INT_VAR match_opcode =  81 END // cure deafness
    LPF DELETE_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 14056 END // 'dispel effects' string
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 match_parameter1 = 7 match_parameter2 = 7 STR_VAR match_resource = destself END // destroy illusionary creatures
    LPF DELETE_EFFECT INT_VAR match_opcode = 215 STR_VAR match_resource = spdispma END // DM visuals
    LPF DELETE_EFFECT INT_VAR match_opcode = 240 match_parameter2 =  48 END // remove icon: feeblemind
    LPF DELETE_EFFECT INT_VAR match_opcode = 240 match_parameter2 = 112 END // remove icon: deaf
    IF_EXISTS

END

// targeted charm spells w/ portrait icons; see also series of cdc[abcde]XXX.eff files created
COPY_EXISTING ~regisamu.itm~ ~override~ // 60s dire charm icon
              ~ring03.itm~   ~override~ // 120s eff_m22a expiry sound
              ~staf14.itm~   ~override~ // spnwchrm, 300s charm icon
              ~spcl311.spl~  ~override~ // 120s charm icon, spnwchrm
              ~spcl641.spl~  ~override~ // spnwchrm, 7200s eff_m22a expiry sound
              ~spin108.spl~  ~override~ // 120s charm icon
              ~spin119.spl~  ~override~ // 100s charm icon
              ~spin980.spl~  ~override~ // 100s charm icon, 100s eff_e07 expiry sound, spnwchrm
              ~sppr204.spl~  ~override~ // spnwchrm, 60s charm icon, 60s eff_m22a expiry shound - also fixes wrong save on sound (174)
              ~sppr982.spl~  ~override~ // 48s dire charm icon
              ~spwi104.spl~  ~override~ // 30s charm icon, spnwchrm, 30s eff_e07 expiry sound
              ~spwi316.spl~  ~override~ // 30s dire charm icon, spnwchrm, 30s eff_e07 expiry sound - also fixes one charm effect save wrong
              ~spwi943.spl~  ~override~ // 120s dire charm icon
  READ_ASCII 0x00 sig (3)
  SET abil_length = 0x28
  PATCH_IF ("%sig%" STRING_COMPARE_CASE "ITM" = 0) BEGIN
    SET abil_length += 0x10
  END
  SET fx_delta = 0
  READ_LONG  0x64 abil_off
  READ_SHORT 0x68 abil_num
  READ_LONG  0x6a fx_off
  FOR (index = 0 ; index < abil_num ; ++index) BEGIN
    READ_SHORT  (abil_off + 0x1e + (abil_length * index)) abil_fx_num
    WRITE_SHORT (abil_off + 0x20 + (abil_length * index)) (THIS + fx_delta)
    READ_SHORT  (abil_off + 0x20 + (abil_length * index)) abil_fx_idx
    SET charm = 0
    SET icon0 = 0
    SET icon1 = 0
    SET sound0 = 0
    SET sound1 = 0
    SET sparklies = 0
    FOR (index2 = 0 ; index2 < abil_fx_num ; ++index2) BEGIN
      READ_SHORT (fx_off +        (0x30 * (abil_fx_idx + index2))) opcode
      READ_LONG  (fx_off + 0x08 + (0x30 * (abil_fx_idx + index2))) param2
      READ_ASCII (fx_off + 0x14 + (0x30 * (abil_fx_idx + index2))) resource
      PATCH_IF (opcode = 5) BEGIN
        SET charm = 1 // sanity check
        READ_LONG (fx_off + 0x0e + (0x30 * (abil_fx_idx + index2))) duration
      END ELSE
      PATCH_IF ((opcode = 142) AND (param2 = 0)) BEGIN
        SET icon0 = 1
        DELETE_BYTES (fx_off +        (0x30 * (abil_fx_idx + index2))) 0x30
        SET index2 -= 1
        SET fx_delta -= 1
        SET abil_fx_num -= 1
      END ELSE
      PATCH_IF ((opcode = 142) AND (param2 = 1)) BEGIN
        SET icon1 = 1
        DELETE_BYTES (fx_off +        (0x30 * (abil_fx_idx + index2))) 0x30
        SET index2 -= 1
        SET fx_delta -= 1
        SET abil_fx_num -= 1
      END ELSE
      PATCH_IF ((opcode = 174) AND ("%resource%" STRING_COMPARE_CASE ~eff_m22a~ = 0)) BEGIN
        SET sound0 = 1
        DELETE_BYTES (fx_off +        (0x30 * (abil_fx_idx + index2))) 0x30
        SET index2 -= 1
        SET fx_delta -= 1
        SET abil_fx_num -= 1
      END ELSE
      PATCH_IF ((opcode = 174) AND ("%resource%" STRING_COMPARE_CASE ~eff_e07~ = 0)) BEGIN
        SET sound1 = 1
        DELETE_BYTES (fx_off +        (0x30 * (abil_fx_idx + index2))) 0x30
        SET index2 -= 1
        SET fx_delta -= 1
        SET abil_fx_num -= 1
      END ELSE
      PATCH_IF ((opcode = 215) AND ("%resource%" STRING_COMPARE_CASE ~spnwchrm~ = 0)) BEGIN
        SET sparklies = 1
        DELETE_BYTES (fx_off +        (0x30 * (abil_fx_idx + index2))) 0x30
        SET index2 -= 1
        SET fx_delta -= 1
        SET abil_fx_num -= 1
      END
    END
    PATCH_IF ((charm = 1) AND (icon0 +icon1 + sound0 + sound1 + sparklies != 0)) BEGIN // don't bother if no charm found, or if no ancillaries found
      FOR (index2 = 0 ; index2 < abil_fx_num ; ++index2) BEGIN
        READ_SHORT (fx_off +        (0x30 * (abil_fx_idx + index2))) opcode
        PATCH_IF (opcode = 5) BEGIN
          READ_ASCII   (fx_off +        (0x30 * (abil_fx_idx + index2))) clone (48)
          PATCH_IF (icon0 = 1) BEGIN
            INSERT_BYTES (fx_off +        (0x30 * (abil_fx_idx + index2))) 0x30
              WRITE_ASCIIE (fx_off +        (0x30 * (abil_fx_idx + index2))) ~%clone%~ #48
              WRITE_SHORT  (fx_off +        (0x30 * (abil_fx_idx + index2))) 177
              WRITE_LONG   (fx_off + 0x08 + (0x30 * (abil_fx_idx + index2))) 3 // from general.ids
              WRITE_ASCIIE (fx_off + 0x14 + (0x30 * (abil_fx_idx + index2))) ~cdca%duration%~ #8
            SET index2 += 1
            SET fx_delta += 1
            SET abil_fx_num += 1
          END
          PATCH_IF (icon1 = 1) BEGIN
            INSERT_BYTES (fx_off +        (0x30 * (abil_fx_idx + index2))) 0x30
              WRITE_ASCIIE (fx_off +        (0x30 * (abil_fx_idx + index2))) ~%clone%~ #48
              WRITE_SHORT  (fx_off +        (0x30 * (abil_fx_idx + index2))) 177
              WRITE_LONG   (fx_off + 0x08 + (0x30 * (abil_fx_idx + index2))) 3 // from general.ids
              WRITE_ASCIIE (fx_off + 0x14 + (0x30 * (abil_fx_idx + index2))) ~cdcb%duration%~ #8
            SET index2 += 1
            SET fx_delta += 1
            SET abil_fx_num += 1
          END
          PATCH_IF (sound0 = 1) BEGIN
            INSERT_BYTES (fx_off +        (0x30 * (abil_fx_idx + index2))) 0x30
              WRITE_ASCIIE (fx_off +        (0x30 * (abil_fx_idx + index2))) ~%clone%~ #48
              WRITE_SHORT  (fx_off +        (0x30 * (abil_fx_idx + index2))) 177
              WRITE_LONG   (fx_off + 0x08 + (0x30 * (abil_fx_idx + index2))) 3 // from general.ids
              WRITE_BYTE   (fx_off + 0x0c + (0x30 * (abil_fx_idx + index2))) 4 // timing: delay/permanent
              WRITE_ASCIIE (fx_off + 0x14 + (0x30 * (abil_fx_idx + index2))) ~cdcc%duration%~ #8
            SET index2 += 1
            SET fx_delta += 1
            SET abil_fx_num += 1
          END
          PATCH_IF (sound1 = 1) BEGIN
            INSERT_BYTES (fx_off +        (0x30 * (abil_fx_idx + index2))) 0x30
              WRITE_ASCIIE (fx_off +        (0x30 * (abil_fx_idx + index2))) ~%clone%~ #48
              WRITE_SHORT  (fx_off +        (0x30 * (abil_fx_idx + index2))) 177
              WRITE_LONG   (fx_off + 0x08 + (0x30 * (abil_fx_idx + index2))) 3 // from general.ids
              WRITE_BYTE   (fx_off + 0x0c + (0x30 * (abil_fx_idx + index2))) 4 // timing: delay/permanent
              WRITE_ASCIIE (fx_off + 0x14 + (0x30 * (abil_fx_idx + index2))) ~cdcd%duration%~ #8
            SET index2 += 1
            SET fx_delta += 1
            SET abil_fx_num += 1
          END
          PATCH_IF (sparklies = 1) BEGIN
            INSERT_BYTES (fx_off +        (0x30 * (abil_fx_idx + index2))) 0x30
              WRITE_ASCIIE (fx_off +        (0x30 * (abil_fx_idx + index2))) ~%clone%~ #48
              WRITE_SHORT  (fx_off +        (0x30 * (abil_fx_idx + index2))) 177
              WRITE_LONG   (fx_off + 0x08 + (0x30 * (abil_fx_idx + index2))) 3 // from general.ids
              WRITE_LONG   (fx_off + 0x0e + (0x30 * (abil_fx_idx + index2))) 4 // duration
              WRITE_ASCII  (fx_off + 0x14 + (0x30 * (abil_fx_idx + index2))) ~cdcvis~ #8
            SET index2 += 1
            SET fx_delta += 1
            SET abil_fx_num += 1
          END
        END // opcode = 5
      END // index2 for loop
    END // charm = 1
    WRITE_SHORT  (abil_off + 0x1e + (abil_length * index)) abil_fx_num
  END // index for loop
  BUT_ONLY