
STRING_SET
7 @1000007 //Haer'Dalis with capital D
10 @1000010 //hopefull->hopeful
41 @1000041 //Haer'dalis
84 @1000084 //Haer' Dalis
93 @1000093 //Haer' Dalis
96 @1000096 //Haer' Dalis
109 @1000109 //Haer' Dalis
118 @1000118 //Haer'Dalis with capital D
122 @1000122 //Haer' Dalis
123 @1000123 //Haer' Dalis
124 @1000124 //Haer' Dalis
125 @1000125 //Haer' Dalis
131 @1000131 //Haer'Dalis with capital D
132 @1000132 //Haer'Dalis with capital D
152 @1000152 //Haer'Dalis with capital D
161 @1000161 //Haer' Dalis
163 @1000163 //Haer'Dalis with capital D
172 @1000172 //Haer' Dalis->Haer'Dalis
176 @1000176 //THACO, thac0 should also be +3, not +2
199 @1000199 //THACO
225 @1000225 //Haer'Dalis with capital D
226 @1000226 //Haer'Dalis with capital D
257 @1000257 //Haer'Dalis with capital D
264 @1000264 //Haer' Dalis
282 @1000282 //Haer'Dalis with capital D
283 @1000283 //Haer'Dalis with capital D
287 @1000287 //Haer' Dalis
288 @1000288 //Haer' Dalis
292 @1000292 //riddence
337 @1000337 //"I have stated my wishes, not get lost!"->"I have stated my wishes, now get lost!"
354 @1000354 //"peasant, Pity him."->"peasant. Pity him."
375 @1000375 //sentence ended with a comma
468 @1000468 //o merchandise->o' merchandise
471 @1000471 //Bruiser Mate->Bruiser Mates
472 @1000472 //business man->businessman
619 @1000619 //THACO->THAC0
642 @1000642 // Twas -> 'Twas, "brain damaged" -> "brain-damaged"
643 @1000643 // Nasty sentence construction. "Then the knight had ridden off" -> "Then the knight rode off", Broke up second sentence with a comma.
644 @1000644 // "heard of his siblings demise" -> "heard of his sibling's demise"
645 @1000645 // "the orcs head" -> "the orc's head"
662 @1000662 // "ex brother-in-law" -> "ex-brother-in-law", griffin -> griffon
663 @1000663 // griffins -> griffons
666 @1000666 // "griffin baiter" -> "griffon-baiter", griffin's -> griffon's
676 @1000676 // "griffin baiter" -> "griffon-baiter"
695 @1000695 //seperates->separates, perogative->prerogative
718 @1000718 //elesewhere
725 @1000725 //"Rocksmash pack keep deal for stronger!"->"Rocksmash pack keep deal for Stronger!"
728 @1000728 //"If you are just the hired ruffiens, who put you up to it!"->"If you are just the hired ruffians, who put you up to it?!" 
729 @1000729 //"No Talk!"->"No talk!"
770 @1000770 //Roenal
847 @1000847 //Villynatny->Villynaty
856 @1000856 //mithril->mithral
857 @1000857 //"STATISTICS"->"STATISTICS:"
879 @1000879 //kuotoans->Kuo-toans
892 @1000892 //STATISTICS
988 @1000988 //Tis->'Tis
1072 @1001072 //Corellan->Corellon
1126 @1001126 //Haer'Dalis with capital D
1129 @1001129 //Haer'Dalis with capital D
1153 @1001153 //fools endeavor->fool's endeavor
1156 @1001156 //"Lets leave"->"Let's leave", "heavy hitters"->"heavy-hitters"
1202 @1001202 //push my nose into to other peoples'->push my nose into other peoples'
1287 @1001287 //its not->it's not
1300 @1001300 //that 200 paces from->than 200 paces from
1320 @1001320 //"your are"->"you are"
1340 @1001340 //Belgade->Belgrade
1362 @1001362 // Matching VO. "oh, I wish" -> "oh, how I wish"
1392 @1001392 //Haer'Dalis with capital D
1516 @1001516 //Excelent->Excellent
1610 @1001610 //"He hiding out somewere?"->"He's hiding out somewhere?"
1669 @1001669 //"You are obviously out of place, here, so"->"You are obviously out of place here, so"
1700 @1001700 //"I have a message for you, Miss Nalia from"->"I have a message for you, Miss Nalia, from"
1742 @1001742 //matching VO, I am->I'm
1787 @1001787 //Lord Roenal->Lord Roenall
1788 @1001788 //Lord Roenal->Lord Roenall
1789 @1001789 //Lord Roenal->Lord Roenall
1793 @1001793 //was wrest out->was wrested out
1819 @1001819 //first time said no->first time I said no
1822 @1001822 //Officer Roenal->Officer Roenall
1828 @1001828 //De'Arnise->de'Arnise
1831 @1001831 //Isaea Roenal->Isaea Roenall
1834 @1001834 //For give->Forgive
1874 @1001874 //Isaea Roenal->Isaea Roenall
1966 @1001966 //Yes but he told me->Yes, but he told me
2024 @1002024 //Tis->'Tis
2032 @1002032 //Tis->'Tis
2039 @1002039 //Athkata->Athkatla
2073 @1002073 //illuthium
2088 @1002088 //Neb's a gnome
2096 @1002096 //matching VO, without you adding->without adding
2141 @1002141 //Full Plate + 2 -> Full Plate +2, plat19
2208 @1002208 //Thank Baervar!->Oh, thank you, Baervan!, matches VO, "My... My hands..." -> "My hands..."
2296 @1002296 //"Catti Brie"->"Catti-Brie"
2298 @1002298 //"Catti Brie"->"Catti-Brie"
2309 @1002309 //STATISTICS
2372 @1002372 //"anti-negative plane energy"->"anti-negative-plane energy"
2416 @1002416 //life.There->life. There
2441 @1002441 //matching VO, Damn, you've all taken too long!->Damn, ye've all taken too long!
2454 @1002454 //matching VO, ".. it's a joke!" appended
2456 @1002456 //reknown->renown
2470 @1002470 //Its nay brutal->It's nay brutal
2475 @1002475 //"Yer indeed a dervish!"->"Ye're indeed a dervish!"
2477 @1002477 //matching VO, yer->your
2479 @1002479 //matching VO, whining->whinin', me->my
2486 @1002486 //matching VO, "It is a simple relationship"->"Is very simple relationship"
2487 @1002487 //"Yer at the beck and call of vermin?"->"Ye're at the beck and call of vermin?"
2490 @1002490 // Matching VO. "That's quite a fine" -> "That's a fine", "fiends" -> "friends"
2494 @1002494 //"When held in your hands it groans a little as if reluctant to allow a living thing to touch it."->"When held in your hands it groans a little, as if reluctant to allow a living thing to touch it.", succesful, speed is wrong
2498 @1002498 //matching VO, 'ere->here
2541 @1002541 //Korgan.Wait->Korgan. Wait
2571 @1002571 //tossin->tossin'
2580 @1002580 //Haer'dalis->Haer'Dalis
2581 @1002581 //Haer'dalis->Haer'Dalis
2595 @1002595 // Matching VO. "I never should have" -> "I should never have"
2638 @1002638 //matching VO, "the--the sun is"->"the sun is"
2639 @1002639 // "You don't talk much, do you." -> "You don't talk much, do you?"
2655 @1002655 //matching VO, "you failed your Test.  You...you are starting"->"you failed your Test, and... you... you're starting"
2681 @1002681 //"and label do not open 'til mid-winter fest!"->"and label 'Do not open 'til mid-winter fest'!"
2684 @1002684 //"scalds and bards"->"skalds and bards"
2716 @1002716 //matching VO, "all of this madness"->"all this madness"
2783 @1002783 //Barnard->Bernard
2904 @1002904 // Matching VO. "would grow" -> "could grow"
2916 @1002916 // "is it!" -> "is it!?"
2917 @1002917 //matching VO, ".. god knows!" appended
2918 @1002918 // Matching VO. "You're" -> "You are"
2921 @1002921 //matching VO, "Looka the sky, missy."->"Ha ha! Looka' the sky, missy."
2941 @1002941 // Matching VO. "I won't always be here" -> "I won't always be around"
2953 @1002953 //matching VO, "Stay away from me."->"Just--just stay away from me."
2965 @1002965 //mithril->mithral
2966 @1002966 //mithril->mithral
2967 @1002967 //provence->province
2969 @1002969 //"around him such as opening doors, disarming a trap, or opening a chest."->"around him, such as opening doors, or opening a chest."
2972 @1002972 //Imnevale->Imnesvale
2973 @1002973 //resue->rescue
2974 @1002974 //cam->came
3024 @1003024 //uless->unless
3031 @1003031 //Roenal->Roenall
3043 @1003043 //thaco
3058 @1003058 //matching VO, 3x"-ing"->"-in'"
3059 @1003059 //Twas->'Twas
3071 @1003071 // Full stop goes inside the parentheses. "arguments)." -> "arguments.)"
3083 @1003083 // Full stop moved in front of parenthetical sentence. "everything" -> "everything.", "four...)." -> "four...)"
3104 @1003104 // "cold.!" -> "cold!"
3151 @1003151 //matching VO, not been->never been
3171 @1003171 //matching VO, Boo->And Boo
3179 @1003179 //matching VO, "This land->Ahh... this land", "look some funny"->"look some kind of funny", "I tell you."->"I tell you this... ha ha!"
3212 @1003212 //matching VO, "Who wants some of Minsc"->"Who wants a piece of Minsc"
3215 @1003215 //Captital D in Haer'Dalis
3235 @1003235 //matching VO, "as I do"->"as Minsc does"
3247 @1003247 //"Minsc breaths"->"Minsc breathes", "There you are"->"Oh... there you are", matches VO
3250 @1003250 //Two Handed
3293 @1003293 // Matching VO. "too unhappy" -> "so unhappy"
3298 @1003298 //matching VO, "I am...I don't"->"I am... I am... I'd... hmm... I don't"
3330 @1003330 // "than just do it quietly" -> "then just do it quietly"
3419 @1003419 // Missing full stop.
3963 @1003963 //"20 foot radius"->"20-foot radius"
4350 @1004350 //"20 foot radius"->"20-foot radius"
4396 @1004396 // "shadow slain" -> "shadow-slain"
4413 @1004413 //overun->overrun
4428 @1004428 //matching VO, That is->That's
4438 @1004438 //augumented
4602 @1004602 //adds STATISTICS section to Star Dart
4866 @1004866 //"yer all such BIG men"->"ye're all such BIG men"
5139 @1005139 //"Die scum !"->"Die, scum!" (resisting urge to add "woof!")
5695 @1005695 //STATISTICS
5703 @1005703 //Tis->'Tis
5716 @1005716 //Tis->'Tis
5811 @1005811 //Roenal->Roenall
5823 @1005823 //"I was the one her prophecy spoken of"->"I was the one spoken of in her prophecy"
5831 @1005831 //Roenal->Roenall
6065 @1006065 //unnaffected
6070 @1006070 //"its best"->"it's best"
6071 @1006071 //"its best"->"it's best"
6074 @1006074 //tournequet->tourniquet
6077 @1006077 //"yer right"->"ye're right", "Its nay matter"->"It's nae matter"
6083 @1006083 //"badly- built"->"badly-built"
6088 @1006088 //"The priests strength"->"The priest's strength", thaco
6128 @1006128 //"tell me, then <GABBER>"->"tell me then, <GABBER>"
6135 @1006135 //Anomen: "strong sword"->"strong warrior"
6138 @1006138 //T'rahcie->T'rachie
6152 @1006152 //hearby->hereby
6157 @1006157 //"returns.Have"->"returns. Have"
6169 @1006169 //"Anomen: warrior priest of Torm"->"Anomen: warrior-priest of Helm"
6181 @1006181 //Anomen: "strong sword"->"strong warrior"
6187 @1006187 //matching VO, "played upon us!"->"played upon this company!"
6250 @1006250 //"Order of the Most Radiant Heart"->"Most Noble Order of the Radiant Heart"
6260 @1006260 //end sentence with a period
6273 @1006273 // "Don't worry, I still do it." -> "Don't worry, I'll still do it."
6284 @1006284 //end sentence with a period
6292 @1006292 //end sentence with a period
6310 @1006310 //stubborness
6312 @1006312 //"Get another step and fetch it"->"Get another step-and-fetch-it."
6322 @1006322 //curiousity->curiosity
6430 @1006430 //"distance South of here"->"distance south of here"
6432 @1006432 //"that that"->"than that"
6445 @1006445 //"your are"->"you are"
6449 @1006449 //Them Temple of Rillifane->The Temple of Rillifane
6460 @1006460 //evillyl->evilly
6467 @1006467 //fortold
6472 @1006472 // "You honor shall forever remain" -> "Your honor shall forever remain"
6486 @1006486 //thieves can normally use scimitars
6516 @1006516 //end sentence with a period
6519 @1006519 //"stump.(Head,"->"stump. (Head,"
6526 @1006526 //missing thac0 bonuses, +3 bonuses are against cold-using not cold/fire
6534 @1006534 //diappearance
6538 @1006538 //Roenal->Roenall
6618 @1006618 //FireBall->Fireball
6653 @1006653 //thaco
6699 @1006699 //"of the bottom"->"on the bottom", missle->missile
6716 @1006716 //"18 inches long.'"->"18 inches long."
6720 @1006720 //"Requires:3 Strength"
6731 @1006731 //high quality quarterstaves
6740 @1006740 //"Bastard Sword +1,+3 vs. Shapeshifters"->"Bastard Sword +1, +3 vs. Shapeshifters"
6751 @1006751 //Two Handed
6752 @1006752 //Two handed
6753 @1006753 //Two Handed
6862 @1006862 //thaco, "the staff is as high as the archer is"->"the staff is as long as the archer is tall"
6880 @1006880 //relevation->revelation
6935 @1006935 //matching VO, Hay->Hey
6939 @1006939 //"20 ' radius"->"20' radius", "first level spell"->"first-level spell"
6940 @1006940 //scroundrel
7015 @1007015 //Absorbtion
7030 @1007030 //matching VO, you are his superior->you are far his superior
7084 @1007084 //"but that attacked me"->"but then attacked me"
7236 @1007236 //William Reirric->William Reirrac
7255 @1007255 //succesfully
7341 @1007341 //thaco
7344 @1007344 //thaco
7345 @1007345 //thaco, didn't mention extra thac0 vs shapeshifters
7346 @1007346 //thaco
7347 @1007347 //"on the hills"->"in the hills", thaco, "Galloma died before Dramnek's tutorage could be completed however and the youth"->"Galloma died before Dramnek's tutorage could be completed, however, and the youth"
7348 @1007348 //"damage type piercing", thaco
7349 @1007349 //thaco
7352 @1007352 //thaco
7353 @1007353 //thaco
7375 @1007375 //STATISTICS, "Equipped Ability : increases movement rate"->"Equipped Ability: Increases movement rate"
7376 @1007376 //Boots of Stealth are not usable by bards and paladins
7381 @1007381 //thaco
7384 @1007384 //thaco
7385 @1007385 //thaco
7386 @1007386 //thaco
7394 @1007394 //single handedly
7400 @1007400 // "as your should be." -> "as you should be."
7430 @1007430 //arduos->arduous
7460 @1007460 //glamers->glamors
7461 @1007461 //babling
7469 @1007469 //2x "30 foot radius"->"30-foot radius"
7482 @1007482 //end sentence with a period
7490 @1007490 //"most Noble Order of the Radiant Heart"->"Most Noble Order of the Radiant Heart"
7496 @1007496 //end sentence with a period
7502 @1007502 //virtous
7508 @1007508 //plagarized
7532 @1007532 //"its member's conduct"->"its members' conduct"
7534 @1007534 // Matching VO. "no one would mourn" -> "none would mourn"
7549 @1007549 //matching VO, "Your words are strange."->"Your words are strange, wizard.", "Stand back."->"Er... stand back a step if you don't mind."
7553 @1007553 //reknown->renown
7555 @1007555 //matching VO, "The sewer-dwelling city weasel?"->"Perhaps, the sewer-dwelling city weasel?"
7557 @1007557 //"working girl rubbish"->"working-girl rubbish"
7559 @1007559 //matching VO, "Boo is patient, but this grows tiring. Keep pressuring and he may not just go for the eyes!"->"Boo is sensitive, and may not just go for the eyes!"
7564 @1007564 //"acid based attacks whether magical or non-magical such as"->"acid-based attacks, whether magical or non-magical, such as"
7572 @1007572 //"electrical based attacks whether magical or non-magical such as"->"electrical-based attacks, whether magical or non-magical, such as"
7597 @1007597 //"Prediction is a crapshoot"->"Prediction is a crapshot"
7599 @1007599 //"a protection from the Elements spell"->"a protection from the elements spell", "elemental attacks such as fire"->"elemental attacks, such as fire", "electricity whether magical or non magical such as"->"electricity, whether magical or non-magical, such as"
7601 @1007601 //"against all energy attacks such as fire, cold, acid, magic and electricity whether magical or non-magical such as"->"against all energy attacks, such as fire, cold, acid, magic and electricity, whether magical or non-magical, such as", blunt->crushing
7602 @1007602 //"my fathers home"->"my father's home"
7604 @1007604 // "your sister Anomen." -> "your sister, Anomen."
7611 @1007611 //"who is protected from normal weapons as well as anyone protected by"->"who is protected from normal weapons, nor on anyone protected by", "this spell with the short speed factor and duration it is"->"this spell, with the short speed factor and duration, it is"
7613 @1007613 //conjuction
7618 @1007618 //"is incredibly powerful hence the duration"->"is incredibly powerful, hence the duration", "also very short making"->"also very short, making"
7620 @1007620 //"also very short making this spell"->"also very short, making this spell"
7641 @1007641 //matching VO, "False friend!"->"You false friend!"
7642 @1007642 // "We are heading your home right now." -> "We are heading to your home right now."
7664 @1007664 //"30' radius cloud"->"30-feet-radius cloud", "while in the area of effect with a save"->"while in the area of effect, with a save"
7683 @1007683 //"Prelate Wesselan"->"Prelate Wessalen"
7746 @1007746 //matching VO, "The prodigal son returns. Heir"->"Well... heh heh heh... The prodigal son returns, heir", "How far have you roamed, son"->"Well, lemme ask you: how far have you roamed, son"
7776 @1007776 // "my sisters remains" -> "my sister's remains"
7777 @1007777 // "your are naught but a hindrance." -> "you are naught but a hindrance."
7782 @1007782 //whithin
7784 @1007784 //"10 foot radius"->"10-foot radius", "effects of blindness apply to the victims such as"->"effects of blindness apply to the victims, such as"
7788 @1007788 //thaco
7808 @1007808 //preportions->proportions
7818 @1007818 //"Sling +3 : 'Arla's Dragonbane'"->"Sling +3: 'Arla's Dragonbane'"
7837 @1007837 //"of of the town"->"of the town"
7848 @1007848 //forefeit
7870 @1007870 // "I am honor-bound to to find my sister's killer" -> "I am honor-bound to find my sister's killer"
7931 @1007931 //"magic based attacks such as magic missile or Abi Dalzim's"->"magic-based attacks, such as magic missile or Abi-Dalzim's"
7972 @1007972 // Matching VO. "situation." -> "regrettable situation."
7985 @1007985 //"Gloves of Pick Pocketing"->"Gloves of Pickpocketing"
8005 @1008005 // Matching VO. "I've been" -> "I have been"
8013 @1008013 //"The proof lies in that fact"->"The proof lies in the fact"
8047 @1008047 //"Order of the Most Radiant Heart"
8062 @1008062 //"8 hit dice monster"->"8-hit-dice monster", "casters control"->"caster's control"
8064 @1008064 //"Fifth and higher level spells"->"Fifth-and-higher-level spells"
8065 @1008065 //"into tiny pieces making it"->"into tiny pieces, making it"
8068 @1008068 //"Order of the Most Radiant Heart"
8087 @1008087 //rallys->rallies
8100 @1008100 //matching VO, "Since you seem intent on keeping me from my commitments, I will go alone."->"I shall set out on my own for the High Hall, since you seem intent on keeping me from my commitments!"
8127 @1008127 //un-named->unnamed
8134 @1008134 //"you who intrude"->"you who are intruding"
8171 @1008171 //unforgiveable->unforgivable
8172 @1008172 //unforgiveable->unforgivable
8211 @1008211 //penant->pennant
8242 @1008242 // "startling affect" -> "startling effect"
8368 @1008368 //Prelates decision->Prelate's decision
8373 @1008373 //Prelates decision->Prelate's decision
8408 @1008408 //pereseverance->perseverance
8462 @1008462 //to long->too long
8467 @1008467 //Paralization->Paralyzation
8486 @1008486 //STATISTICS, "In addition to the magical protection the shield radiates an aura"->"In addition to the magical protection, the shield radiates an aura"
8493 @1008493 //Two Handed, thaco
8499 @1008499 //matching VO, "You are a fine example of honor and chivalry."->"You are a fine example of honor and chivalry, and all in the Order look up to you."
8505 @1008505 //thaco, speed is wrong
8513 @1008513 //"but Radiant Heart accepts"->"but the Radiant Heart accepts"
8535 @1008535 //matching VO, "You are pathetic, Keldorn."->"Oh, you are pathetic, Keldorn.", " You are a hypocrite and a liar."->"You are a hypocrite and a liar. You care nothing for me, only for your honor."
8556 @1008556 // honey). -> honey.)
8571 @1008571 //"if'n yer gonna talk"->if'n ye're gonna talk"
8602 @1008602 // Mis-spaced colon. "I've a question for you :"If a tree falls" -> "I've a question for you: "If a tree falls"
8610 @1008610 //matching VO, "Valygar, you realize"->"Valygar, do you realize", "Mmmm, how can I be discreet?"->"Ha! How can I be discreet?"
8636 @1008636 // Missing punctuation. "no house just emptiness" -> "no house, just emptiness"
8650 @1008650 //matching VO, "my erotic onslaught"->"his erotic onslaught"
8653 @1008653 //darhir->darthiir
8656 @1008656 //matching VO, "Don't you Boo?"->"Don't you Boo? Don't you... yes!"
8673 @1008673 //desireable->desirable
8702 @1008702 // Matching VO. "It has been a long time since last I passed this way." -> "It has been a long time since I have passed this way."
8712 @1008712 //"spent with rivvil...the humans"->"spent with rivvin...the humans"
8725 @1008725 //krags->crags
8739 @1008739 // "I don't know why you to say that" -> "I don't know why you say that"
8740 @1008740 //"floundering on the field of battle."->"flounderin' on the field o' battle.", "Yer vassal"->"Ye're vassal"
8808 @1008808 //Tis->'Tis
8822 @1008822 //contempletive->contemplative, Torm->Helm
8904 @1008904 //thaco, "use this item on their own  Once the poison"->"use this item on their own.  Once the poison" 
8943 @1008943 //acquaintence->acquaintance
8944 @1008944 //happend
8952 @1008952 //want's to know->wants to know
8964 @1008964 //"woman who's husband ran off"->"woman whose husband ran off"
8974 @1008974 //develope->develop
9009 @1009009 // Matching VO. "it's bleeding so much!" -> "it hurts so much!"
9024 @1009024 //Lot's of guests
9027 @1009027 // "You're a man who looks like they" -> "You're a man who looks like he"
9031 @1009031 // servents -> servants
9058 @1009058 // "Why you think" -> "Why do you think"
9073 @1009073 // commiting -> committing
9088 @1009088 // Matching VO. "came out in the night." -> "come out in the night."
9097 @1009097 //extremeties
9113 @1009113 //matching VO, "adventure for weak-willed"->"adventure for the weak-willed"
9186 @1009186 //Haer'Dalis with capital D
9230 @1009230 //"mages fizzled scheme"->"mage's fizzled scheme"
9249 @1009249 //"one on one battles"->"one-on-one battles"
9253 @1009253 //"your are"->"you are"
9266 @1009266 //matching VO, "Sir William shall be hung and my love imprisoned."->"Sir William shall be hung and the love of my entire life imprisoned."
9362 @1009362 //Doppleganger->Doppelganger
9363 @1009363 //Doppleganger->Doppelganger
9381 @1009381 //Two Handed
9588 @1009588 //correction of proficiency descriptions
9616 @1009616 //matching VO, "Such bonding is frowned upon as it drains from the earth"->"Such bonding rituals are frowned upon as they draw energy from the earth itself"
9703 @1009703 //Roenal->Roenall
9710 @1009710 //"Some of us are reluctant accept affections."->"Some of us are reluctant to accept affections."
9735 @1009735 //"Those rivvil who"->"Those rivvin who"
9786 @1009786 //"it's song is a delight"->"its song is a delight"
9812 @1009812 //psychpathic 
10042 @1010042 //missle->missile
10043 @1010043 //thaco
10068 @1010068 //"Can not pick pocket hostile creatures"->"Can not pickpocket hostile creatures"
10185 @1010185 //Rasheman->Rashemen
10212 @1010212 //thaco
10704 @1010704 //matching VO, would see->should see, last sentence added
10715 @1010715 //"but Radiant Heart accepts"->"but the Radiant Heart accepts"
10716 @1010716 //than I->then I, glady
10727 @1010727 //matching VO, "agitation -- please"->"agitation and... please"
10770 @1010770 //matching VO, Sir William->Sir William of Thorpe
10851 @1010851 //"are stationary such as"->"are stationary, such as", "4th level spells"->"4th-level spells", "For example if"->"For example, if"
10854 @1010854 //privelege->privilege
10862 @1010862 //"are stationary such as"->"are stationary, such as", "7th level spells"->"7th-level spells", "For example if"->"For example, if"
10872 @1010872 //"This effects a total"->"This affects a total", "or 1 6th and"->"or 1 6th- and", "etc.."->"etc.", "are stationary such as"->"are stationary, such as", "For example if"->"For example, if"
10881 @1010881 //hiearchy
10889 @1010889 //"are stationary such as"->"are stationary, such as", "For example if"->"For example, if"
10911 @1010911 //scalliwag
10928 @1010928 //end sentence with a period
10977 @1010977 //"14th level priest"->"14th-level priest"
10985 @1010985 //"will either go berserk, stand confused or wander"->"will go berserk, stand confused or wander "
11003 @1011003 //privelege->privilege
11015 @1011015 //"effects that are stationary such as"->"effects that are stationary, such as", "For example if"->"For example, if", Shield of the Archons does not protect against dispel magic.
11054 @1011054 //thieves can use scimitars, single edged
11055 @1011055 //thaco
11057 @1011057 //thaco
11058 @1011058 //mithril->mithral
11059 @1011059 //mithril->mithral
11060 @1011060 //"How you"->"How can you", matches VO
11073 @1011073 //Haer'Dalis with capital D
11204 @1011204 //matching VO, "The scourge has been purged. The deed is done,"->"The scourge has been purged? I can tell that the deed is done,"
11305 @1011305 //indescretion->indiscretion
11352 @1011352 //selecion
11353 @1011353 //north east
11382 @1011382 //"Minsc get's eve"->"Minsc gets eve"
11536 @1011536 //"I had not though"->"I had not thought"
11686 @1011686 //provication->provocation
11850 @1011850 //everytime
11880 @1011880 //Roenal->Roenall
12029 @1012029 //Invulneribility->Invulnerability
12145 @1012145 //"This is the combat version of dispel magic, it will only affect opponents."->"This is the combat version of dispel magic, it will only affect opponents.", "certain magical items such as wands"->"certain magical items, such as wands", "Similarly if the caster"->"Similarly, if the caster"
12146 @1012146 //"Fourth and higher level spells"->"Fourth-and-higher-level spells"
12149 @1012149 //"hurled and projected missiles such as"->"hurled and projected missiles, such as", "magical missiles such as"->"magical missiles, such as"
12156 @1012156 //"3 HD monsters"->"3-HD monsters"
12157 @1012157 //"4 HD monsters"->"4-HD monsters"
12158 @1012158 //"5 HD monsters"->"5-HD monsters"
12163 @1012163 //"70 foot radius"->"70-foot radius"
12166 @1012166 //"will either go berserk, stand confused, or wander"->"will go berserk, stand confused or wander"
12168 @1012168 //"with one difference, there is no saving throw bonus"->"with one difference: there is no saving throw bonus"
12174 @1012174 //"At first-level"->"At first level", "At second-level"->"At second level", "At third-level"->"At third level", "At fourth-level"-"At fourth level", "At fifth-level"->"At fifth level", "At sixth-level"->"At sixth level"
12180 @1012180 //"first level spells"->"first-level spells"
12188 @1012188 //"30 foot cube"->"30-foot cube"
12190 @1012190 //"12th level caster"->"12th-level caster", "treated as temporary additional hit points"->"treated as temporary, additional hit points"
12193 @1012193 //"Area of Effect: 40' cube, 1 creature/level"->"Area of Effect: 40' cube" (not implemented), "it affects all ally creatures"->"it affects all allied creatures"
12196 @1012196 //speeded->hasted
12197 @1012197 //"then adds 50% bonus on top of this"->"then adds a 50% bonus on top of this", "If his strength is less then 18"->"If his strength is less than 18"
12202 @1012202 //etc..->etc.
12204 @1012204 //"recipients morale"->"recipients' morale"
12205 @1012205 //"20 ft radius"->"20-ft radius"
12212 @1012212 //casting time is 1 round, not 1 turn
12220 @1012220 //"30 foot radius"->"30-foot radius"
12221 @1012221 //"30 foot radius"->"30-foot radius"
12314 @1012314 //"giant sized animals"->"giant-sized animals"
12317 @1012317 //"flys out and hits"->"flies out and hits"
12320 @1012320 //"third level caster"->"third-level caster", "12th level caster"->"12th-level caster"
12651 @1012651 //Doppleganger->Doppelganger
13033 @1013033 //Invisibilty
13036 @1013036 //Invisibilty
13137 @1013137 //Calishite->Calimshite, soley
14234 @1014234 //"Order of the Most Radiant Heart"
14254 @1014254 //"casters inventory"->"caster's inventory", "if they are thrown at an enemy, a fireball will ensue causing"->"if they are thrown at an enemy, a fireball will ensue, causing"
14315 @1014315 //"an outer planar creature -- the Pit Fiend"->"an outer planar creature -- a Pit Fiend", demon->devil
14386 @1014386 //"By Lothander!"->"By Lathander!"
14471 @1014471 //"Yer nuthin' but a big liar!"->"Ye're nuthin' but a big liar!"
14492 @1014492 //"Yer bleedin' good"->"Ye're bleedin' good"
14523 @1014523 //Roenal->Roenall
14524 @1014524 //Roenal->Roenall
14556 @1014556 //"Yer just a little scrapper"->"Ye're just a little scrapper"
14831 @1014831 //"Hope yer not here to fight"->"Hope ye're not here to fight"
14924 @1014924 //Roenal->Roenall
15008 @1015008 //gardner
15044 @1015044 //"ye 're"->"ye're"
15063 @1015063 //coverse->converse
15159 @1015159 //"yer a sight fer old eyes"->"ye're a sight fer old eyes"
15181 @1015181 //"12 hit dice"->"12-hit-dice", "16 hit dice"->"16-hit-dice", "24 hit dice"->"24-hit-dice"
15193 @1015193 // Matching VO. " I can't carry any more. I'm sorry, I dropped something." -> " No, I can't carry any more. Oh, I'm sorry, I dropped something."
15212 @1015212 //"12 hit dice"->"12-hit-dice", "16 hit dice"->"16-hit-dice", "24 hit dice"->"24-hit-dice"
15253 @1015253 //"Yer a kind, kind shoul"->"Ye're a kind, kind shoul", "I shpose yer here"->"I shpose ye're here"
15264 @1015264 //"yer a cheapshkate"->"ye're a cheapshkate"
15327 @1015327 //ibleth->iblith
15401 @1015401 //Excelent->Excellent
15463 @1015463 //"Are you hear to"->"Are you here to"
15464 @1015464 //hear to->here to
15546 @1015546 //I know little <LADYLORD>->I know little, <LADYLORD>
15735 @1015735 //judgemental
15739 @1015739 //judgemental
15783 @1015783 //asylym
15803 @1015803 //pavillion->pavilion
15865 @1015865 //"wasting Arnolinus time!"->"wasting Arnolinus' time!"
15943 @1015943 //"scimitars, swords  even iron weapons"->" scimitars, swords, even iron weapons"
15959 @1015959 // dejemma -> dajemma
16020 @1016020 //missle->missile
16028 @1016028 //Roenal->Roenall, "meet the eye"->"meets the eye"
16108 @1016108 //"Yer a saint"->"Ye're a saint"
16150 @1016150 //outisde->outside
16288 @1016288 //thaco
16293 @1016293 //thaco
16297 @1016297 //thaco
16302 @1016302 //Togerias
16336 @1016336 //seperate->separate
16357 @1016357 //"yer a bleedin' coward"->"ye're a bleedin' coward"
16360 @1016360 //"Yer a goody-goody"->"Ye're a goody-goody"
16383 @1016383 //"I bleedin' coward amongst us!"->"A bleedin' coward amongst us!"
16415 @1016415 //"Yer th' best"->"Ye're th' best"
16669 @1016669 //Shauagin->Sahuagin
16841 @1016841 //"Some say its creatures made by magic"->"Some say it's creatures made by magic"
17061 @1017061 //asnwer->answer
17073 @1017073 //woudn't->wouldn't
17251 @1017251 //thaco
17283 @1017283 //funtion
17287 @1017287 //rangers and paladins can not use wands of fear
17348 @1017348 //desparate
17352 @1017352 //"outer planar creature"->"outer-planar creature", Pit Fiends are devils
17361 @1017361 //"7th level variant"->"7th-level variant"
17386 @1017386 //"simple looking blueberries"->"simple-looking blueberries", handfull
17458 @1017458 //"...as a druid sanction"->"...as a druid, sanction"
17487 @1017487 //"I get's ya."->"I gets ya."
17489 @1017489 //druids can use ankheg plate, succeptible
17490 @1017490 //thaco
17503 @1017503 //jem->gem
17523 @1017523 //chracter
17532 @1017532 //"rainbow coloured"->"rainbow-coloured", irridecent->iridescent
17534 @1017534 //thaco
17536 @1017536 //thaco
17541 @1017541 //thaco
17643 @1017643 //thaco, "the staff is as high as the archer is"->"the staff is as long as the archer is tall"
17647 @1017647 // Consistency with other spell descriptions. "Skull Trap (necromantic)" -> "Skull Trap (Necromancy)", "30 foot radius"->"30-foot radius"
17653 @1017653 //rangers and paladins can not use wands of paralysation
17654 @1017654 //rangers and paladins can not use wands of fire
17655 @1017655 //rangers and paladins can not use wands of ice, "White crystalline motes spray forth from the wand in a column towards the victim striking square in the chest with numbing force."->"White crystalline motes spray forth from the wand in a column towards the victim, striking square in the chest with numbing force."
17656 @1017656 //rangers and paladins can not use wands of lightning
17658 @1017658 //rangers and paladins can not use wands of polymorphing
17682 @1017682 //thaco
17683 @1017683 //thaco
17709 @1017709 //rangers and paladins can not use wands of cloudkill, "This wand emits a vapor bubble that travels towards the target exploding into a deadly cloud of noxious gas that expands to fill an area roughly 20 feet in radius."->"This wand emits a vapor bubble that travels towards the target, exploding into a deadly cloud of noxious gas that expands to fill an area roughly 20 feet in radius.", "Instant death no save"->"Instant death, no save"
17725 @1017725 // "benefactors hand" -> "benefactor's hand"
17738 @1017738 // crew'd -> crew
17749 @1017749 //"You must get our acorns back form Ilyich"->"You must get our acorns back from Ilyich"
17756 @1017756 //matching VO, "I be lookin' at ye, Anomen, and I be pleased that at least I be no hypocrite.  There nay a heart so holy the Devil nay make a nest of black twigs in it."->"At least I am no hypocrite, Anomen. There nay be a heart so holy that evil nay make a nest of black twigs in it."
17759 @1017759 //north east
17763 @1017763 //privledged->privileged
17770 @1017770 //"You must get our acorns back form Ilyich"->"You must get our acorns back from Ilyich"
17795 @1017795 // "What is this!" -> "What is this?"
17845 @1017845 //thaco
17859 @1017859 //missle->missile
17867 @1017867 //embider
17886 @1017886 //excersize->exercise
17953 @1017953 //consitution
18066 @1018066 //"standup to the Cowled Wizards for long"->"stand up to the Cowled Wizards for long"
18143 @1018143 //"9th level spell"->"9th-level spell", "back to this plane ending the spell"->"back to this plane, ending the spell", "Note a mazed creature"->"Note that a mazed creature"
18201 @1018201 //end sentence with a period
18205 @1018205 //ryme-rhyme
18405 @1018405 //matching VO, "Justice has been dispensed with your dispatchment of that wretched fool, Mae'Var!"->"Justice has been dispensed this day."
18414 @1018414 //recknoning->reckoning
18425 @1018425 //accquainted
18439 @1018439 //villified->vilified
18536 @1018536 //"and <PRO_HISHER> has proven it"->"and <PRO_HESHE> has proven it"
18560 @1018560 //"Like Drizzt and Wolfgar!"->" Like Drizzt and Wulfgar!"
18593 @1018593 //Selfish->Selfishness, hellself.cre
18610 @1018610 //Selfish->Selfishness, hellself.cre
18632 @1018632 // "she's a cute one, isn't she." -> "she's a cute one, isn't she?"
18735 @1018735 //mithril->mithral
18779 @1018779 //"it was just a word mispoke."->"it was just a word misspoken.
18805 @1018805 //asnwer->answer
18831 @1018831 //end sentence with a period
18832 @1018832 // Matching VO. "through difficult times" -> "through a very difficult time", "I turned my back on many of my brethren." -> "I have turned my back on many of my own brethren."
18923 @1018923 //thaco
18932 @1018932 //thaco
18933 @1018933 //thaco
18966 @1018966 //thaco
18973 @1018973 //thaco
18976 @1018976 //thaco
19034 @1019034 //rangers and paladins can not use wands of monster summoning
19043 @1019043 //rangers and paladins can not use wands of the heavens
19044 @1019044 //Two Handed, thaco
19045 @1019045 //Two Handed, thaco
19046 @1019046 //thaco
19353 @1019353 //thaco
19358 @1019358 //thaco
19359 @1019359 //thaco
19361 @1019361 //thaco
19363 @1019363 //thaco
19384 @1019384 //permissable->permissible
19402 @1019402 //despied->despised
19420 @1019420 //end sentence with a period
19427 @1019427 //decleration->declaration
19435 @1019435 //mathing VO, "Your voice is familiar"->"I...Your voice is familiar"
19464 @1019464 //"I've come to see the circus not some half-dressed tart"->"I've come to see the circus, not some half-dressed tart"
19469 @1019469 //"I've come to see the circus not some half-dressed tart"->"I've come to see the circus, not some half-dressed tart"
19490 @1019490 //"Yer all piles"->"Ye're all piles"
19505 @1019505 //seperate->separate
19522 @1019522 //matching VO, "Bloody forests.  Bloody"->"(mumble) Bloody forests. (mumble) Bloody"
19526 @1019526 //matching VO, "An' they think"->"(mumble) An' they think"
19538 @1019538 //"I've come to see the circus not some half-dressed tart"->"I've come to see the circus, not some half-dressed tart"
19546 @1019546 //"I've come to see the circus not some half-dressed tart"->"I've come to see the circus, not some half-dressed tart"
19608 @1019608 //"yer a kind one"->"ye're a kind one"
19610 @1019610 //"yer a hard, cold fiend"->"ye're a hard, cold fiend"
19634 @1019634 //"yer the bloke"->"ye're the bloke", "whose gone and"->"who's gone and"
19635 @1019635 //"yer the one whose gone an'"->"ye're the one who's gone an'"
19655 @1019655 //"Yer plain gold"->"Ye're plain gold"
19656 @1019656 // Matching VO, AKA Elminster doesn't follow his lines. "Ye have done what ye have done, the reasons for which are thine.  I trust they are valid...  This is my question, Jaheira: did ye do the right thing?" -> "Ye have done what ye have done, there is no denying, the reasons for which are thine and I trust they are valid, if ye believe them to be...  This is my question, Jaheira: did you do the right thing?"
19688 @1019688 //garrolous->garrulous
19766 @1019766 //end sentence with a period
19914 @1019914 //"yer in fer a world o' trouble"->"ye're in fer a world o' trouble"
19927 @1019927 //"yer a kind soul"->"ye're a kind soul"
19952 @1019952 //"yer a sodden piece o' ore"->"ye're a sodden piece o' ore"
20044 @1020044 // Matching VO. "I think it mostly" -> "I think it is mostly"
20053 @1020053 // Matching VO. "like one that truly believes his cause." -> "like one who truly believes his cause."
20070 @1020070 //adventursome->adventuresome
20085 @1020085 // whist -> whilst
20191 @1020191 //"well thought and calculated pIan"->"well-thought and calculated plan"
20219 @1020219 // Extra full stop removed. (Could be an ellipsis.)
20221 @1020221 //dischord
20228 @1020228 // "ahead o me!" -> "ahead o' me!"
20254 @1020254 // Jaheria -> Jaheira
20298 @1020298 //matching VO, "You're not what?"->"Hahaha... you're not what?"
20336 @1020336 //here me->hear me
20349 @1020349 // "for moment" -> "for a moment"
20351 @1020351 // absense -> absence
20359 @1020359 // "reminds you what" -> "reminds you of what"
20361 @1020361 //thaco
20363 @1020363 // "Alaundo's prophesies" -> "Alaundo's prophecies"
20485 @1020485 //Pretention
20502 @1020502 // "pressure do" -> "pressure to do"
20521 @1020521 //"Shall we be off."->"Shall we be off?"
20522 @1020522 //"Lets just get out of here."->"Let's just get out of here.", endevor -> endeavor
20525 @1020525 //2x"yer"->"ye're"
20533 @1020533 //Yes, lets do->Yes, let's do, valluables, have spaces before and after hyphen-stand-in-for-dash
20549 @1020549 //yer->ye're, resonable->reasonable
20669 @1020669 //Tis->'Tis
20817 @1020817 //matching VO, amongst->among
20833 @1020833 //matching VO, "What does that mean?  Shall we tear our own eyes out?"->"What... what does that mean? Shall we tear our own eyes out, then?"
20838 @1020838 //matching VO, "Bah!  What has your god ever done for me?"->"Bah! What has your god ever done for me, eh? Eh!?"
20863 @1020863 //matching VO, "They can also affect the rescue of your lass, or the capture of the mage, to boot."->"They can also affect the rescue of your lass, to boot."
20876 @1020876 //matching VO, "Maybe ye wants to find 'im?"->"Maybe ye's have a question or two. Maybe ye wants to find 'im?"
20943 @1020943 //order's headquarters->Order's headquarters
21003 @1021003 //Arledian->Arledrian
21008 @1021008 //Arledian->Arledrian
21029 @1021029 //"I see yer almost there"->"I see ye're almost there"
21142 @1021142 //"I though we had"->"I thought we had"
21303 @1021303 //mithril->mithral
21333 @1021333 // griffin -> griffon
21340 @1021340 // Matching VO. "need worry" -> "need to worry"
21366 @1021366 //"while yer at it"->"while ye're at it"
21421 @1021421 // Matching VO. "sky is darkened" -> "sky has darkened"
21491 @1021491 //"You find some happiness, perhaps, from the slaughter of a relative?"->"You find some happiness, perhaps, in the slaughter of a relative?", matches VO
21789 @1021789 //acheive->achieve
21820 @1021820 //destruction..
21822 @1021822 //matching VO, " Will you join the fold of the Unseeing Eye?"->"Have you decided to enter the holy fold of the Unseeing Eye?"
21868 @1021868 //matching VO, "It is a safe haven, as my friends below shall reiterate."->"It is a safe haven, and below there are friends of mine that will tend to your trading needs."
21944 @1021944 //everytime
21954 @1021954 //thaco
21981 @1021981 //two handed, thaco
22026 @1022026 //thaco, "Damage type:  Bludgeon"->"Damage type:  Crushing"
22115 @1022115 //instuctions->instructions
22263 @1022263 //thaco
22280 @1022280 // Missing word. "Mae'Var will hunt me until he I am dead!" -> "Mae'Var will hunt me until he knows I am dead!"
22379 @1022379 //Thayan->Thayvian
22386 @1022386 //yer->ye're
22515 @1022515 //"yer a no-good thief"->"ye're a no-good thief"
22516 @1022516 //replace inter-sentence quad-space with double-space
22609 @1022609 // "targets body" -> "target's body", "dexterity bonus'" -> "dexterity bonuses", "save vs. magical attacks"->"save vs. spell", "3rd level spell"->"3rd-level spell"
22611 @1022611 //"4th level spell"->"4th-level spell"
22615 @1022615 //"4th level priest spell"->"4th-level priest spell"
22617 @1022617 //"5 foot radius"->"5-foot radius"
22621 @1022621 //"electrical attack such as"->"electrical attacks, such as"
22663 @1022663 //"As pleasing as it is, even it would leave a welt"->"As pleasing as it is, it would leave a welt"
22708 @1022708 //Lot's of dainty collectors->Lots of dainty collectors
22712 @1022712 //thieves can use scimitars, "Where as the sabre was intented"->"Whereas the sabre was intended"
22808 @1022808 //traiterous->traitorous
22834 @1022834 //"9th level priest"->"9th-level priest"
22877 @1022877 //emnity->enmity
22945 @1022945 //Winspear
22972 @1022972 //"Not get moving."->"Now get moving."
23324 @1023324 //matching VO, "Boo will have your eyes when next we meet!"->"With our ties severed, I will be free to exact the proper justice! Boo will have your eyes when next we meet!"
23378 @1023378 //thieves can use scimitars, "enhanced magically to compliment the skill of the wielder."->"enhanced magically to complement the skill of the wielder.", thaco
23422 @1023422 //seperate->separate
23547 @1023547 //Roenal->Roenall
23561 @1023561 //judgemental->judgmental
24017 @1024017 // "whom have been perverted" -> "who have been perverted"
24202 @1024202 //Haer'Dalis with capital D
24204 @1024204 //Haer'Dalis with capital D
24213 @1024213 //Haerdalis->Haer'Dalis
24214 @1024214 //hear to do a job->here to do a job
24286 @1024286 //"Enter north of the palisade, though a secret door"->"Enter north of the palisade, through a secret door"
24347 @1024347 //you're buddy->your buddy
24354 @1024354 // "if it clear things up" -> "if it clears things up"
24423 @1024423 // Matching VO. "peoples" -> "people"
24435 @1024435 //Haer'Dalis with capital D
24447 @1024447 //Haer'Dalis with capital D
24450 @1024450 //Haer'Dalis with capital D
24462 @1024462 //"Do your return bearing?"->"Do you return bearing?"
24468 @1024468 //Haer'Dalis with capital D
24494 @1024494 //t'was->'twas
24573 @1024573 //Haer'Dalis with capital D
24576 @1024576 //dealing with his lessors->dealing with his lessers
24583 @1024583 //matching VO, "Injustice and indifference have always been the banes of our society.  and pose more of a danger to us than any dragon ever could."->"Injustice and indifference have always been the banes of our society. I often suspect that these sins pose more of a danger to us than any dragon ever could."
24612 @1024612 //end with period
24621 @1024621 //Haer'Dalis with capital D
24624 @1024624 //Haer'Dalis with capital D
24648 @1024648 //matching VO, amazing->amusing
24707 @1024707 //Roenal->Roenall
24708 @1024708 //His is well.->He is well.
24717 @1024717 //We serve stronger->We serve Stronger
24718 @1024718 //stronger->Stronger
24720 @1024720 //stronger->Stronger
24724 @1024724 //matching VO, "When we stop to rest, would you please"->"Would you please"
24761 @1024761 //high quality merchandise
24797 @1024797 //"a earth"->"an earth", "upon the elementals death"->"until the elemental's death", "will escape the instructions of the caster upon which it will go berserk attacking the mage"->"will escape the instructions of the caster, upon which it will go berserk, attacking the mage", "creatures psyche"->"creature's psyche", "At the end of this time if the caster has won he has control"->"At the end of this time, if the caster has won, he has control", "charm type spells cast afterwards"->"charm-type spells, cast afterwards"
24799 @1024799 //"upon the elemental's death"->"until the elemental's death", "will escape the instructions of the caster upon which it will go berserk attacking the mage"->"will escape the instructions of the caster, upon which it will go berserk, attacking the mage", "creatures psyche"->"creature's psyche", "At the end of this time if the caster has won he has control"->"At the end of this time, if the caster has won, he has control", "charm type spells cast afterwards"->"charm-type spells, cast afterwards"
24800 @1024800 //BioWare sucked. "casters every whim"->"caster's every whim", "upon the elementals death"->"until the elemental's death", "will escape the instructions of the caster upon which it will go berserk attacking the mage"->"will escape the instructions of the caster, upon which it will go berserk, attacking the mage", "creatures psyche"->"creature's psyche", "At the end of this time if the caster has won he has control"->"At the end of this time, if the caster has won, he has control", "charm type spells cast afterwards"->"charm-type spells, cast afterwards"
24838 @1024838 //"12 hit dice elemental"->"12-hit-dice elemental", ditto for 16 hit dice and 24 hit dice
24840 @1024840 //"12 hit dice elemental"->"12-hit-dice elemental", ditto for 16 hit dice and 24 hit dice
24842 @1024842 //"12 hit dice elemental"->"12-hit-dice elemental", ditto for 16 hit dice and 24 hit dice
24864 @1024864 //"homestead , away"->"homestead, away"
24872 @1024872 //"yer pretty bright"->"ye're pretty bright"
24910 @1024910 //compared sweet revenge->compared to sweet revenge
24993 @1024993 //lets->let's
25085 @1025085 // "tire or your musings." -> "tire of your musings.", add comma in front of "then"
25207 @1025207 //practicioners
25209 @1025209 //thaco
25306 @1025306 //"a devious controlling snake"->"a devious, controlling snake", "who's head"->"whose head"
25355 @1025355 //perveyor
25504 @1025504 //Who's estate->Whose estate
25515 @1025515 // "prepare to dealt righteous vengeance!" -> "prepare to be dealt righteous vengeance!"
25567 @1025567 //Lanulin->Ianulin
25603 @1025603 //"20th level priest"->"20th-level priest"
25616 @1025616 //"casters control"->"caster's control"
25623 @1025623 //"around the caster will be effected"->"around the caster will be affected"
25687 @1025687 //"who yer looking at"->"who ye're looking at"
25731 @1025731 //"go the tavern"->"go to the tavern"
25732 @1025732 //"yer a stranger"->"ye're a stranger"
25751 @1025751 //"swarms over a large area spreading"->"swarms over a large area, spreading", "fifth level counterpart"->"fifth-level counterpart"
25764 @1025764 //"between his god and the prime material plane causing"->"between his god and the prime material plane, causing"
25766 @1025766 //casting time is 1 round, not 1 turn, "5th level spell"->"5th-level spell"
25783 @1025783 //"and the purpose magic users is good"->"and the purpose of many magic users is good"
25872 @1025872 // Space. "Casting Time:3" -> "Casting Time: 3", "Therefor" -> "Therefore", Refected->Reflected
25876 @1025876 //Stoneskin does not protect the caster against physical magical attacks, not even "magic missle", "from the ground completely covering him"->"from the ground, completely covering him", "physical attacks such as"->"physical attacks, such as", "upon casting, for example a 10th level wizard"->"upon casting. For example, a 10th-level wizard", "20th level wizard"->"20th-level wizard", "10th level wizard"->"10th-level wizard", "magical attacks such as"->"magical attacks, such as"
25891 @1025891 //"book learning crap"->"book-learning crap"
25933 @1025933 //"perform any actions at all such as"->"perform any actions at all, such as", "destroys illusions such as"->"destroys illusions, such as"
25935 @1025935 //"creatures magic resistance"->"creature's magic resistance", "For example if this spell was cast by a 15th level wizard the target"->"For example, if this spell was cast by a 15th-level wizard, the target", "his current total reducing it"->"his current total, reducing it", "cancelling one 8th level or lower spell protection"->"cancelling one 8th-level-or-lower spell protection"
25936 @1025936 //Refected
25938 @1025938 //"third level wizard spell"->"third-level wizard spell"
25943 @1025943 //casting time is 1 round, not 1 turn, "is allowed up to 18th level or 6th level spells"->"is allowed, up to 18th level or 6th-level spells", "12th level wizard"->"12th-level wizard", "Then in combat once the wizard is"->"Then, in combat, once the wizard is", "Therefor"->"Therefore"
25945 @1025945 //"spells however it"->"spells, however, it", "Also if"->"Also, if", "illusions such as"->"illusions, such as"
25948 @1025948 //There is no "Spell Invulnerability"
25954 @1025954 //unconcious
25959 @1025959 //"too close to it.  At which point"->"too close to it, at which point"
25961 @1025961 //"multil colored rays"->"multi-colored rays"
25991 @1025991 //Lot's->Lots
26021 @1026021 //Lot's->Lots
26038 @1026038 //"Well, tannin alone would not have allowed me to act against a businessman"->"Well, that evidence alone would not have allowed me to act against a businessman" you can also arrive at this state by mentioning the elephant hide
26053 @1026053 // "Its that witch!" -> "It's that witch!"
26066 @1026066 //"light fingered one"->"light-fingered one", l->I (or maybe it's a 1 (one))
26071 @1026071 // "If every old crone were murderers" -> "If every old crone were a murderer"
26123 @1026123 //Nothin.->Nothin'.
26151 @1026151 //little currie chicken->little curried chicken
26156 @1026156 //unequivocably->unequivocally
26226 @1026226 //you paid for you time->you paid for your time
26242 @1026242 //"For example if this spell was cast by a 15th level wizard the target creature would lose 25% magic resistance from his current total reducing it to 0 if less than that remains as well"->"For example, if this spell was cast by a 15th-level wizard the target creature would lose 25% magic resistance from his current total, reducing it to 0 if less than that remains, as well"
26305 @1026305 //"(3rd level spell)"->"(3rd-level spell)", "The spell trap protects against 30 levels of protection"->"The spell trap provides 30 levels of protection", "(i.e., ten flame arrows or five finger's of death)"->"(e.g., ten flame arrows or five fingers of death)"
26315 @1026315 //There is no "Spell Invulnerability" spell
26330 @1026330 //casting time is 1 round, not 1 turn, "under certain conditions such as"->"under certain conditions, such as"
26342 @1026342 //"two handed weapon"->"two-handed weapon", end sentence with a period
26350 @1026350 //Lieutenent
26393 @1026393 //Feveran->Feveron
26395 @1026395 //Feveran->Feveron
26415 @1026415 //these man
26498 @1026498 //Completly
26540 @1026540 //matching VO, "Call me a fiend, will you?  I've never"->"Call me a fiend, will ya? Why, I've never"
26595 @1026595 //litte
26648 @1026648 //decendants
26784 @1026784 //confered->conferred
26793 @1026793 //stomache->stomach
26805 @1026805 // "if I have too." -> "if I have to."
26806 @1026806 //seak->seek
26815 @1026815 //dont'->don't
26839 @1026839 // "why must I tell their secrets." -> "why must I tell their secrets?"
26868 @1026868 // "give me a second too" -> "give me a second to"
26877 @1026877 //"lets just get moving"->"let's just get moving"
26908 @1026908 //matching VO, "So... could I... have"->"So... could I... could I have"
26913 @1026913 //incovenient
26943 @1026943 // Matching VO. "how did that" -> "how did the"
26958 @1026958 //matching VO, "Good morning, my child."->"Good morning, my lad."
26968 @1026968 //"spare him"->"spare <PRO_HIMHER>"
26975 @1026975 //deciedely
26993 @1026993 //"I tire of you ridiculous games"->"I tire of your ridiculous games"
27121 @1027121 //"I accuse you a crimes against Amn."->"I accuse you of crimes against Amn."
27170 @1027170 //"Back to you slime pit"->"Back to your slime pit"
27217 @1027217 // "I though you would" -> "I thought you would", "be mad I followed"->"be mad if I followed"
27223 @1027223 //dissention
27386 @1027386 // Missing full stop.
27387 @1027387 // Matching VO. "our sleep to the cycle of" -> "our sleep cycle to the"
27419 @1027419 // "his nature" -> "<PRO_HISHER> nature"
27464 @1027464 //glamer->glamor
27523 @1027523 // "there is it is." -> "there it is."
27546 @1027546 // reverant -> reverent
27551 @1027551 // mens' -> men's
27557 @1027557 // "If that is your wish, heretic, that I cannot promise your protection." -> "If that is your wish, heretic, then I cannot promise your protection."
27579 @1027579 // "I'm a sorry" -> "I'm sorry", havok->havoc
27606 @1027606 // unresposive -> unresponsive
27669 @1027669 //"yer pushin' about"->"ye're pushin' about"
27704 @1027704 // Aerie knows not whom she worships. "Baravar Cloakshadow" -> "Baervan Wildwanderer"
27709 @1027709 //replace inter-sentence quad-space with double-space
27721 @1027721 // Matching VO. "a long journey" -> "so long a journey"
27836 @1027836 //"Order of the Most Radiant Heart"
27841 @1027841 //"Order of the Most Radiant Heart"
27958 @1027958 //rivvil by the dozens->rivvin by the dozens
28036 @1028036 //"This prophet preyed on the people's need for security Can you not offer this?"->"This prophet preyed on the people's need for security. Can you not offer this?"
28044 @1028044 //"Order of the Most Radiant Heart"
28051 @1028051 //tresspass->trespass
28073 @1028073 //"Order of the Most Radiant Heart"
28081 @1028081 //Tis->'Tis
28130 @1028130 //pleasureable->pleasurable
28152 @1028152 //Morninglords'->Morninglord's
28180 @1028180 //deeply that I have
28200 @1028200 //trancends->transcends
28221 @1028221 //jalukl->jaluk
28290 @1028290 //I,,,I->I... I
28302 @1028302 //end last sentence with a period
28381 @1028381 //end sentence with a period
28404 @1028404 //Start sentence with capital letter
28434 @1028434 //"And what is it your wish of me?"->"And what is it you wish of me?"
28606 @1028606 //to long ago->too long ago
28607 @1028607 //"yer a kind one"->"ye're a kind one"
28633 @1028633 //Ilmatar->Ilmater
28634 @1028634 //Ilmatar->Ilmater
28692 @1028692 //"said so to you masters"->"said so to your masters"
28766 @1028766 //harsher types then you
28797 @1028797 //fix inconsistent quotation marks
28840 @1028840 //mithril->mithral
28954 @1028954 //"Order of the Most Radiant Heart"
28958 @1028958 //"Why must this Inn"->"Why must this inn"
28989 @1028989 //"the man is swine"->"the man is a swine"
29054 @1029054 //benificent->beneficent
29133 @1029133 //receeding
29208 @1029208 //conjurs
29212 @1029212 //"larger more vicious"->"larger, more vicious"
29214 @1029214 // "wizards control" -> "wizard's control", "a magical being of considerable power, the Nishruu"->"a magical being of considerable power: the Nishruu", "boiling churning"->"boiling, churning", "This is chosen at random, however, it will"->"This is chosen at random. However, it will"
29220 @1029220 //"6th level wizard spell"->"6th-level wizard spell", "a magical being of considerable power, the Hakeashar"->"a magical being of considerable power: the Hakeashar", "boiling churning"->"boiling, churning", "This is chosen at random, however it will"->"This is chosen at random. However, it will", "wizards control"->"wizard's control"
29221 @1029221 //"For example if"->"For example, if", "15th level mage"->"15th-level mage"
29243 @1029243 //"It demeans a god to walk with the flock, Just as if I supp'ed with insects."->"It demeans a god to walk with the flock, just as if I supped with insects."
29270 @1029270 //maically->magically
29324 @1029324 //greter->greater
29425 @1029425 //matching VO, ye->you
29431 @1029431 //matching VO, "And lo, the judgment of Beshaba has been called upon this most evil of drow! May the people see salvation in the Maid of Misrule! Pray she is merciful, foul one!"->"And lo, the judgment of Beshaba has been called upon this most evil of drow, and she has been found wanting! May the people see their salvation from your evil in the Maid of Misrule! Pray that she is merciful, foul one!"
29433 @1029433 //matching VO, "Hurrah!  Hurrah!!"->"Huzzah! Huzzah!!"
29466 @1029466 //The High Mornmaster of the Lathander
29503 @1029503 //concened->concerned
29527 @1029527 //incorrigable->incorrigible
29545 @1029545 //Tallassans->Talassans
29561 @1029561 //"But ' get the last word."->"But I get the last word."
29690 @1029690 //De'Arnise->de'Arnise
29694 @1029694 //Sythsillian->Sythillisian
29724 @1029724 //STATISTICS
29725 @1029725 //"A mind controlled creature"->"A mind-controlled creature"
29727 @1029727 //end sentence with a period
29783 @1029783 //matching VO, "but involve me in any filthy magic"->"but involve me with any filthy magic"
29902 @1029902 //matching VO, "Hey! That's not"->"Say... that's not"
29914 @1029914 //matching VO, "which that...er..."->"which that... uh... in a way..."
29922 @1029922 //matching VO, "Boo!!  BOO!!"->"Boo!! BOO!! That's awful! Terrible!"
30039 @1030039 //Sythsillian->Sythillisian
30172 @1030172 // Matching VO, heavy revision. "Tell my people you carry the piece so that you might deplete it, that you go to restore its components and dispose of it as a whole. My people must know I intend to destroy it... but more, they must know I intend to end their service." -> "Tell my people that you carry the piece that I give you, that you might deplete it, that you go to restore its components so that it may be disposed of as a whole, not in part. My people must know I intend to destroy it when you return... but more, they must know I intend to end their service."
30225 @1030225 //"Talos curse you for their shall be no services"->" Talos curse you for there shall be no services"
30227 @1030227 // "in a millennia!" -> "in millennia!"
30283 @1030283 //weakend
30560 @1030560 //lamanting->lamenting
30577 @1030577 //Yoshimo's garbled Japanese
30601 @1030601 //yout threat
30618 @1030618 //end sentence with a period
30625 @1030625 //wihin
30628 @1030628 //"I will lead with gently certainty"->"I will lead with gentle certainty"
30635 @1030635 // Lieutenants Aegisfield-> Lieutenant Aegisfield
30677 @1030677 //simplist->simplest
30709 @1030709 //matching VO, "I'm busy."->"I'm busy, okay? I'm busy!"
30760 @1030760 //Lets get going->Let's get going
30834 @1030834 //Riativin
30835 @1030835 //Riativin->Riatavin
30837 @1030837 //Riativin->Riatavin
30839 @1030839 //Atkatla->Athkatla
30875 @1030875 //racoon
30889 @1030889 //plently
30947 @1030947 //Riativin->Riatavin
30949 @1030949 //Haer'Dalis with capital D
30962 @1030962 //start sentence with capital letter
30969 @1030969 //Haer'Dalis with capital D
30996 @1030996 //Haer'Dalis with capital D, Faenya-dail
31007 @1031007 //Haer'Dalis with capital D
31009 @1031009 //Haer'Dalis with capital D
31014 @1031014 //Haer'Dalis with capital D
31049 @1031049 // Faenya-dail -> Faenya-Dail
31053 @1031053 // Faenya-dail -> Faenya-Dail
31077 @1031077 // "None of us has" -> "None of us have"
31095 @1031095 //Riativin->Riatavin
31100 @1031100 //Riativin->Riatavin
31101 @1031101 //embargos
31102 @1031102 //Riativin->Riatavin
31108 @1031108 //Riativin->Riatavin
31109 @1031109 //Riativin->Riatavin
31117 @1031117 //two handed sword
31135 @1031135 //two handed weapon
31142 @1031142 //Riativin->Riatavin
31145 @1031145 // Mis-splaced exclamation mark. "outposts !" -> "outposts!"
31146 @1031146 //Tethtyr->Tethyr
31147 @1031147 //Riativin->Riatavin
31149 @1031149 // Matching VO. "I...need" -> "I...I need"
31185 @1031185 //matching VO, "I...I have been thinking, and...y-you are right."->"I have been thinking, and you are right."
31200 @1031200 //Haer'Dalis with capital D
31204 @1031204 //Haer'Dalis with capital D
31211 @1031211 //Haer'Dalis with capital D
31220 @1031220 //brethern
31222 @1031222 //Haer'Dalis with capital D
31238 @1031238 //Haer'Dalis with capital D
31241 @1031241 //Sythsillian->Sythillisian
31245 @1031245 //Riativin->Riatavin
31249 @1031249 //Haer'Dalis with capital D
31251 @1031251 //Haer'Dalis with capital D
31254 @1031254 //Haer'Dalis with capital D
31261 @1031261 //Haer'Dalis with capital D
31264 @1031264 //Haer'Dalis with capital D
31280 @1031280 //Haer'Dalis with capital D
31289 @1031289 //Haer'Dalis with capital D
31291 @1031291 //Haer'Dalis with capital D
31294 @1031294 //Haer'Dalis with capital D
31295 @1031295 //Haer'Dalis with capital D
31296 @1031296 //Haer'Dalis with capital D
31302 @1031302 //Haer'Dalis with capital D
31303 @1031303 //Haer'Dalis with capital D
31308 @1031308 //Haer'Dalis with capital D
31317 @1031317 //Haer'Dalis with capital D
31322 @1031322 //Haer'Dalis with capital D
31325 @1031325 //Haer'Dalis with capital D
31328 @1031328 // "It is I who love you" -> "It is I who loves you
31329 @1031329 //Haer'Dalis with capital D
31334 @1031334 //Haer'Dalis with capital D
31345 @1031345 // Haer'Dalis with capital D, "than you are not" -> "then you are not"
31380 @1031380 //Haer'Dalis with capital D
31400 @1031400 //Baldurs Gate->Baldur's Gate
31408 @1031408 //Riativin->Riatavin
31421 @1031421 //Riativin->Riatavin
31422 @1031422 //Riativin->Riatavin
31423 @1031423 //Riativin->Riatavin
31427 @1031427 //Riativin->Riatavin
31430 @1031430 //Riativin->Riatavin, "gold mining Lurraxols"->"gold-mining Lurraxols"
31431 @1031431 //Riativin->Riatavin
31434 @1031434 //Riativin->Riatavin, arrrives->arrives
31442 @1031442 //Riativin->Riatavin
31447 @1031447 //Riativin->Riatavin
31449 @1031449 //Riativin->Riatavin
31462 @1031462 //Riativin->Riatavin
31463 @1031463 //Riativin->Riatavin, Gateweay->Gateway
31486 @1031486 //Sythsillian->Sythillisian
31487 @1031487 //Sythsillian->Sythillisian
31502 @1031502 //Sythsillian->Sythillisian
31521 @1031521 //wraught
31549 @1031549 //Esmeltran->Esmeltaran, Sythsiallians->Sythillisians
31559 @1031559 //forsee
31562 @1031562 //Esmeltran->Esmeltaran
31588 @1031588 //Miativin->Riatavin
31592 @1031592 //"form liberating"->"from liberating", seperates->separates
31607 @1031607 //matching VO, "that you wish to rest.  I...wish"->"that you wish to rest, but I... I wish"
31608 @1031608 //Riativin->Riatavin
31630 @1031630 //Riativin->Riatavin
31697 @1031697 // Restored VO. [AERIEB1]
31733 @1031733 // familar -> familiar
31743 @1031743 //matching VO, "Aerie...this bard"->"Aerie, this... this bard"
31745 @1031745 //Haer'Dalis with capital D
31748 @1031748 //shadow thieves->Shadow Thieves
31753 @1031753 // "hope barely neigh" -> "hope barely nigh"
31762 @1031762 //Haer'Dalis with capital D
31766 @1031766 //Haer'Dalis with capital D
31773 @1031773 //Haer'Dalis with capital D
31780 @1031780 //Haer'Dalis with capital D
31784 @1031784 //forsee
31787 @1031787 //Haer'Dalis with capital D
31794 @1031794 //Haer'Dalis with capital D
31799 @1031799 //Haer'Dalis with capital D
31865 @1031865 //Vapiricus
31873 @1031873 //"I will have it seeded it with"->"I will have it seeded with"
31885 @1031885 // Matching VO. "I've... I've just" -> "I've just... I've just"
31887 @1031887 //Haer'Dalis with capital D
31889 @1031889 //matching VO, "False friend! I shall go to my father without you! I am loath to think that I have leant my hand to your cause..."->"False friend! I am loath to think that I have lent my hand to your cause. I shall go to my father without you!"
31893 @1031893 //Haer'Dalis with capital D
31896 @1031896 //Haer'Dalis with capital D
31901 @1031901 //matching VO, "No effect? I need a bigger sword!"->"No effect? I need bigger sword!"
31906 @1031906 //mithril->mithral
31950 @1031950 //scroundrel
31976 @1031976 // Matching VO. "I...I assure you" -> "I assure you"
32119 @1032119 //damage correction for High Mastery
32120 @1032120 //damage and speed factor correction for Grand Mastery
32128 @1032128 //thaco
32136 @1032136 //STATISTICS
32138 @1032138 //STATISTICS
32143 @1032143 //thaco
32145 @1032145 //Balhifet, thaco, thac0 and damage are noted as additional
32182 @1032182 //Balhifet, thaco
32186 @1032186 //Defender of Easthaven is +3 and not +2
32187 @1032187 //commerate->commemorate, bonuses to hit and damage are wrong, Balhifet->Belhifet, thaco
32194 @1032194 //STATISTICS, Two Handed
32196 @1032196 //Balhifet
32336 @1032336 //burglaring->burgling
32358 @1032358 //"Yer a mighty respectible sort"->"Ye're a mighty respectable sort"
32410 @1032410 //"This creates a telepathic link between the caster and the undead allowing complete control."->"This creates a telepathic link between the caster and the undead, allowing complete control."
32421 @1032421 // liekly -> likely
32425 @1032425 // "The next rogues is Goshan" -> "The next rogue is Goshan"
32440 @1032440 //clientelle->clientele
32455 @1032455 // becuase -> because
32457 @1032457 //wast->waste
32482 @1032482 //pedestians->pedestrians
32492 @1032492 //witnessess->witnesses
32502 @1032502 //crouds
32526 @1032526 //guidlines->guidelines
32527 @1032527 //guidlines->guidelines
32586 @1032586 //embarrasing->embarrassing
32622 @1032622 //"that a five-hundred year-old witch is on the prowl."->"that a five-hundred-year-old witch is on the prowl."
32673 @1032673 //"This will be a relatively difficult set of circumstance for her to overcome."->"This will be a relatively difficult set of circumstances for her to overcome."
32674 @1032674 //same as 1032673
32687 @1032687 // "5 days has elapsed" -> "5 days have elapsed"
32756 @1032756 //mithril->mithral
32766 @1032766 //Then She will->Then she will
32798 @1032798 //mithril->mithral
32799 @1032799 //"yer talkin' about"->"ye're talkin' about"
32845 @1032845 //amout->amount
32892 @1032892 //"So, you be men new boss then?"->"So, you be me new boss then?"
32901 @1032901 //your's->yours
32914 @1032914 //currenlty
32919 @1032919 //"There is not other guild that compares."->"There is no other guild that compares."
32925 @1032925 //eanything->anything
32947 @1032947 //know's->knows
32953 @1032953 //"Things are a little slow tight now"->"Things are a little slow right now"
32964 @1032964 //"yer up to no good"->"ye're up to no good"
32969 @1032969 //Palying->Playing
33002 @1033002 //protocal
33010 @1033010 //palasade->palisade
33023 @1033023 //suddeness
33059 @1033059 //"These terrors I am loathe to discuss"->"These terrors I am loath to discuss"
33064 @1033064 //halfing
33112 @1033112 //Ill->I'll
33114 @1033114 //"Maybe it'll be me whose eating you."->"Maybe it'll be me who's eating you."
33115 @1033115 //"There is nowhere to run to now my prey."->"There is nowhere to run to now, my prey."
33117 @1033117 //"Think again.  I'll have digested your heart by days end."->"Think again.  I'll have digested your heart by day's end."
33269 @1033269 //start sentence with capital letter
33281 @1033281 // Sythsillian->Sythillisian, "How do expect" -> "How do you expect"
33315 @1033315 // "So you're band is no better off then" -> "So your band is no better off than"
33365 @1033365 // "None is worthy" -> "None are worthy"
33372 @1033372 //"will go, now, to rejoin"->" will go now, to rejoin"
33375 @1033375 //mithril->mithral
33377 @1033377 //mithril->mithral
33378 @1033378 //mithril->mithral
33572 @1033572 //"Be careful, its hot!"->"Be careful, it's hot!"
33755 @1033755 //viscious->vicious
33822 @1033822 // "Yer not gonna" -> "Ye're not gonna"
33829 @1033829 // "while yer sleepin'" -> "while ye're sleepin'"
33834 @1033834 // "yer a peach" -> "ye're a peach"
33850 @1033850 //t'were->'twere
33893 @1033893 //thaco
33925 @1033925 //"are disappearing ...only to be reappear" -> "are disappearing ...only to reappear"
33929 @1033929 //"Order of the Most Radiant Heart"
33939 @1033939 //no -one->no-one
33950 @1033950 //independant
33959 @1033959 //Sythsillian->Sythillisian
33966 @1033966 //mithril->mithral
33971 @1033971 //Liliith Lurraxol->Lilith Lurraxol
33976 @1033976 //Sythsillian->Sythillisian
33977 @1033977 //braggards->braggarts
34014 @1034014 //"Order of the Most Radiant Heart"
34072 @1034072 //"I have friends among the order."->"I have friends among the Order."
34080 @1034080 //genuinly
34085 @1034085 //Jeirdan->Jierdan
34090 @1034090 //Two Handed
34096 @1034096 //"distance South of here"->"distance south of here"
34117 @1034117 //asumptions->assumptions
34146 @1034146 //two handed sword
34149 @1034149 //varities
34150 @1034150 //"two handed", "single handed", "counter balances", "muscle bound warrior"
34151 @1034151 //"These weapons are hard to find Outside of Kara-Tur"->"These weapons are hard to find outside of Kara-Tur"
34152 @1034152 //Wakazashi
34164 @1034164 //"and in the hands of a skilled user just as deadly"->"and, in the hands of a skilled user, just as deadly"
34171 @1034171 //you get the critical hit bonus with the first pip, "two handed"->"two-handed", "single handed"->"single-handed"
34173 @1034173 //one handed
34174 @1034174 //one handed
34192 @1034192 //ursurped
34202 @1034202 //inexpereinced->inexperienced
34232 @1034232 //Mae'var->Mae'Var
34271 @1034271 //sulik->solik
34338 @1034338 //north east
34370 @1034370 //"Me bad."->"My bad."
34440 @1034440 // Added 'and'. "Do a task for me I shall heal the damage" -> "Do a task for me and I shall heal the damage"
34533 @1034533 //matching VO, "this was home"->"this was my home"
34593 @1034593 //Nishru->Nishruu
34609 @1034609 //Efreet->Efreeti
34622 @1034622 //Abi Dalzim->Abi-Dalzim
34646 @1034646 //Invunerability
34662 @1034662 //"Order of the Most Radiant Heart"
34664 @1034664 //"Order of the Most Radiant Heart"
34665 @1034665 //"Order of the Most Radiant Heart"
34714 @1034714 //missle->missile
34719 @1034719 //"lead me to to it"->"lead me to it"
34806 @1034806 //obstinant->obstinate
34872 @1034872 //setaling->stealing
34874 @1034874 //"operations.He"->"operations. He"
34902 @1034902 //"of miy like a pro"->"of my like a pro", maybe "of mine" instead?
34919 @1034919 //chieftans->chieftains
34941 @1034941 //probally->probably
34953 @1034953 // "Than I would thank you" -> "Then I would thank you"
34955 @1034955 //priveledge->privilege
35096 @1035096 //expell->expel
35120 @1035120 // seperate -> separate
35131 @1035131 // seperate -> separate
35143 @1035143 //"than I shall"->"then I shall"
35183 @1035183 // Matching VO. "I...I wish to apologize" -> "I...I do wish to apologize"
35185 @1035185 // yourelf -> yourself
35211 @1035211 // "I would go to to free her." -> "I would go to free her."
35266 @1035266 //Most Radiant Heart
35408 @1035408 // confidant -> confident
35415 @1035415 // "I do thank you humbly for your council." -> "I do thank you humbly for your counsel."
35443 @1035443 //"I am not discussing Sarevok with you, Anomen...nor of my activities in the Sword Coast."->"I am not discussing Sarevok with you, Anomen... nor my activities in the Sword Coast."
35449 @1035449 //bely->belie
35469 @1035469 //hesistant
35470 @1035470 //"I am almost loathe to ask."->"I am almost loath to ask."
35537 @1035537 //pleasureable->pleasurable
35594 @1035594 //supsceptible->susceptible
35596 @1035596 //matching VO, Sir Ryan Trawl->Sir Cadril
35604 @1035604 //"life energy level"->"life-energy level", "life energy level drain"->"life-energy-level drain", "any form of insanity such as"->"any form of insanity, such as"
35626 @1035626 //epecially
35658 @1035658 //"between his god and the prime material plane causing"->"between his god and the prime material plane, causing"
35660 @1035660 //trangressions
35675 @1035675 //"Nowhere does it mention Talos the 'They are Happy Now!!' No, I really do not think you understand the edicts of the Talos faith!"->"Nowhere did Talos mention this 'They are Happy Now!!' No, I really do not think you understand the edicts of the Talassan faith!"
35694 @1035694 //cooporative
35714 @1035714 //matching VO, "I am still a little bitter"->"I am still a bit bitter"
35725 @1035725 //"it wasn't self defence"->"it wasn't self-defense"
35736 @1035736 //witnessess->witnesses
35760 @1035760 // Matching VO. "That is good." -> "Well, that is good."
35766 @1035766 //thaco
35791 @1035791 //thaco, "has come describe"->"has come to describe"
35792 @1035792 //priveledged->privileged
35827 @1035827 // "I shall be free to complement you" -> "I shall be free to compliment you"
35843 @1035843 //"led you as a mantis her prey!"->"led you as a mantis does her prey!"
35847 @1035847 //"vampires foul heart"->"vampire's foul heart"
35880 @1035880 // Matching VO. "I have never" -> "I never have"
35931 @1035931 //perfomance
35950 @1035950 //"I though you"->"I thought you"
35953 @1035953 //trangressions
35962 @1035962 //perfomance
35986 @1035986 //trangressions
35994 @1035994 //"In who's estimation"->"In whose estimation"
36012 @1036012 //adherance->adherence
36016 @1036016 //occurence
36022 @1036022 // "there are many things that went through my head." -> "there were many things that went through my head."
36086 @1036086 // Matching VO. "you'll not be seeing me bow before any altars!" -> "you'll not see me bowing before any altars!"
36168 @1036168 //taudry->tawdry
36181 @1036181 //STATISTICS
36188 @1036188 //warrent->warrant
36283 @1036283 //"She longs for our destruction as have give the order."->"She longs for our destruction, and she has given the order."
36301 @1036301 //lauch
36338 @1036338 //Two Handed
36350 @1036350 // "take vengeance of the merchant" -> "take vengeance on the merchant"
36353 @1036353 //"Order of the Most Radiant Heart"
36384 @1036384 //Tallasans
36460 @1036460 //thaco
36466 @1036466 //"Feel the wrath of the arachnids, of the divine eight legged!"->"Feel the wrath of the arachnids, of the divine eight-legged!"
36549 @1036549 //desparate
36550 @1036550 //"mistresses ear"->"mistress' ear"
36576 @1036576 //Baalor->Balor
36641 @1036641 //posession
36646 @1036646 //alter->altar
36664 @1036664 //Baalor->Balor
36665 @1036665 //alter->altar
36666 @1036666 //thaco
36669 @1036669 //Baalor->Balor
36676 @1036676 //alter->altar
36678 @1036678 //thaco
36759 @1036759 //"Order of the Most Radiant Heart"
36766 @1036766 //forgoe
36767 @1036767 //fotune
36770 @1036770 //achievments->achievements
36778 @1036778 //"did not wish to join the order"->"did not wish to join the Order"
36798 @1036798 //order->Order
36810 @1036810 //order->Order
36827 @1036827 //appology->apology
36871 @1036871 //order->Order
36879 @1036879 //order->Order
36890 @1036890 //order->Order
36894 @1036894 //order->Order
36896 @1036896 //order->Order
36948 @1036948 //ta'anari->tanar'ri
36959 @1036959 //ta'anari->tanar'ri
36977 @1036977 //order->Order
36988 @1036988 //Imnesvail
37085 @1037085 //"Order of the Most Radiant Heart"
37089 @1037089 //sqautters->squatters
37090 @1037090 //metting
37093 @1037093 //hesistant->hesitant
37121 @1037121 //"Order of the Most Radiant Heart"
37145 @1037145 //"Order of the Most Radiant Heart"
37153 @1037153 //"you carefull place the arms and legs in your pack"->"you carefully place the arms and legs in your pack"
37172 @1037172 // Matching VO. "He...he's" -> "He's...he's"
37225 @1037225 //"Noble Order of the Most Radiant Heart"->"Most Noble Order of the Radiant Heart"
37249 @1037249 //matching VO, "this is the planar sphere here."->"this is the planar sphere here in the slums."
37276 @1037276 //stanger
37290 @1037290 //matching VO, "I...I am most grateful.  If...if you could"->"I... am most grateful. If... you could"
37291 @1037291 //"less then I expected"->"less than I expected", matches VO
37372 @1037372 //orcrs->orcs
37382 @1037382 //Derbert->Dirbert
37383 @1037383 //"yer an adventurer"->"ye're an adventurer"
37386 @1037386 // neath -> 'neath
37395 @1037395 //Enroute
37404 @1037404 //Haer'Dalis with capital D
37416 @1037416 //sancticity->sanctity
37447 @1037447 //"The mandate of your loyal order is deception and ruse, so misery is just another disguise for your gang of holy thugs agenda is my guess."->"The mandate of your loyal order is deception and ruse, so misery is just another disguise for your gang of holy thugs' agenda is my guess."
37457 @1037457 //"a number of The Baron's guards"->"a number of the Baron's guards"
37547 @1037547 //T'il->'Til
37606 @1037606 //order->Order
37610 @1037610 //order->Order
37634 @1037634 //order->Order
37643 @1037643 //"but I had  duty to fulfill"->"but I had a duty to fulfill"
37649 @1037649 //Matrich, agenst
37669 @1037669 //"Now just calm down and well straighten this all out."->"Now just calm down and we'll straighten this all out."
37672 @1037672 //prefered
37698 @1037698 //beligerant->belligerent
37710 @1037710 //beligerant->belligerent
37722 @1037722 //"responsible !"->"responsible!"
37736 @1037736 // Matching VO. "have the half of" -> "have half of"
37763 @1037763 //immediatly
37880 @1037880 //Order..->Order.
37915 @1037915 //"yer not gonna make me work"->"ye're not gonna make me work"
37918 @1037918 //"Yer welcome"->"Ye're welcome"
37919 @1037919 //"Izzat why yer whisperin' there"->"Izzat why ye're whisperin' there"
37930 @1037930 //mithril->mithral
37931 @1037931 //"yer gettin' mighty portly"->"ye're gettin' mighty portly"
37947 @1037947 //"yer selling those books"->"ye're selling those books"
37968 @1037968 //"Yer one o' the friends"->"Ye're one o' the friends"
37970 @1037970 //"yer findin' our village to yer likin'"->"ye're findin' our village to yer likin'"
37982 @1037982 //"Yer doin' a fine job"->"Ye're doin' a fine job", "anythin' yer needin' help with"->"anythin' ye're needin' help with"
37995 @1037995 //mithril->mithral
38012 @1038012 //mithril->mithral
38017 @1038017 //"yer no longer welcome here"->"ye're no longer welcome here"
38101 @1038101 //mithril->mithral
38182 @1038182 //order->Order
38194 @1038194 //order->Order
38215 @1038215 //obstinant->obstinate
38218 @1038218 //obstinant->obstinate
38268 @1038268 //start sentence with capital letter
38280 @1038280 //mithril->mithral
38281 @1038281 //mithril->mithral
38420 @1038420 //mithril->mithral
38422 @1038422 //mithril->mithral
38428 @1038428 //mithril->mithral
38430 @1038430 //replace inter-sentence quad-space with double-space
38464 @1038464 //mithril->mithral
38466 @1038466 //mithril->mithral
38527 @1038527 //"Knights of the Most Radiant Heart"->"Knights of the Most Noble Order of the Radiant Heart"
38546 @1038546 //"our arrangement wil be fulfilled"->"our arrangement will be fulfilled"
38567 @1038567 //"Cloak of Fear(Conjuration)"->"Cloak of Fear (Conjuration)"
38570 @1038570 //"30-foot radius sphere"->"30-foot-radius sphere", "bright reddish light"->"bright, reddish light"
38572 @1038572 //The duration of the effects of Dolorous Decay are better described as "Special"
38574 @1038574 //"6th-level or greater spells"->"6th-level-or-greater spells"
38608 @1038608 //thaco
38695 @1038695 //"we should ge going"->"we should get going"
38727 @1038727 //Glaicas->Glaicus
38728 @1038728 //Glaicas->Glaicus
38751 @1038751 //brethern
38855 @1038855 //"yer sweet t' say so"->"ye're sweet t' say so"
38882 @1038882 //accquired->acquired
38919 @1038919 //"Only their self-determination will such rabble amount to anything"->"Only with self-determination will such rabble amount to anything"
38977 @1038977 //"yer gonna run outta wall"->"ye're gonna run outta wall"
39004 @1039004 //t'was
39005 @1039005 //"yer around Aran"->"ye're around Aran", "more then a few"->"more than a few"
39010 @1039010 //"Yer plannin' on usin' the courses"->"Ye're plannin' on usin' the courses"
39039 @1039039 //"yer here to"->"ye're here to"
39040 @1039040 //"in case yer messin' with him"->"in case ye're messin' with him"
39042 @1039042 //"yer wondering just what"->"ye're wondering just what"
39058 @1039058 //"distraction when yer trainin'"->"distraction when ye're trainin'"
39083 @1039083 //T'would->'Twould
39086 @1039086 //"My lungs burned as a fought to stay conscious"->"My lungs burned as I fought to stay conscious""
39111 @1039111 //"Well, yer goin' to have t' clean"->"Well, ye're goin' to have t' clean"
39149 @1039149 //pratically
39180 @1039180 //"If yer plannin' this trip"->"If ye're plannin' this trip"
39242 @1039242 //Everaska->Evereska
39310 @1039310 //"who's pocket"->"whose pocket"
39311 @1039311 //"attempt to Pick Pocket a gem"->"attempt to Pickpocket a gem"
39312 @1039312 //"Left-Click on the person you want to Pick Pocket."->"Left-Click on the person you want to Pickpocket."
39436 @1039436 //nasea
39443 @1039443 //"elven made"->"elven-made", clarify the fact the hammer does a total of 11 additional damage to giantkin
39444 @1039444 //Thac0->THAC0
39449 @1039449 //thaco, "Short Sword + 1"->"Short Sword +1"
39450 @1039450 //thaco
39451 @1039451 //thaco
39452 @1039452 //thaco
39453 @1039453 //thaco
39454 @1039454 //thaco
39455 @1039455 //thaco
39456 @1039456 //thaco
39457 @1039457 //thaco
39458 @1039458 //thaco
39459 @1039459 //thaco, "who accepted dubious service at court throughout Faerun"->"who accepted dubious service at courts throughout Faerun"
39460 @1039460 //thaco
39461 @1039461 //thaco, damage is wrong
39462 @1039462 //thieves can use long swords, thaco
39463 @1039463 //thaco
39465 @1039465 //STATISTICS
39466 @1039466 //wakishasi, STATISTICS
39467 @1039467 //STATISTICS
39468 @1039468 //wakishasi, STATISTICS
39469 @1039469 //thieves can use scimitars, "STATISTICS"->"STATISTICS:"
39470 @1039470 //Two Handed, "STATISTICS"->"STATISTICS:"
39471 @1039471 //Two Handed, "STATISTICS"->"STATISTICS:"
39472 @1039472 //Two Handed, "STATISTICS"->"STATISTICS:"
39473 @1039473 //Two Handed, "STATISTICS"->"STATISTICS:"
39474 @1039474 //Two Handed
39475 @1039475 //STATISTICS
39476 @1039476 //STATISTICS, " When a victim is struck they are, as one would guess, very nearly impaled, run through as the massive enchantment does its dirty work."->" When a victim is struck they are, as one would guess, very nearly impaled: run through as the massive enchantment does its dirty work."
39477 @1039477 //STATISTICS, "electrum plated shaft"->"electrum-plated shaft"
39478 @1039478 //thaco
39479 @1039479 //STATISTICS, thaco
39480 @1039480 //thaco
39481 @1039481 //STATISTICS, thaco
39508 @1039508 //thaco
39510 @1039510 //thaco
39511 @1039511 //thaco, speed and weight are wrong
39512 @1039512 //thaco
39513 @1039513 //thaco, thac0 correction
39515 @1039515 //thaco
39516 @1039516 //thaco
39517 @1039517 //thaco, "long dead faith"->"long-dead faith"
39519 @1039519 //thaco, "Sling +3 : 'Arla's Dragonbane'"->Sling +3: 'Arla's Dragonbane'"
39520 @1039520 //thaco
39521 @1039521 //thaco
39522 @1039522 //thaco
39523 @1039523 //thaco
39524 @1039524 //STATISTICS
39525 @1039525 //STATISTICS
39526 @1039526 //STATISTICS
39527 @1039527 //thaco, "well to do family"->"well-to-do family"
39528 @1039528 //thaco
39529 @1039529 //two handed, thaco
39530 @1039530 //thaco
39533 @1039533 //thaco
39538 @1039538 //thieves can not use plate armour
39549 @1039549 // griffin -> griffon
39562 @1039562 //"seldom is this armor be found" -> "seldom is this armor found"
39566 @1039566 //STATISTICS
39570 @1039570 //STATISTICS
39571 @1039571 //STATISTICS
39599 @1039599 //STATISTICS, "lowly ranked Red Mage"->"lowly-ranked Red Mage"
39600 @1039600 //STATISTICS
39601 @1039601 //STATISTICS, "lock picking abilities"->"lock-picking abilities"
39602 @1039602 //STATISTICS
39606 @1039606 //STATISTICS
39607 @1039607 //STATISTICS, "Gloves of Pick Pocketing", "A few years back Fong Moo a famous cutpurse, known in"->"A few years back Fong Moo, a famous cutpurse, known in", "good at pick pocketing", "Pick Pocketing:  +20% Bonus"
39608 @1039608 //STATISTICS
39609 @1039609 //STATISTICS
39610 @1039610 //STATISTICS
39611 @1039611 //STATISTICS, "KP, or Kaligun Poonil was the general"->"KP, or Kaligun Poonil, was the general"
39612 @1039612 //STATISTICS, "wear this particle periapt"->"wear this particular periapt"
39613 @1039613 //STATISTICS
39614 @1039614 //STATISTICS
39615 @1039615 //STATISTICS
39616 @1039616 //STATISTICS
39617 @1039617 //STATISTICS
39619 @1039619 //thaco
39620 @1039620 //STATISTICS "life giving effects"->"life-giving effects"
39621 @1039621 //Thac0 and STATISTICS
39622 @1039622 //STATISTICS, Thac0, "he or she were a flesh eating demon"->""he or she were a flesh-eating demon""
39624 @1039624 //thaco
39625 @1039625 //STATISTICS
39626 @1039626 //bards can not use the staff of curing, "STATISTICS"->"STATISTICS:", speed is wrong
39627 @1039627 //STATISTICS and some whitespace
39628 @1039628 //STATISTICS
39629 @1039629 //thaco, speed is wrong
39630 @1039630 //STATISTICS
39631 @1039631 //STATISTICS
39632 @1039632 //STATISTICS
39633 @1039633 //STATISTICS, "Drawing from the Plane of Fire it can erupt in"->"Drawing from the Plane of Fire, it can erupt in"
39634 @1039634 //thaco, speed is wrong
39635 @1039635 //thaco
39636 @1039636 //thaco
39637 @1039637 //STATISTICS
39638 @1039638 //STATISTICS, "rock throwing contest"
39639 @1039639 //STATISTICS, "the belt greatly increases the wearer's strength making them as strong"->"the belt greatly increases the wearer's strength, making them as strong"
39640 @1039640 //STATISTICS
39641 @1039641 //STATISTICS, "has this sword has been"->"has this sword been", "Abi Dalzim"->"Abi-Dalzim"
39645 @1039645 //STATISTICS
39646 @1039646 //STATISTICS
39647 @1039647 //STATISTICS
39648 @1039648 //STATISTICS
39649 @1039649 //STATISTICS
39654 @1039654 //STATISTICS, "is a perfect replication, in miniature of a lion"->"is a perfect replication, in miniature, of a lion"
39656 @1039656 //STATISTICS, mis-spaced full stop. "called Kitthix ." -> "called Kitthix.", "use it's Web" -> "use its Web"
39658 @1039658 //STATISTICS
39660 @1039660 //fifth level warrior
39661 @1039661 //seventh level warrior
39662 @1039662 //ninth level warrior
39665 @1039665 //STATISTICS, "The most common use of the Horn of Silence is a weapon"->"The most common use of the Horn of Silence is as a weapon"
39669 @1039669 //STATISTICS, "All creatures, other than the bard and his/her party must"->" All creatures, other than the bard and his/her party, must"
39671 @1039671 //STATISTICS, "an courtyard", "man eating sharks", "well known citizens", "shark filled pool"
39672 @1039672 //STATISTICS
39679 @1039679 //thaco
39714 @1039714 //STATISTICS
39716 @1039716 //STATISTICS (for SoA)
39751 @1039751 //"north west"->northwest
39763 @1039763 //matching VO, "If that is what you wish. I will wait outside by the palisade. It will be safer than waiting here."->"If that is what you wish... it will be safer than waiting here. I will wait outside by the palisade."
39764 @1039764 //STATISTICS
39791 @1039791 //pallisade->palisade
39822 @1039822 //pallisade->palisade
39831 @1039831 //"reknown for their cruelty"->"renowned for their cruelty"
39843 @1039843 //pallisade->palisade
39955 @1039955 //STATISTICS
39959 @1039959 //replace inter-word multi-space with single-space
40034 @1040034 //Roenal->Roenall
40056 @1040056 //moraly
40087 @1040087 //end sentence with a period
40104 @1040104 //"Order of the Most Radiant Heart"
40116 @1040116 //rememeber
40117 @1040117 //rememeber
40187 @1040187 //matching VO, "This is far worse than if the Roenalls had taken over!"->"This is far worse than if the Roenalls had taken over the keep!"
40188 @1040188 //matching VO, "You... you can't just kill someone!"->"You can't just kill someone!"
40232 @1040232 //weasely
40288 @1040288 //carvan
40289 @1040289 //carvan
40418 @1040418 //begiinning->beginning
40441 @1040441 //preposturous->preposterous
40531 @1040531 //preposturous->preposterous
40545 @1040545 //"its the witch"->"it's the witch"
40634 @1040634 //STATISTICS, "This Figurine of Wondrous Power that calls forth from the ether"->"This Figurine of Wondrous Power calls forth from the ether"
40641 @1040641 //Baalor->Balor
40689 @1040689 //"The Amn Council has"->"The Amnish Council has"
40888 @1040888 //Llira->Lliira
40906 @1040906 //cutsie->cutesy
40931 @1040931 //"yer one of the folks"->"ye're one of the folks"
40948 @1040948 //"yer that <CHARNAME>"->"ye're that <CHARNAME>"
40962 @1040962 //waste my time of this idiotic plan
40977 @1040977 //annoint
41065 @1041065 //"join the the thieves"->"join the thieves"
41145 @1041145 //heresay
41190 @1041190 //"think its the curse"->"think it's the curse"
41204 @1041204 //"And my style is my own, do not be so petty."->" And my style is my own, do not be so petty."
41333 @1041333 //"something a simple"->"something as simple"
41354 @1041354 //end sentence with a period
41355 @1041355 //end sentence with a period
41356 @1041356 //end sentence with a period
41369 @1041369 //"your days a starving actor"->"your days as a starving actor"
41432 @1041432 //invloved
41458 @1041458 //Shavanana->Shvanana
41462 @1041462 //rivven->rivvin
41611 @1041611 //"We open our play in the land of Turmish"->"We open our play in the Turmish land"
41680 @1041680 //"We open our play in the land of Turmish"->"We open our play in the Turmish land"
41733 @1041733 //assignent->assignment
41740 @1041740 //"I saw we try our hand at"->"I say we try our hand at"
41789 @1041789 //Appreti->Apprenti
41829 @1041829 //Ther's->There's
41844 @1041844 //"Abi Dalzim"->"Abi-Dalzim"
41950 @1041950 //STATISTICS
41965 @1041965 //streching
41966 @1041966 //wil be worth it
42043 @1042043 //Aslaer->Azlaer
42166 @1042166 //Balmittance->Balmitance
42238 @1042238 //thay->they
42278 @1042278 //tuteledge->tutelage
42284 @1042284 //Solamninc->Solamnic
42291 @1042291 // becuase -> because
42327 @1042327 //carefull->careful
42337 @1042337 //"he continues magic use will be"->"he continues magic-use will be", excecutions
42515 @1042515 //presumptious->presumptuous
42763 @1042763 //matching VO, "You seek Imoen, your lost comrade, and Irenicus, the one who would give you power.  I am prepared to give you their location, and the means with which to reach them."->"You seek Imoen, your lost comrade. I am prepared to give you her location, and the means with which to reach her."
42777 @1042777 //there were circumstance that you
42779 @1042779 //reqested->requested
42794 @1042794 //Sythsillian->Sythillisian
42820 @1042820 //"yer just going t' be washed away"->"ye're just going t' be washed away"
42838 @1042838 //interrogat->interrogate
42840 @1042840 //Sythsillian->Sythillisian
42845 @1042845 //Sythsillian->Sythillisian
42847 @1042847 //won't'->won't
42854 @1042854 //"strong willed"->"strong-willed"
42888 @1042888 //towns troubles
42892 @1042892 //retrieveing->retrieving
42931 @1042931 //soflty
42941 @1042941 //"proved to unruly"->"proved too unruly"
42985 @1042985 // "What kind of people are you!" -> "What kind of people are you!?"
42987 @1042987 // "I hope it you choke on it." -> "I hope you choke on it."
42991 @1042991 //"before I tire your toes in a knot"->"before I tie your toes in a knot"
43058 @1043058 //retrieveing->retrieving
43161 @1043161 //transgession->transgression
43343 @1043343 //"Yer in league"->"Ye're in league"
43344 @1043344 //"yer th' folk responsible"->"ye're th' folk responsible", "yer in league"->"ye're in league"
43345 @1043345 //"Yer in league"->"Ye're in league", "Yer what's sicced 'em beasties"->"Ye're what's sicced 'em beasties"
43348 @1043348 //"Mayhap ye'll speak to Guildmistress Busya if he wants to do somethin' about that."->"Mayhap ye'll speak to Guildmistress Busya if ye wants to do somethin' about that."
43412 @1043412 // "being doing here" -> "be doing here"
43418 @1043418 //"being doing here" -> "be doing here"
43480 @1043480 //matching VO, "What can the Dao"->"Tell me, what can the Dao"
43592 @1043592 //rukh->ruhk
43606 @1043606 //"hording all the food"->"hoarding all the food"
43623 @1043623 //horde our very food
43634 @1043634 //STATISTICS
43652 @1043652 //Llira->Lliira
43657 @1043657 //subserviant->subservient
43837 @1043837 //Skarbaen->Skarmaen
43839 @1043839 // Comma. "You come, <MANWOMAN> bearing the bones" -> "You come, <MANWOMAN>, bearing the bones"
43854 @1043854 // Comma. "You come, <MANWOMAN> bearing the bones" -> "You come, <MANWOMAN>, bearing the bones"
43863 @1043863 //presense->presence
43878 @1043878 //STATISTICS
43895 @1043895 //Ther->There
44050 @1044050 //"pay for you help"->"pay for your help"
44116 @1044116 //"Where is Imoen!"->"Where is Imoen?!"
44201 @1044201 //STATISTICS
44206 @1044206 //co-ordinator->Coordinator
44207 @1044207 //matching VO, "He rules all! He does! You! You are to be but the left bunion of his wondrous idol! You! Be grateful for the chance!"->"He rules all, he does! You?! You are but the left bunion of his wondrous idol! You be grateful for the chance!"
44282 @1044282 //"me trade is a might constricted"->"me trade is a mite constricted"
44300 @1044300 // "they're lives are in danger." -> "their lives are in danger."
44391 @1044391 //Llira->Lliira
44394 @1044394 //Sythsillian->Sythillisian
44406 @1044406 //Sythsillian->Sythillisian
44436 @1044436 //"Yer gonna pay"->"Ye're gonna pay"
44439 @1044439 //"Yer those people"->"Ye're those people"
44594 @1044594 //"walled off section of town"->"walled-off section of town"
44597 @1044597 //"walled off section of town"->"walled-off section of town"
44615 @1044615 //"It's... it's body"->"Its... its body"
44620 @1044620 //cooporation->co-operation
44696 @1044696 //everytime
44701 @1044701 //succesfully
44772 @1044772 //"Yer a fool"->"Ye're a fool"
44850 @1044850 // "you breath air!" -> "you breathe air!"
44895 @1044895 // Matching VO / question marks.
44923 @1044923 //satifaction->satisfaction
44924 @1044924 //hestitation
44943 @1044943 //Iron Skins does not protect the druid against "magic missle", "from the ground completely covering her"->"from the ground, completely covering her", "10th level druid"->"10th-level druid", "10th level druid"->"10th-level druid"
45061 @1045061 //accomodate->accommodate
45071 @1045071 //De'Arnise->de'Arnise
45081 @1045081 //prefered->preferred
45203 @1045203 //Shaundakar->Shaundakul
45333 @1045333 //"Got's me an appointment"->"Gots me an appointment"
45339 @1045339 //fightin->fightin'
45443 @1045443 //"If you ever seem them again"->"If you ever see them again"
45449 @1045449 //did't->didn't
45565 @1045565 //"tough question, yer askin'"->"tough question ye're askin'"
45664 @1045664 //"The sea gates are steadfast locked until it is blown"->"The sea gates are steadfastly locked until it is blown."
45760 @1045760 //"They I wish"->"Then I wish"
45763 @1045763 //"thieves war"->"thieves' war"
45827 @1045827 //"think yer buying my whole"->"think ye're buying my whole"
45840 @1045840 // "Who's blasted job" -> "Whose blasted job"
45882 @1045882 //"it's location"->"its location"
45898 @1045898 //matching VO, "Oh hell. I'll be below deck securing the... ah... something."->"Aw hell. Uh... I-I'll be below deck securing the... um... s-something, ah..."
45970 @1045970 //replace inter-sentence quad-space with double-space
46016 @1046016 //adds VO
46020 @1046020 //"What it is worth?"->"What is it worth?"
46021 @1046021 //adds VO
46031 @1046031 //anyting
46107 @1046107 //"Well, sported, sir. I shall have the Desharik apprised of the results."->"Well sported, sir. I shall have Desharik apprised of the results."
46120 @1046120 //Lanulin->Ianulin
46163 @1046163 //"Arnise certain kept"->"Arnise certainly kept"
46213 @1046213 //Roenal->Roenall
46225 @1046225 //"on the group in future"->"on the group in the future"
46237 @1046237 //De'Arnise->de'Arnise
46241 @1046241 //liason
46261 @1046261 //Roenal->Roenall
46262 @1046262 //Roenal->Roenall
46272 @1046272 //Roenal->Roenall
46292 @1046292 //scryed->scried
46293 @1046293 //prophesized->prophesied
46295 @1046295 //Roenal->Roenall
46299 @1046299 //"We are called the Sea Devils and the Anguiliians"->"We are called the Sea Devils and our eel-kin the Anguiliians"
46383 @1046383 //"What does that scoundrel pay you to do!"->"What does that scoundrel pay you to do?!"
46391 @1046391 //Releived->Relieved
46399 @1046399 //scrumpcious->scrumptious
46417 @1046417 //perserverence->perserverance
46430 @1046430 //speciman->specimen
46442 @1046442 //prophecized->prophesied
46576 @1046576 //prophecized->prophesied
46580 @1046580 //prophecized->prophesied
46657 @1046657 //Admantine
46665 @1046665 //thieves can use scimitars, single edged
46667 @1046667 //thieves can use scimitars, single edged, "STATISTICS"->"STATISTICS:"
46706 @1046706 //thieves can use light crossbows, thaco
46710 @1046710 //Piwafwi->Piwawfi
46712 @1046712 //STATISTICS
46718 @1046718 //thaco
46720 @1046720 //thaco
46722 @1046722 //thaco
46754 @1046754 //Sakolah->Sekolah
46760 @1046760 //prophecized->prophesied
46851 @1046851 //Master of Thralls dwarven slave
46867 @1046867 //end sentence with period
46889 @1046889 //thieves can use scimitars
46912 @1046912 //Tis->'Tis
46918 @1046918 //paraphenelia->paraphernalia
46924 @1046924 //"alchemists poisons"->"alchemists' poisons"
46945 @1046945 //"Trademeets mercantile enterprises"->"Trademeet's mercantile enterprises"
47016 @1047016 //Imnsevale->Imnesvale
47030 @1047030 //Sythsillian->Sythillisian
47115 @1047115 //"reknown around Faerun"->"renowned around Faerun"
47124 @1047124 //mischevious->mischievous
47127 @1047127 //high quality pair
47131 @1047131 //STATISTICS, speed and weight wrong
47141 @1047141 //Winspear->Windspear
47158 @1047158 // Cemetary -> Cemetery
47159 @1047159 // cemetary -> cemetery
47209 @1047209 //"tiny rivvin like yourself"->"tiny rivvil like yourself"
47262 @1047262 //eviller->eviler
47263 @1047263 //its horde was mine
47361 @1047361 //independant->independent
47382 @1047382 //"I would be careful with that sharp tone, rivvin, lest you lose the tongue that shapes it."->"I would be careful with that sharp tone, rivvil, lest you lose the tongue that shapes it."
47393 @1047393 //"yer all the same"->"ye're all the same"
47401 @1047401 //"yer an elf"->"ye're an elf"
47434 @1047434 //threathening
47451 @1047451 //"Yer a traitorous"->"Ye're a traitorous"
47482 @1047482 //"things to do that court your arrogant pride"->"things to do than court your arrogant pride"
47485 @1047485 //Alateto->Alatelo
47493 @1047493 //failling->failing
47496 @1047496 //wailling->wailing
47497 @1047497 //ryhme
47512 @1047512 //STATISTICS
47545 @1047545 //"although I did it without the evidence that Renal needed and without his."->"although I did it without the evidence that Renal needed and without his approval."
47578 @1047578 //inadvertantly->inadvertently
47721 @1047721 //illilthium->illithium, neb's a gnome
47760 @1047760 //presense->presence
47762 @1047762 //mithril->mithral
47766 @1047766 //mithril->mithral
47767 @1047767 //mithril->mithral
47911 @1047911 //wisdome->wisdom
47919 @1047919 //desireable->desirable 
47950 @1047950 //hazzard->hazard
47959 @1047959 //procede
47986 @1047986 // believeable -> believable
47987 @1047987 //garrolous->garrulous
47988 @1047988 //leant->lent
47991 @1047991 //garrolous->garrulous
48013 @1048013 //adultress, replace inter-sentence quint-space with double-space
48095 @1048095 //Twas->'Twas
48100 @1048100 //"I hate fish. I fishing"->"I hate fish. I hate fishing"
48134 @1048134 //"pay for our fathers 'crime'."->"pay for our father's 'crime'."
48163 @1048163 //"Ulgoth'd Beard"->"Ulgoth's Beard"
48194 @1048194 //"unless yer foolish"->"unless ye're foolish"
48233 @1048233 //"There passage is assured"->"Their passage is assured"
48265 @1048265 //matching VO, "Are we to separate on this note?"->"Well... are we to separate on this note?"
48323 @1048323 //matching VO, "We must continue on our travels."->"We must continue our travels."
48334 @1048334 //horseshoe shaped
48471 @1048471 // "more often then not" -> "more often than not"
48472 @1048472 //tyrrany->tyrany
48473 @1048473 // Capitalisation. "(hmm, I have to wonder what she'll be like in twenty years.  Maybe with my help...)" -> "(Hmm, I have to wonder what she'll be like in twenty years.  Maybe with my help...)"
48492 @1048492 // "Yer a yellow kobold, ye are." -> "Ye're a yellow kobold, ye are."
48529 @1048529 //Jeirdan->Jierdan
48533 @1048533 //Jeirdan->Jierdan
48586 @1048586 //Jeridan->Jierdan
48633 @1048633 //desireable->desirable
48635 @1048635 //"ill got in origin"->"ill-got in origin"
48646 @1048646 //"Yer a weak stick"->"Ye're a weak stick"
48652 @1048652 //"than it should be. ."->"than it should be..."
48658 @1048658 //Two Handed, speed is wrong
48690 @1048690 //"shade lord"->"Shade Lord"
48726 @1048726 //"yer the bloody gnome"->"ye're the bloody gnome"
48779 @1048779 //"Calm yourself, rivvin."->"Calm yourself, rivvil."
48786 @1048786 //reknown->renowned
48791 @1048791 //halfing->halfling
48821 @1048821 // beyong -> beyond
48824 @1048824 //"yer pretty like an angel"->"ye're pretty like an angel"
48838 @1048838 //reknown->renowned
48852 @1048852 //intrument->instrument
48860 @1048860 //Roenal->Roenall
48867 @1048867 //Roenal->Roenall
48871 @1048871 //Roenal->Roenall
48884 @1048884 //"this 'gong"->"this gong"
48890 @1048890 // retreive -> retrieve, "<CHARNAME> and his band" -> "<CHARNAME> and <PRO_HISHER> band", "turnip beer bender"->"turnip-beer bender"
48910 @1048910 //"Always been a bit surley to newcomers"->"Always been a bit surly to newcomers"
48916 @1048916 //"Chaos "->"Chaos"
48952 @1048952 // "Couldn't spare just *one* coin?" -> "Couldn't you spare just *one* coin?"
48973 @1048973 //"The singleminded nature of the Rashemen"->"The singleminded nature of the Rashemeni"
48982 @1048982 //Aegiesfield->Aegisfield
49000 @1049000 //Neb's a gnome
49029 @1049029 //Sprit->Spirit
49050 @1049050 //"Child of Nature you are again needed."->"Child of Nature, you are again needed."
49107 @1049107 //"old enemies marshall their forces"->"old enemies marshal their forces"
49130 @1049130 //"yor body"->"your body"
49247 @1049247 //brethern->brethren
49323 @1049323 //replace inter-sentence quad-space with double-space
49338 @1049338 //Winspear
49382 @1049382 //imcompetence->incompetence
49445 @1049445 //ursurped
49457 @1049457 //somthing
49543 @1049543 //t'would->'twould
49588 @1049588 //"We# we"->"Well, we"
49630 @1049630 //"Yer a conquerer"->"Ye're a conqueror"
49711 @1049711 //it's->its
49925 @1049925 // sooth -> soothe
49931 @1049931 // Neb's a gnome
49943 @1049943 // Neb's a gnome
49950 @1049950 // Neb's a gnome
49979 @1049979 //"lets get out of this place"->"let's get out of this place"
49988 @1049988 //blashphemy->blasphemy
49992 @1049992 //"Calm yourself, rivvin."->"Calm yourself, rivvil."
50024 @1050024 //"I will be find"->"I will be fine"
50031 @1050031 //moent->moment
50038 @1050038 // worhty -> worthy
50096 @1050096 //"your voice, rivvin"->"your voice, rivvil"
50122 @1050122 // Neb's a gnome
50172 @1050172 //rivven->rivvin
50251 @1050251 //adminstering
50267 @1050267 //inisist
50269 @1050269 //"Here take the deed and prepare your self."->"Here, take the deed and prepare yourself."
50307 @1050307 //thows
50317 @1050317 //"I merely though you would be interesed"->"I merely thought you would be interested"
50393 @1050393 //prepatory
50418 @1050418 //warrented->warranted
50423 @1050423 //indespensible->indispensable
50427 @1050427 //impass->impasse
50470 @1050470 //insistant->insistent
50472 @1050472 //sufficiant->sufficient
50524 @1050524 //"length of it's stay"->"length of its stay"
50529 @1050529 //prehaps->perhaps
50535 @1050535 //lilly-footing->lily-footing, "I wonder of the fool even wants to stop the mad druids!"->"I wonder if the fool even wants to stop the mad druids!"
50583 @1050583 //"I have survived more self-righteous rivvil than you"->"I have survived more self-righteous rivvin than you"
50586 @1050586 //rivven->rivvin
50657 @1050657 //"a magic portal suddenly opens spawning a blood thirsty monster!"->"a magic portal suddenly opens, spawning a blood-thirsty monster!"
50679 @1050679 //"an opponents force"->"an opponent's force"
50694 @1050694 //lilly-livered->lily-livered
50730 @1050730 //"a group of Kuo-Toan's guarding a bridge"->"a group of Kuo-Toans guarding a bridge"
50731 @1050731 //happend
50737 @1050737 //north east, Grove.The
50781 @1050781 //D'Arnisse->de'Arnise
50790 @1050790 //dakness
50818 @1050818 //D'Arnisse
50827 @1050827 //speed correction
51029 @1051029 //adminstering->administering
51151 @1051151 //millenia->millennium
51176 @1051176 //Ust Nathan->Ust Natha
51195 @1051195 //"Peform and have nothing"->"Perform poorly and have nothing"
51210 @1051210 //presense->presence
51317 @1051317 //Veldin->Veldrin
51342 @1051342 //Threndle->Therndle
51364 @1051364 //decended->descended
51666 @1051666 //heirarchy->hierarchy
51672 @1051672 //uspeakable
51691 @1051691 //"statue,the"->"statue, the"
51770 @1051770 //tockenage->tokenage, mithril->mithral
51850 @1051850 //mithril->mithral
51851 @1051851 //mithril->mithral
51852 @1051852 //mithril->mithral
51884 @1051884 //thieves can use scimitars, speed is wrong
51945 @1051945 //STATISTICS
51947 @1051947 //thaco, speed is wrong
51949 @1051949 //thaco, speed is wrong, everytime
51952 @1051952 //STATISTICS, Abiltiies
51954 @1051954 //STATISTICS
51957 @1051957 //STATISTICS, "bonus to [...] pick pocketing"
51973 @1051973 //stubborness->stubbornness
52127 @1052127 //IGNOMNITY->IGNOMINY
52373 @1052373 //significan->significant
52539 @1052539 //brethern->brethren
52616 @1052616 //Lesaonar->Lasaonar
52689 @1052689 //Vhaerun->Vhaeraun
52724 @1052724 //Elistraee->Eilistraee
52732 @1052732 //end sentence with a period
52798 @1052798 //"House De Vir"->"House DeVir"
52801 @1052801 //"House De Vir"->"House DeVir"
52821 @1052821 //"House De Vir"->"House DeVir"
52957 @1052957 //Wesselan->Wessalen
53006 @1053006 //attemtping->attempting
53023 @1053023 //priveledge->privilege
53024 @1053024 //priveledge->privilege
53047 @1053047 //poweful
53060 @1053060 //Reirric->Reirrac
53088 @1053088 //end sentence with a period
53092 @1053092 //end sentence with a period
53103 @1053103 //priveledge->privilege
53104 @1053104 //priveledge->privilege
53119 @1053119 //positition->position
53296 @1053296 //Drizz't->Drizzt
53320 @1053320 //contemptable->contemptible
53403 @1053403 //"disgusting eight legged beast"->"disgusting eight-legged beast"
53683 @1053683 //palatte
53686 @1053686 //Roenal->Roenall
53750 @1053750 //presense->presence
53791 @1053791 //"south west"->southwest
53826 @1053826 //"new found friendship"->"new-found friendship"
53843 @1053843 //comapny->company
53877 @1053877 //"It is to dangerous"->"It is too dangerous"
53888 @1053888 //coudl->could
53928 @1053928 //assitance->assistance
53935 @1053935 //"th guild"->"the guild"
53993 @1053993 //"yer a customer"->"ye're a customer"
54054 @1054054 //"If yer plannin' on"->"If ye're plannin' on", "while yer at it"->"while ye're at it"
54075 @1054075 //Nelathir->Nelanther
54077 @1054077 //Nelanthir
54087 @1054087 //Nelanthir
54276 @1054276 //"If yer plannin' on"->"If ye're plannin' on", "while yer at it"->"while ye're at it"
54282 @1054282 //matching VO, "Perhaps you lose yourself in the end, but you will go to a greater reward than you can know."->"Perhaps you lose yourself in the end, but you will go to greater reward than you can know."
54311 @1054311 //abrubt->abrupt
54313 @1054313 //abrubt->abrupt
54432 @1054432 //"I barely escapes"->"I barely escaped"
54518 @1054518 //dispell->dispel
54538 @1054538 //abrubt->abrupt
54539 @1054539 //abrubt->abrupt
54555 @1054555 //"Don't you think that your overreacting"->"Don't you think that you're overreacting"
54671 @1054671 //"What... who... WHO DARES!"->"What... who... WHO DARES?!"
54857 @1054857 //matching VO, "You comess to usss at lassst, Child of Bhaal.  You comess to claimsss your heritage"
54892 @1054892 //everytime
54896 @1054896 //matching VO,  "You have come very nearss to locating your quarry...yesssss, indeedss you have."
54925 @1054925 //The militia captain is a woman, not a man
54926 @1054926 //Unecessary
55030 @1055030 //matching VO, "Yes, indeed you have."->"Oh yes, indeed you have."
55049 @1055049 //matching VO, "even the powerful"->"even the most powerful", "claims of power were hollow"->"claims of power were ssso hollow", "You tore them from their"->"You tore them down from their"
55052 @1055052 //matching VO, "And I am givingsss to you, now"->"And I am giving you, now"
55053 @1055053 //matching VO, "sssword called 'Blackrazor'"->"sssword that iss named 'Blackrazor'", needss->need
55054 @1055054 //matching VO, "how you usssse"->"how to usssse", leavesss->leave
55117 @1055117 //matching VO, "will do nicely"->"will do very nicely"
55124 @1055124 //matching VO, effect->effects
55211 @1055211 //matching VO, "What is this place?!"->"What... wha-what is this place?!", "and I felt... a dragging"->"and I felt... I felt a dragging"
55212 @1055212 //matching VO, "We died"->"I died", " this was not finished.  I came willingly... Mazzy Fentan"->"this was not finished, this battle. I felt your tugging and I came willingly... Mazzy Fentan"
55214 @1055214 //matching VO, "I felt your infernal power"->"Yes, I felt your infernal power"
55247 @1055247 //elswhere
55318 @1055318 //intenion
55319 @1055319 //"told of of the theft"->"told of the theft"
55372 @1055372 //interupted
55551 @1055551 //Imnesvail->Imnesvale
55556 @1055556 //Tyrriana->Tyrianna
55571 @1055571 //indescretion->indiscretion
55573 @1055573 //"duty is all important"->"duty is all-important"
55577 @1055577 //"self sacrifice"->"self-sacrifice"
55578 @1055578 //"self sacrificing"->"self-sacrificing"
55580 @1055580 //fortold
55603 @1055603 //"I was to lenient"->"I was too lenient"
55629 @1055629 //"Were were attacked"->"We were attacked"
55630 @1055630 //anit-magic
55631 @1055631 //Ketlar->Ketlaar
55632 @1055632 //Ketlar->Ketlaar
55633 @1055633 //bu->but
55653 @1055653 // miunderstood -> misunderstood
55666 @1055666 //start sentence with capital letter
55668 @1055668 //bewteen->between
55680 @1055680 //warrent->warrant
55725 @1055725 // "he probably looked to far" -> "he probably looked too far"
55747 @1055747 //"I am loathe"->"I am loath"
55749 @1055749 //obsenity->obscenity
55845 @1055845 //"life energy level"->"life-energy level", "life energy level drain"->"life-energy-level drain"
55864 @1055864 // Matching VO. "I don't want to be here" -> "I do not want to be here"
55882 @1055882 //"Don't worried"->"Don't be worried"
55886 @1055886 //"unwelcome my old hom has become"->"unwelcome it has become" (as per VO)
55889 @1055889 //manuever->maneuver
55928 @1055928 //sickenly->sickeningly
55950 @1055950 //"every rivvin who has wronged me"->"every rivvil who has wronged me"
55966 @1055966 //"I will not assist you fight him."->"I will not assist you fighting him."
55971 @1055971 //millenium
55995 @1055995 //tresspassing->trespassing
55996 @1055996 //tresspassing->trespassing
56012 @1056012 //fete->feat
56013 @1056013 //"to not not upset"->"to not upset"
56081 @1056081 // Aerie is not well-versed. "Corellan Latharian" -> "Corellon Larethian"
56083 @1056083 //"Corellan Latharian"->"Corellon Larethian", "propose to do join such ranks?" -> "propose to join such ranks?"
56101 @1056101 //"Yer a fine one fer words"->"Ye're a fine one fer words"
56149 @1056149 //"then yer dead"->"then ye're dead"
56151 @1056151 //monstous->monstrous
56155 @1056155 //"an I right"->"am I right"
56169 @1056169 //"These are Impressive risks"->"These are impressive risks"
56172 @1056172 //glimps->glimpse
56229 @1056229 //wll
56243 @1056243 //matching VO, "I... I was"->"I was"
56255 @1056255 //matching VO, "I was j-just"->"I was just"
56274 @1056274 //wimpering->whimpering
56298 @1056298 //matching VO, "grate on the nerves"->"grate on my nerves", "as I recall... so pull yourself together"->"as I recall... pull yourself together"
56345 @1056345 //matching VO, "bang a drum"->"bang on a drum"
56407 @1056407 //Vapiricus->Vampiricus
56410 @1056410 //"tragedy beyond meansure"->"tragedy beyond mention"
56473 @1056473 // Matching VO. "There.  It is done." -> "There. For good or ill, it is done.", "I want to hear no reprisements, either"->"I want to hear no reprisals, either"
56546 @1056546 //Jaheria -> Jaheira
56551 @1056551 //"well being"->"well-being"
56590 @1056590 //Ohgma->Oghma
56593 @1056593 //Ohgma->Oghma
56596 @1056596 //Lanthon->Lanthorn
56600 @1056600 // Matching VO. "thought myself worthy" -> "thought of myself worthy"
56658 @1056658 //"I new you"->"I knew you"
56668 @1056668 //"I my body, that... that thing does not die"->"If my body, that... that thing does not die", blood->hand (Dace's)
56671 @1056671 //shaman's->shaman, blood->hand
56672 @1056672 //blood->hand
56679 @1056679 //"that is was traumatic"->"that it was traumatic"
56790 @1056790 //"Away with yo"->"Away with you"
56809 @1056809 //Liason->Liaison
56863 @1056863 //"2 feet by 4 feet size"->"2 feet by 4 feet in size", end last sentence with a period
56882 @1056882 //"who's benefit"->"whose benefit"
56895 @1056895 //bazarre->bazaar
56942 @1056942 //Ghaundaur->Ghaunadaur
56943 @1056943 //Ghaundaur->Ghaunadaur
56948 @1056948 //Ghaundaur->Ghaunadaur
56949 @1056949 //Ghaundaur->Ghaunadaur
56953 @1056953 //T'would->'Twould
57150 @1057150 //"a millenia"->"a millennium"
57177 @1057177 //"Kill the lich loot his tower"->"Kill the lich and loot his tower"
57216 @1057216 //Gladatorial->Gladiatorial
57225 @1057225 //comdemned->condemned
57275 @1057275 //broudcast
57313 @1057313 //resposibility->responsibility
57322 @1057322 //obstinant->obstinate
57388 @1057388 //irrelevent->irrelevant
57412 @1057412 //"south eastern"->southeastern
57417 @1057417 //"Lolth has spoken her divine will me"->"Lolth has spoken her divine will through me"
57420 @1057420 //apopologies->apologies
57426 @1057426 //revernce->reverence
57456 @1057456 //permissable->permissible
57462 @1057462 //inherant->inherent
57478 @1057478 //"The Rope no longers seems to"->"The Rope no longer seems to"
57518 @1057518 //occured
57564 @1057564 //Vapiricus->Vampiricus
57565 @1057565 //Vapiricus->Vampiricus
57583 @1057583 //sulphorous->sulphurous
57593 @1057593 //"of the unconcious surface worlders"->"of the unconscious surface-worlders"
57630 @1057630 //"surface worlder's blood"->"surface-worlders' blood"
57650 @1057650 //stomache->stomach
57655 @1057655 //develope->develop
57668 @1057668 //"had to breath through the spigot"->"had to breathe through the spigot"
57671 @1057671 //"Yer a bit pale in the face"->"Ye're a bit pale in the face"
57676 @1057676 //"yer best in the lead"->"ye're best in the lead"
57681 @1057681 //"I wil be all right"->"I will be all right"
57701 @1057701 //"have ing"->"having"
57737 @1057737 //ammount
57766 @1057766 //Rillifiane->Rillifane
57864 @1057864 //chastizing->chastising
57881 @1057881 //south west
57888 @1057888 //occured
57903 @1057903 //unstrustworthy->untrustworthy
57926 @1057926 //"to guard duty over"->"to stand guard over"
57985 @1057985 //"Corellan Lotharian"->"Corellon Larethian", "Elven Panthenon" -> "Elven Pantheon"
57990 @1057990 //"Corellan Lotharian"->"Corellon Larethian"
58085 @1058085 //"Athkatla, In the end"->"Athkatla, in the end"
58139 @1058139 //achive->achieve
58143 @1058143 //stading->standing
58174 @1058174 // "but would I cross the street rather than walk by some of these... thieves." -> "but I would rather cross the street than walk by some of these... thieves."
58179 @1058179 //Thet->Then
58303 @1058303 //"it's multicolored eyes"->"its multicolored eyes"
58325 @1058325 //contendedly->contentedly
58408 @1058408 //warrent
58438 @1058438 //"goddess of caravans, Shaundakar"->"god of caravans, Shaundakul"
58489 @1058489 //Glavena->Galvena
58575 @1058575 //end sentence with a period
58580 @1058580 //end sentence with a period
58607 @1058607 //ressurected->resurrected
58608 @1058608 //"I will speak, but it shall be the last you here!"->"I will speak, but it shall be the last you hear!"
58680 @1058680 //deterrance->deterrent
58738 @1058738 // "How could you... How could you!!" -> "How could you...? How could you!?"
58749 @1058749 //theif
58838 @1058838 //Pefectly
58841 @1058841 //postition
58890 @1058890 //"Ye're kindred's spots betray ye"->"Yer kindred's spots betray ye"
58891 @1058891 //"nay stop lookin' over ye're shoulders"->"nay stop lookin' over yer shoulders"
58914 @1058914 //Iit->It
58920 @1058920 //"now yer berating me"->"now ye're berating me"
58922 @1058922 //"Yer a hard-arsed mule"->"Ye're a hard-arsed mule"
58924 @1058924 //Exacly->Exactly
58989 @1058989 // "It... from a friend of Quayle's" -> "It's... from a friend of Quayle's"
59108 @1059108 //presense->presence
59218 @1059218 //"half vampire body"->"half-vampire body"
59219 @1059219 //"half vampire body"->"half-vampire body"
59220 @1059220 //"half vampire body"->"half-vampire body"
59221 @1059221 //"half vampire body"->"half-vampire body"
59237 @1059237 //"loved on"->"loved one"
59372 @1059372 //Vapiricus->Vampiricus
59385 @1059385 //"have been quite a few old books turn up"->"have been quite a few old books turning up"
59395 @1059395 //"No you cannot"->"No, you cannot."
59426 @1059426 //inportance->importance
59481 @1059481 //matching VO, "So are we killing something now?" "So are we gonna... kill something now?"
59483 @1059483 //matching VO, "So, we going to kill something soon?  How about now?  No?  How about... now?  No?  Ummm... now?"->"So, are we gonna kill something soon? How about now? No? How about, uh... now? No? Ummm... now? What about now?"
59494 @1059494 //matching VO, "Advice, eh?  Well, besides working a little on your swordsmanship.  Besides that, I'd have to think."->"Advice, eh? Hmmm... well, besides working on your swordsmanship... you know, besides that... uh, I'd have to think..."
59495 @1059495 //matching VO, come up with it, Wahoo
59497 @1059497 //matching VO, Find someone->Then find someone
59498 @1059498 //matching VO, "Hmmm... I think"->"I think", "ranger's head."->"ranger's head. Haha!"
59500 @1059500 //matching VO, Woo-hoo->Hahahaa
59501 @1059501 //matching VO, "C'mon, grab a rag already..."->"Grab a rag already!"
59502 @1059502 //matching VO, "Err... find that wizard guy.  Yeah... find him and kill him.  Kill kill kill kill KILL!!    Whoo-hoo!!"->"Ahh... umm... uh, find the wizard guy. Yeah, sure... find 'im and kill 'im. Kill kill kill kill KILL!! Woo-hoo!!"
59510 @1059510 //matching VO, "Right now.  Go find one and kill it.  That would be SO cool."->"Right now. No, don't look. Go kill one now. Go find one and kill it. That's right: kill... now. That would be SO cool!"
59543 @1059543 //matching VO, "I agree with the Rashemaar.  Give me to him, willya?  What a pair!  Me the brains"->"Ooh... I agree with the Rashemaar! Give me to him, willya? C'mon! What a pair we'd make! Oh, me the brains"
59654 @1059654 //vistors
59758 @1059758 //Welll->Well
59845 @1059845 //occaision->occasion
59857 @1059857 //disapoint->disappoint
60274 @1060274 //veangeance->vengeance
60334 @1060334 //"This heres' the life"->"This here's the life"
60420 @1060420 //interupted->interrupted
60506 @1060506 //Sakolah->Sekolah
60633 @1060633 //end sentence with a period
60762 @1060762 //Lolths name->Lolth's name
60863 @1060863 //Thac0
60866 @1060866 //thaco
60871 @1060871 //Efreet->Efreeti, Salamaders->Salamanders
60877 @1060877 //thaco
60950 @1060950 //leopards have spots, not stripes
60958 @1060958 //"Yer a cleric"->"Ye're a cleric"
60959 @1060959 //occuring
60967 @1060967 //yer->ye're, "to found out"->"to find out"
60971 @1060971 //"Yer some noble type"->"Ye're some noble type"
60998 @1060998 //"Rarely have a seen its like"->"Rarely have I seen its like"
61059 @1061059 //T'were->'Twere
61095 @1061095 //Thayans->Thayvians
61154 @1061154 //"Yer not the <PRO_LADYLORD> patron... yer one o' <PRO_HISHER> friends"->"Ye're not the <PRO_LADYLORD> patron... ye're one o' <PRO_HISHER> friends"
61173 @1061173 //"who's estate"->"whose estate"
61286 @1061286 //start sentence with capital letter
61309 @1061309 //dispicable->despicable
61351 @1061351 //Two Handed
61449 @1061449 //"our swords and ours souls"->"our swords and our souls"
61574 @1061574 //STATISTICS, "Usable By"->"Usable By:"
61591 @1061591 //THACO
61595 @1061595 //STATISTICS
61598 @1061598 //STATISTICS, "forged the by the"->"forged by the", "where is was forged"->"where it was forged"
61809 @1061809 //"yer not the taxman"->"ye're not the taxman"
61904 @1061904 //"Yer a piece o' iron"->"Ye're a piece o' iron"
61915 @1061915 //Borinal->Borinall
62054 @1062054 //"third party communication"->"third-party communication"
62135 @1062135 //order->Order
62138 @1062138 //order->Order
62159 @1062159 //Mae-Var->Mae'Var
62160 @1062160 //Mae-Var->Mae'Var

USING "bg2fixpack/%LANGUAGE%/gtul.tra"

ACTION_IF FILE_EXISTS_IN_GAME mel01.cre BEGIN //ToB

STRING_SET
29214 @2529214 //Nishruus do not drain item charges in ToB
29220 @2529220 //ditto for Hakeashars
62323 @1062323 //Apparation
62490 @1062490 //challange
62622 @1062622 //millenium->millennium
62702 @1062702 //seperate->separate
62972 @1062972 //reknown
63028 @1063028 //horde of treasure
63040 @1063040 //Pehaps
63140 @1063140 //fleshing->fleshling
63220 @1063220 //"a disembodied head of red dragon"->"a disembodied head of a red dragon"
63406 @1063406 //perserverance->perseverance
63460 @1063460 //perserverance->perseverance
63468 @1063468 //Staff of Radiance
63470 @1063470 //Staff of Radiance
63545 @1063545 //"swirl of centuries old dust"->"swirl of centuries-old dust"
63570 @1063570 //missle
63573 @1063573 //"blood soaked corpse"->"blood-soaked corpse"
63586 @1063586 //"well furnished room"->"well-furnished room"
63616 @1063616 //"to THAC0, and when thrown does"->"to THAC0 and, when thrown, does"
63622 @1063622 //rushs->rushes
63639 @1063639 //siezes->seizes
63670 @1063670 //"reknowned match"->"renowned match"
63700 @1063700 //"it's bony finger"->"its bony finger"
63736 @1063736 //ta'anari->tanar'ri, baalor->balor
63743 @1063743 //"30 foot radius"->"30-foot radius", "acidic poisonous rain"->"acidic, poisonous rain"
63807 @1063807 //"it's golden trail"->"its golden trail"
63831 @1063831 //"an demonic"->"a demonic"
63833 @1063833 //perserverance->perseverance
64139 @1064139 //perserverance->perseverance
64142 @1064142 //specificially
64143 @1064143 //embarassments->embarrassments
64192 @1064192 //everytime
64235 @1064235 //Pyrgram->Pyrgam
64246 @1064246 //"Yaga Shura"->"Yaga-Shura"
64255 @1064255 //"coming to me personal like and sharing"->"coming to me, personal-like, and sharing"
64265 @1064265 //"Yaga Shura"->"Yaga-Shura"
64270 @1064270 //"Yer just like that"->"Ye're just like that"
64303 @1064303 //"Yaga Shura"->"Yaga-Shura", seige->siege
64304 @1064304 //"Yaga Shura"->"Yaga-Shura"
64305 @1064305 //"Yaga Shura"->"Yaga-Shura"
64367 @1064367 //"Yaga Shura"->"Yaga-Shura"
64376 @1064376 //"Yaga Shura"->"Yaga-Shura"
64377 @1064377 //"Yaga Shura"->"Yaga-Shura"
64379 @1064379 //Yaga Shura, Bhaal spawn
64410 @1064410 //"Yaga Shura"->"Yaga-Shura"
64481 @1064481 //"I am loathe"->"I am loath"
64548 @1064548 //sugary sweet soul
64559 @1064559 //replace inter-space quad-space with double-space
64634 @1064634 //"self serving weasel"->"self-serving weasel"
64661 @1064661 //exectuion
64840 @1064840 //"A far fetched tale"->"A farfetched tale"
64906 @1064906 //"he caught him red handed"->"he caught him red-handed"
64972 @1064972 //Erarrd
64998 @1064998 //"Yaga Shura"->"Yaga-Shura"
65000 @1065000 //"Yaga Shura"->"Yaga-Shura"
65094 @1065094 //"Yaga Shura"->"Yaga-Shura"
65265 @1065265 //T'is->'Tis
65267 @1065267 //t'is->'tis
65272 @1065272 //T'is->'Tis
65349 @1065349 //capital letter thing
65395 @1065395 //"The fool was far too gone."->"The fool was too far gone."
65579 @1065579 //"Yaga Shura"->"Yaga-Shura"
65580 @1065580 //"Yaga Shura"->"Yaga-Shura"
65594 @1065594 //"Yaga Shura"->"Yaga-Shura"
65769 @1065769 //"Bhaal spawn"->"Bhaalspawn, Yaga Shura->Yaga-Shura
65868 @1065868 //"Bhaal tainted blood"->"Bhaal-tainted blood"
65879 @1065879 //"Yaga Shura"->"Yaga-Shura"
65934 @1065934 //"Yaga Shura"->"Yaga-Shura"
65947 @1065947 //"Yaga Shura"->"Yaga-Shura"
65952 @1065952 //matching VO, "No, please, no!"->"No, please..."
65961 @1065961 //"Yaga Shura"->"Yaga-Shura"
65964 @1065964 //adds VO
65966 @1065966 //"Yaga Shura"->"Yaga-Shura"
65968 @1065968 //"Yaga Shura"->"Yaga-Shura"
65971 @1065971 //impertinance->impertinence
65972 @1065972 //"Yaga Shura"->"Yaga-Shura"
65976 @1065976 //"Yaga Shura"->"Yaga-Shura"
65979 @1065979 //"Yaga Shura"->"Yaga-Shura"
65984 @1065984 //"Yaga Shura"->"Yaga-Shura"
65988 @1065988 //"short sighted fools", Yaga Shura
65989 @1065989 //"Yaga Shura"->"Yaga-Shura"
65992 @1065992 //"Yaga Shura"->"Yaga-Shura"
66008 @1066008 //adds VO
66010 @1066010 //adds VO
66011 @1066011 //adds VO
66015 @1066015 //adds VO
66017 @1066017 //adds VO
66040 @1066040 //"Yaga Shura"->"Yaga-Shura"
66041 @1066041 //"Yaga Shura"->"Yaga-Shura"
66042 @1066042 //"Yaga Shura"->"Yaga-Shura"
66123 @1066123 //T'is->'Tis
66151 @1066151 //"slime loving excuse of a mage"
66153 @1066153 //"cold hearted monster"
66154 @1066154 //"red bodied beast"
66163 @1066163 //"slow burning torches"
66166 @1066166 //matching VO, "I...I am wounded!!"->"I am wounded?!?!"
66200 @1066200 //thaco, "Damage type piercing"
66201 @1066201 //thaco, "Damage type piercing"
66224 @1066224 //Frithior->Frithiof
66225 @1066225 //Baalor->Balor
66248 @1066248 //thaco, extra damage clarification
66254 @1066254 //thaco
66258 @1066258 //STATISTICS, single handed, thaco
66259 @1066259 //STATISTICS, thaco
66260 @1066260 //STATISTICS
66261 @1066261 //STATISTICS, "high ranking official"->"high-ranking official", Wakishashi->Wakizashi
66281 @1066281 //STATISTICS, reknown
66286 @1066286 //STATISTICS
66292 @1066292 //STATISTICS, Two Handed
66294 @1066294 //STATISTICS, Two Handed
66301 @1066301 //STATISTICS, Two Handed
66307 @1066307 //thaco
66312 @1066312 //thaco
66318 @1066318 //thaco
66330 @1066330 //STATISTICS
66361 @1066361 //STATISTICS, Baalor->Balor, "vorpal edged axe"->"vorpal-edged axe"
66362 @1066362 //thaco
66366 @1066366 //thaco, Abilites
66367 @1066367 //thaco, Abilites
66369 @1066369 //thaco, speed is wrong
66372 @1066372 //seperated->separated, "THAC0: + 4 bonus"->"THAC0: +4 bonus", speed is wrong
66377 @1066377 //thaco
66378 @1066378 //thaco
66379 @1066379 //thaco
66383 @1066383 //Thac0
66384 @1066384 //Thac0
66385 @1066385 //thaco
66387 @1066387 //thaco
66388 @1066388 //reknowned, thaco, thac0 correction
66389 @1066389 //thaco, thac0 correction
66393 @1066393 //thaco
66394 @1066394 //thaco
66402 @1066402 //thaco
66403 @1066403 //thaco
66404 @1066404 //thaco
66405 @1066405 //thaco
66409 @1066409 //STATISTICS
66421 @1066421 //druids can apparently use dragon scale armour
66423 @1066423 //"dwarvish hero"->"dwarven hero", "ill fated quest"->"ill-fated quest"
66424 @1066424 //thaco
66437 @1066437 //"dark elf ranger"->"dark-elf ranger", Usuable
66448 @1066448 //reknowned
66452 @1066452 //creedence
66453 @1066453 //beseiged
66454 @1066454 //STATISTICS
66455 @1066455 //Usuable, "Only those most worthy and devoted servants"->"Only the most worthy and devoted servants"
66456 @1066456 //Usuable, "Only those most worthy and devoted servants"->"Only the most worthy and devoted servants"
66457 @1066457 //Usuable, "Only those most worthy and devoted servants"->"Only the most worthy and devoted servants"
66463 @1066463 //Usuable, indented classes
66479 @1066479 //blindess, added what type of save it is
66551 @1066551 //matching VO, "Use my recipes for you will I, make the shiny ones."->"Use my recipes for you will, I... I make the shiny ones."
66570 @1066570 //"sea salt stinging eyes"->"sea-salt-stinging eyes"
66576 @1066576 //"double crossing rat"->"double-crossing rat"
66632 @1066632 //life draining powers
66672 @1066672 //Baalor->Balor
66673 @1066673 //Baalor->Balor
66691 @1066691 //"Would you llike?"->"Would you like?"
66731 @1066731 //"slack jawed yokel"->"slack-jawed yokel"
66808 @1066808 //"hard earned gold"->"hard-earned gold"
66854 @1066854 //"fighting skills were getting a might rusty"->"fighting skills were getting a mite rusty"
66924 @1066924 //end sentence with period
67141 @1067141 //Athakatla->Athkatla, Sythsillians->Sythillisians
67350 @1067350 //the the clearing, funny looking elves
67352 @1067352 //south west
67464 @1067464 //occurences->occurrences
67477 @1067477 //"slaughter filled progress"->"slaughter-filled progress"
67573 @1067573 //sufference->sufferance
67578 @1067578 //T'was->'Twas
67579 @1067579 //T'was->'Twas
67654 @1067654 //adds VO
67658 @1067658 //adds VO
67662 @1067662 //adds VO
67666 @1067666 //adds VO
67669 @1067669 //adds VO
67671 @1067671 //adds VO
67675 @1067675 //adds VO
67721 @1067721 //spurnned->spurned
67736 @1067736 //preceeds->precedes
67754 @1067754 //coincedence->coincidence
67767 @1067767 //do gooders->do-gooders
67768 @1067768 //chuch
67769 @1067769 //rivven->rivvin
67776 @1067776 //"alou sisters"->"alu-sisters"
67781 @1067781 //alou fiends
67782 @1067782 //"alou sisters"->"alu-sisters"
67897 @1067897 //"Iyachtu Svim"->"Iyachtu Xvim"
67907 @1067907 //T'is->'Tis
67912 @1067912 //rememberance->remembrance
67956 @1067956 // "than I suppose I can do that." -> "then I suppose I can do that."
68003 @1068003 //Rashemen warrior->Rashemeni warrior
68039 @1068039 //"Ye look a might down today."->"Ye look a mite down today."
68041 @1068041 //"I find that a might surprisin'."->"I find that a mite surprisin'."
68054 @1068054 //disparge->disparage
68060 @1068060 //matching VO, "Korgan, Boo"->"Korgaaan... Korgan, Korgan: Boo"
68081 @1068081 // Matching VO. "how you had to... to go." -> "how you had... to go.", "I... I understand" -> "I understand"
68128 @1068128 //Rasheman->Rashemen
68136 @1068136 //Rasheman->Rashemen
68140 @1068140 //Rasheman->Rashemen
68145 @1068145 //Rashemani witch->Rashemeni witch
68163 @1068163 // Matching VO / grammar. "as a initiate" -> "as an initiate"
68164 @1068164 // Matching VO. "rolled over him" -> "rolled over on him"
68171 @1068171 //Rashemani witch->Rashemeni witch
68184 @1068184 //privelege->privilege
68222 @1068222 //dischord->discord
68259 @1068259 //"no matter how you guild your words"->"no matter how you gild your words"
68289 @1068289 //twas->'twas
68294 @1068294 // Faenya-Dael -> Faenya-Dail
68298 @1068298 // Faenya-Dael -> Faenya-Dail
68340 @1068340 //resurgance->resurgence
68364 @1068364 //seperate->separate
68368 @1068368 //high handed condemnation, believeing
68402 @1068402 //greater then
68403 @1068403 // "I can have small affect on our future." -> "I can have a small effect on our future."
68477 @1068477 //"You're not upset are you?"->"You're not upset, are you?"
68479 @1068479 //prophesies->prophecies (what with prophesy being the act of uttering a prophecy)
68481 @1068481 // Mis-spaced full stop.
68507 @1068507 //fine looking, turnip farming
68508 @1068508 //"Yer losin me"->"Ye're losin me"
68535 @1068535 //mischievious->mischievous
68559 @1068559 //never ending
68565 @1068565 //"I have given that considerable though"->"I have given that considerable thought"
68609 @1068609 //T'is->'Tis, T'would->'Twould
68613 @1068613 //T'is->'Tis
68615 @1068615 //T'is->'Tis
68621 @1068621 //t'is->'tis
68623 @1068623 //t'is->'tis
68629 @1068629 //T'is->'Tis
68649 @1068649 //T'is->'Tis
68651 @1068651 //T'was->'Twas
68653 @1068653 //T'is->'Tis
68658 @1068658 //T'is->'Tis
68662 @1068662 //matching VO, "Well, no... I just..."->"Oh! Well, no... uh... I just thought..."
68722 @1068722 //tyrin'->tryin'
68727 @1068727 //"Yer handy enough"->"Ye're handy enough"
68730 @1068730 //"yer not hurting our group"->"ye're not hurting our group"
68731 @1068731 //"yer an o'er-lame excuse"->"ye're an o'er-lame excuse"
68735 @1068735 //"Yer a canker on me backside"->"Ye're a canker on me backside"
68739 @1068739 //"Yer a fine, fine lass"->"Ye're a fine, fine lass"
68742 @1068742 //"Yer a bloody killin' machine"->"Ye're a bloody killin' machine"
68749 @1068749 //Roenal->Roenall
68750 @1068750 //Roenal->Roenall
68755 @1068755 //resurection->resurrection
68758 @1068758 //"yer gonna get prissy"->"ye're gonna get prissy"
68784 @1068784 // "yer never in the mood" -> "ye're never in the mood
68786 @1068786 //Yer->Ye're, wanna be
68787 @1068787 //small minded->small-minded, small membered->small-membered
68794 @1068794 //curiousity->curiosity
68851 @1068851 //"fine lookin' woman"->"fine-lookin' woman"
68886 @1068886 //excrutiating
68917 @1068917 //incorrigable->incorrigible
68952 @1068952 //venemous
68955 @1068955 //scrumptuous
68984 @1068984 //mechanitions
69008 @1069008 //T'is->'Tis
69021 @1069021 //matching VO, "I've got to admit, Mazzy, that being your squire has been far more pleasant that I thought it would be."->"I gotta admit, Mazzy, that being your squire has been far more pleasant than I thought it'd be."
69039 @1069039 //embarassed
69080 @1069080 //"yer a sweet thing, lass.  Yer a halfling"->"ye're a sweet thing, lass.  Ye're a halfling"
69084 @1069084 //T'was->'Twas
69152 @1069152 // Faenya-Dael -> Faenya-Dail
69228 @1069228 //matching VO, "Boo and I always have time to speak with our friends, right Boo?"->"Boo and I always are having time to speak with our friends, yes no Boo?"
69239 @1069239 //rivel->rivvil
69340 @1069340 //irresistable->irresistible
69362 @1069362 //forsee
69453 @1069453 // appealling -> appealing
69518 @1069518 //end sentence with a period
69544 @1069544 // "these type of things." -> "these types of things."
69661 @1069661 //"mrann d'sinss"->"mrann d'ssinss"
69667 @1069667 //reasurances->reassurances
69725 @1069725 //grande scheme
69751 @1069751 //"maybe its time to start"->"maybe it's time to start"
69791 @1069791 //"m'rann d'sinss"->"mrann d'ssinss"
69866 @1069866 //"m'rann dssinss"->"mrann d'ssinss"
69952 @1069952 //rivven->rivvin
69993 @1069993 // Matching VO. "Perhaps this is not the place" -> "Perhaps this is not the best place"
70070 @1070070 //"m'rann dssinss"->"mrann d'ssinss"
70109 @1070109 // "more then comforting words" -> "more than comforting words
70133 @1070133 //"m'rann dssinss"->"mrann d'ssinss"
70138 @1070138 // unforseen
70157 @1070157 //"That's the way ter do it!"->"That's the way ye're do it!"
70165 @1070165 // "I pray you never have to chose." -> "I pray you never have to choose."
70166 @1070166 //"m'rann dssinnss"->"mrann d'ssinss"
70254 @1070254 // Matching VO. "a matter of... greatest importance." -> "a matter of... of greatest importance."
70290 @1070290 //"my childhood dreams to join the Order seems insignificant"->"my childhood dreams to join the Order seem insignificant"
70390 @1070390 //stangers
70473 @1070473 //There is not telling
70543 @1070543 //t'is->'tis
70549 @1070549 //t'is->'tis
70688 @1070688 //STATISTICS
70745 @1070745 //futher
70785 @1070785 //thaco, "exquisitely-crafted sword"->"exquisitely crafted sword", speed is wrong
70912 @1070912 //rune covered, fist sized
71003 @1071003 //"The problem is, everytime a globe is dispensed"->"The problem is, every time a globe is dispensed"
71028 @1071028 //Two Handed
71029 @1071029 //thaco
71030 @1071030 //thaco
71031 @1071031 //thaco
71033 @1071033 //Two Handed
71048 @1071048 //thaco
71050 @1071050 //thaco
71052 @1071052 //thaco
71054 @1071054 //thaco
71056 @1071056 //thaco
71058 @1071058 //thaco, speed is wrong, "the staff is as high as the archer is"->"the staff is as long as the archer is tall", thac0 correction
71060 @1071060 //thaco
71062 @1071062 //thaco
71065 @1071065 //"Yaga Shura"->"Yaga-Shura"
71070 @1071070 //"Yaga Shura"->"Yaga-Shura"
71073 @1071073 //thaco
71098 @1071098 //thieves can use scimitars, "enhanced magically to compliment the skill of the wielder."->"enhanced magically to complement the skill of the wielder.", thaco
71101 @1071101 //thaco
71211 @1071211 //"yer eating our food"->"ye're eating our food"
71279 @1071279 //"Yer a stranger"->"Ye're a stranger"
71320 @1071320 // "interested in you offer." -> "interested in your offer."
71391 @1071391 //"Yer a pretty one aren't ya?"->"Ye're a pretty one, aren't ya?"
71398 @1071398 //"Yer all a bunch of"->"Ye're all a bunch of"
71421 @1071421 //Suldanesselar->Sulanessellar
71511 @1071511 //"he cares about even more then his lifelong dream"->"he cares about even more than his lifelong dream"
71655 @1071655 //Rafeya->Rafeha
71783 @1071783 //accomodate->accommodate
71789 @1071789 //"Yaga Shura"->"Yaga-Shura"
71865 @1071865 //barrell->barrel
71898 @1071898 //monastary->monastery
71904 @1071904 //monastary->monastery
71912 @1071912 //monastary->monastery
71913 @1071913 //monastary->monastery
71941 @1071941 //monastary->monastery
71943 @1071943 //monastary->monastery
71944 @1071944 //monastary->monastery
71962 @1071962 //inherant->inherent
71963 @1071963 //inherant->inherent
71964 @1071964 //inherant->inherent
71977 @1071977 //Rafeya->Rahefa
72177 @1072177 //T'was->'Twas
72294 @1072294 //end sentence with period
72330 @1072330 //replace inter-sentence quad-space with double-space
72343 @1072343 //guath->gauth
72407 @1072407 //missle
72576 @1072576 // hadly -> hardly
72697 @1072697 //"Just don't get cacked is all I can say about it."->"Just don't get cracked is all I can say about it."
72708 @1072708 //"Yaga Shura"->"Yaga-Shura"
72822 @1072822 //end sentence with period
72837 @1072837 //"Yaga Shura"->"Yaga-Shura"
72872 @1072872 //Ziranda->Zaranda
73179 @1073179 //" Tase the pain of my fist!"->" Taste the pain of my fist!"
73207 @1073207 //Abzigal->Abazigal
73212 @1073212 //"These eggs are man made"->"These eggs are man-made"
73256 @1073256 //Suldanessalar, carved faced
73292 @1073292 //"Yaga Shura"->"Yaga-Shura"
73383 @1073383 //"I urge you gods speed."->"I urge you godspeed."
73384 @1073384 //Missle->Missile
73405 @1073405 //"Yaga Shura"->"Yaga-Shura"
73467 @1073467 //alway's->always
73729 @1073729 //crytalline->crystalline
73822 @1073822 //"Yaga Shura"->"Yaga-Shura"
73851 @1073851 //"Yaga Shura"->"Yaga-Shura"
73863 @1073863 //predestinied
73900 @1073900 //single handedly
73910 @1073910 //thaco
73911 @1073911 //Two Handed
73912 @1073912 //thaco, speed is wrong
73918 @1073918 //Roenal->Roenall
73921 @1073921 //Suldanessalar->Suldanessellar
73946 @1073946 //Marileth
73961 @1073961 //protitutes
USING "bg2fixpack/%LANGUAGE%/gtul.tra"

END

