IF
	Delay(15)
	AttackedBy([ANYONE],DEFAULT)
	HPLT(Myself,3)
THEN
	RESPONSE #100
		RunAwayFrom(LastAttackerOf(Myself),150)
END

IF
	See(LastAttackerOf(Myself))
	Range(LastAttackerOf(Myself),4)
THEN
	RESPONSE #30
		SelectWeaponAbility(SLOT_WEAPON1,0)
		Attack([PC])
	RESPONSE #70
		RunAwayFrom([PC],75)
END

IF
	See(LastAttackerOf(Myself))
THEN
	RESPONSE #100
		SelectWeaponAbility(SLOT_AMMO,0)
		Attack([PC])
END

